### ISSUE TITLE
Option to report absolute path name of file with problems

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1051]
In GitLab by @jarshwah on Mar 26, 2017, 15:24

*Please describe the problem or feature*

I'd like to be able to report the absolute path of the file containing violations. Mainly, this would help when using the Jenkins warnings plugin (https://kaosktrl.wordpress.com/2015/09/03/static-code-analysis-in-python-with-jenkins/) to report on code quality trends. For Jenkins to be able to view the actual file from the web UI, it requires the absolute path to the file.

Would there be interest in this feature? I'd be happy to investigate and perhaps sending in a patch.

Current output:

```
$ /usr/local/bin/flake8 apps/myapp/mixins.py
apps/myapp/mixins.py:0:1: C101 Coding magic comment not found
apps/myapp/mixins.py:35:13: E128 continuation line under-indented for visual indent
apps/myapp/mixins.py:38:13: E124 closing bracket does not match visual indentation
apps/myapp/mixins.py:42:13: E124 closing bracket does not match visual indentation
```

Proposed output:

```
$ /usr/local/bin/flake8 apps/myapp/mixins.py
/Users/me/project/apps/myapp/mixins.py:0:1: C101 Coding magic comment not found
/Users/me/project/apps/myapp/mixins.py:35:13: E128 continuation line under-indented for visual indent
/Users/me/project/apps/myapp/mixins.py:38:13: E124 closing bracket does not match visual indentation
/Users/me/project/apps/myapp/mixins.py:42:13: E124 closing bracket does not match visual indentation
```

*Please describe how you installed Flake8*

```
$ pip3 install flake8  # + additional plugins
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
$ /usr/local/bin/flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "25.2.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.5.2",
    "system": "Darwin"
  },
  "plugins": [
    {
      "plugin": "flake8-string-format",
      "version": "0.2.3"
    },
    {
      "plugin": "flake8_coding",
      "version": "1.3.0"
    },
    {
      "plugin": "flake8_isort",
      "version": "2.1.3"
    },
    {
      "plugin": "mccabe",
      "version": "0.5.3"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.2.0"
    },
    {
      "plugin": "pyflakes",
      "version": "1.3.0"
    }
  ],
  "version": "3.2.1"
}
```

**Comment by asottile** [comment]
In GitLab by @jarshwah on Apr 2, 2017, 16:02

If this idea is accepted, I'm happy to put the work in to making it happen. I'd like to avoid doing the work if the idea isn't accepted though, so I'm just awaiting confirmation that I should go ahead.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 2, 2017, 17:21

Hi @jarshwah I'm so sorry I've been so very busy. I don't think Flake8 needs this as an option built-in. I think this would be a good use-case for an alternate [formatter plugin](http://flake8.pycqa.org/en/latest/plugin-development/formatters.html) that would report them. That would allow you to register it and then do `--format=full-path`.

Thanks for bringing us your idea, filing this issue, and respectfully nudging me again. :-) :tada: :cake:

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 2, 2017, 17:21

closed

**Comment by asottile** [comment]
In GitLab by @jarshwah on Apr 2, 2017, 17:36

I understand being busy and forgetting to respond to OS issues, no problems there :)

I'll give writing a formatter plugin a try, thanks for the pointer.

**Comment by marc-legendre** [comment]
Quick note for anyone stumbling on this issue: YMMV, but it seems that calling flake8 with absolute paths on the command line does the job.

**Comment by jarshwah** [comment]
I did write a plugin back then too but switched off Jenkins shortly after and didn’t need it anymore. https://github.com/jarshwah/flake8_formatter_abspath If someone else needs a starter.
