### ISSUE TITLE
Support pyflakes 1.6.0

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1058]
In GitLab by @bxm156 on Aug 3, 2017, 13:40

PyFlakes 1.6.0 was released today, it would be great if flake8 would support it.

Fake8 pins pyflakes < 1.6.0. I'm not sure if that was for any specific reason, if it was just a precaution, but I was able to run flake8 with pyflakes 1.6.0 without problem.

I'd like to be using v1.6.0 of pyflakes because it fixes a few bugs relating to static typing with python 3.6 that I have been encountering.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 3, 2017, 16:50

We've documented why we cap our versions [here](http://flake8.pycqa.org/en/latest/faq.html#why-does-flake8-use-ranges-for-its-dependencies). And we document our release methodology [here](http://flake8.pycqa.org/en/latest/internal/releases.html#releasing-flake8), specifically that we will only upgrade PyFlakes in the next Minor release, e.g., 3.5.0. That's why I've added the 3.5.0 milestone to this issue.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 3, 2017, 16:50

closed

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 3, 2017, 16:50

reopened

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 3, 2017, 16:51

Sorry, didn't mean to close this.

**Comment by asottile** [comment]
In GitLab by @bxm156 on Aug 3, 2017, 18:03

Ah, good to know. Thanks! Can't wait for the next release.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 6, 2017, 17:53

3.5.0 is in development and a change for this has been merged to master. Cheers!

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 6, 2017, 17:53

closed

**Comment by asottile** [comment]
In GitLab by @henryJack on Sep 4, 2017, 06:07

Really looking forward to pyflakes 1.6.0. Thanks for the great work. Fantastic tool.

**Comment by asottile** [comment]
In GitLab by @tnir on Feb 25, 2018, 01:45

Memo: this looks closed by !201 :tada:

**Comment by tnir** [comment]
> Memo: this looks closed by !201 🎉

`!201` is no more available in 2021. 7db5561363c2d03690474915776af0cde1173841 is the canonical URL 😄 

@asottile Thanks for maintaining the issue! Are you moving Issues from GitLab.com to GitHub.com?
