### ISSUE TITLE
Add flags similar to pydocstyle's --add-select/--add-ignore

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1061]
In GitLab by @sigmavirus24 on Aug 19, 2017, 04:49

These flags are quite useful for folks who merely want to extend the existing select and ignore lists. That said, we've found in pydocstyle that the `--add` verb is confusing to some. I would suggest `--extend-(select|ignore)` instead.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 19, 2017, 04:49

cc @mfcabrera

**Comment by asottile** [comment]
In GitLab by @scop on May 13, 2018, 14:08

mentioned in merge request !233

**Comment by asottile** [comment]
In GitLab by @fwinkl on Jun 8, 2020, 07:22

mentioned in merge request !437

**Comment by MarcoGorelli** [comment]
Bit confused about this issue - doesn't flake8 already have extend-ignore?

**Comment by sigmavirus24** [comment]
Yes but it doesn't have `--extend-select`

**Comment by asottile** [comment]
via #1312
