### ISSUE TITLE
Only flake8 and mypy are still missing pyproject.toml support

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1117]
In GitLab by @elgalu on Feb 5, 2021, 12:40

As of 2021, only flake8 and mypy are still missing pyproject.toml support.

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 5, 2021, 12:50

#428 

this is your first warning, please be cordial or I will ban you from further contributions

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 5, 2021, 12:50

locked this issue

**Comment by ilCatania** [comment]
hi @asottile can you please point us to the long locked thread mentioned here? the link seems to be going to an unrelated issue? apologies for not being able to find it myself...

**Comment by asottile** [comment]
https://github.com/PyCQA/flake8/issues?q=is%3Aissue+is%3Aopen+pyproject.toml

**Comment by asottile** [comment]
https://github.com/PyCQA/flake8/issues/234
