### ISSUE TITLE
options: Remove parsing `--output-file` from the configuration file - [merged]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1246]
In GitLab by @ericvw on Oct 12, 2019, 07:48

_Merges remove-output-file-config -> master_

The `--output-file` option is used when parsing and handling preliminary
options for logging.  It is also used to set `BaseFormatter.filename`.
Towards ensuring that the option is respected consistently for both
logging and formatting plugins, only observe the value from the CLI.

**Comment by asottile** [comment]
In GitLab by @codecov on Oct 12, 2019, 07:49

# [Codecov](https://codecov.io/gl/pycqa/flake8/pull/361?src=pr&el=h1) Report
> Merging [#361](https://codecov.io/gl/pycqa/flake8/pull/361?src=pr&el=desc) into [master](https://codecov.io/gl/pycqa/flake8/commit/0359533fca164ef21c40c8074fbd3899316b8f91?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gl/pycqa/flake8/pull/361/graphs/tree.svg?width=650&token=QL6TVnaXih&height=150&src=pr)](https://codecov.io/gl/pycqa/flake8/pull/361?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #361   +/-   ##
=======================================
  Coverage   81.89%   81.89%           
=======================================
  Files          24       24           
  Lines        2403     2403           
  Branches      388      388           
=======================================
  Hits         1968     1968           
  Misses        366      366           
  Partials       69       69
```


| [Impacted Files](https://codecov.io/gl/pycqa/flake8/pull/361?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/flake8/main/options.py](https://codecov.io/gl/pycqa/flake8/pull/361/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9tYWluL29wdGlvbnMucHk=) | `100% <ø> (ø)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gl/pycqa/flake8/pull/361?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gl/pycqa/flake8/pull/361?src=pr&el=footer). Last update [0359533...bb12b83](https://codecov.io/gl/pycqa/flake8/pull/361?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by asottile** [comment]
In GitLab by @asottile on Oct 12, 2019, 20:48

merged

**Comment by asottile** [comment]
In GitLab by @asottile on Oct 12, 2019, 20:48

mentioned in commit daca2c80db42de1b69b73db84abfc7db1c9e4463

**Comment by unchris** [comment]
@asottile I'm unable to file an issue/PR at the moment but wanted to point out that the documentation for `-tee` still shows an example of specifying `output-file` in the config file. I mistakenly used that example and found that it indeed does not work, leading me on a search until I found this issue and #1289 showing that the functionality was removed.

**Comment by asottile** [comment]
ah, sometimes the docs lag behind the implementation -- I'll update that
