### ISSUE TITLE
Add --extend-select command line argument - [opened]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1274]
In GitLab by @fwinkl on Jun 8, 2020, 07:22

_Merges extend_select -> master_

Implement `--extend-select` command line argument following what was
done for `--extend-ignore` in !233. This option can be used to
selectively add individual codes without overriding the default list
entirely.

Addresses the remaining item of issue #365.

**Comment by asottile** [comment]
In GitLab by @fwinkl on Jun 8, 2020, 07:24

Commented on [tests/unit/test_decision_engine.py line 198](https://github.com/PyCQA/flake8/compare/a7be77f761a4c29121d6bb6f61c11902281f9105..7db4f246a7b6c430baaac9fbef32698caa879d16#diff-f99de482e9d9043eff5fd016859a1862R198)



The changes here (`extend_select` -> `extended_default_select`) are just to avoid confusion with the now separate `extend_select` command line option).

**Comment by asottile** [comment]
In GitLab by @fwinkl on Jun 8, 2020, 07:26

Not sure why the docs unit test fails. `tox -e docs` works locally for me and I did not make any changes in `FileProcessor`. Could someone advise?

**Comment by asottile** [comment]
In GitLab by @asottile on Jun 10, 2020, 07:44

I've banned sphinx==3.1.0 -- they committed a regression

**Comment by asottile** [comment]
In GitLab by @fwinkl on Jun 10, 2020, 23:56

added 4 commits

<ul><li>ea753d3c...a7be77f7 - 3 commits from branch <code>pycqa:master</code></li><li>7db4f246 - Add --extend-select command line argument</li></ul>

[Compare with previous version](/pycqa/flake8/-/merge_requests/437/diffs?diff_id=95128657&start_sha=ea753d3c5405ce5791d689f89168e3e83954efa2)

**Comment by asottile** [comment]
In GitLab by @codecov on Jun 10, 2020, 23:57

# [Codecov](https://codecov.io/gl/pycqa/flake8/pull/437?src=pr&el=h1) Report
> Merging [#437](https://codecov.io/gl/pycqa/flake8/pull/437?src=pr&el=desc) into [master](https://codecov.io/gl/pycqa/flake8/commit/a7be77f761a4c29121d6bb6f61c11902281f9105&el=desc) will **increase** coverage by `0.00%`.
> The diff coverage is `100.00%`.

[![Impacted file tree graph](https://codecov.io/gl/pycqa/flake8/pull/437/graphs/tree.svg?width=650&height=150&src=pr&token=QL6TVnaXih)](https://codecov.io/gl/pycqa/flake8/pull/437?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master     #437   +/-   ##
=======================================
  Coverage   90.74%   90.75%           
=======================================
  Files          59       59           
  Lines        4192     4195    +3     
  Branches      417      417           
=======================================
+ Hits         3804     3807    +3     
  Misses        335      335           
  Partials       53       53           
```


| [Impacted Files](https://codecov.io/gl/pycqa/flake8/pull/437?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/flake8/style\_guide.py](https://codecov.io/gl/pycqa/flake8/pull/437/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9zdHlsZV9ndWlkZS5weQ==) | `98.51% <ø> (ø)` | |
| [src/flake8/main/options.py](https://codecov.io/gl/pycqa/flake8/pull/437/diff?src=pr&el=tree#diff-c3JjL2ZsYWtlOC9tYWluL29wdGlvbnMucHk=) | `100.00% <100.00%> (ø)` | |
| [tests/unit/test\_decision\_engine.py](https://codecov.io/gl/pycqa/flake8/pull/437/diff?src=pr&el=tree#diff-dGVzdHMvdW5pdC90ZXN0X2RlY2lzaW9uX2VuZ2luZS5weQ==) | `100.00% <100.00%> (ø)` | |
| [tests/unit/test\_style\_guide.py](https://codecov.io/gl/pycqa/flake8/pull/437/diff?src=pr&el=tree#diff-dGVzdHMvdW5pdC90ZXN0X3N0eWxlX2d1aWRlLnB5) | `100.00% <100.00%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gl/pycqa/flake8/pull/437?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gl/pycqa/flake8/pull/437?src=pr&el=footer). Last update [a7be77f...7db4f24](https://codecov.io/gl/pycqa/flake8/pull/437?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by asottile** [comment]
In GitLab by @fwinkl on Jun 11, 2020, 24:00

Thanks!

**Comment by asottile** [comment]
In GitLab by @fwinkl on Oct 5, 2020, 09:11

Since this has been sitting for a while (and since this is my first contribution), is there anything else needed to move this into the next release? Just want to make sure I am not missing a step.

**Comment by asottile** [comment]
In GitLab by @asottile on Oct 5, 2020, 09:18

yeah since it's a new feature it couldn't go into master at the time since it was the bugfix period

**Comment by fwinkl** [comment]
@asottile, could I ask why this PR was closed without explanation?

**Comment by asottile** [comment]
@fwinkl this isn't a pull request, it's a placeholder issue representing a pull request

**Comment by fwinkl** [comment]
@asottile thanks for the clarification. Will the GitLab merge requests be migrated automatically to github or do I need to do something myself?

**Comment by asottile** [comment]
they will not, you will need to recreate anything that got closed as part of the move
