### ISSUE TITLE
Clarify `--ignore` arguments are used as prefixes, not as specific codes

### ISSUE THREAD

**Issue by jvanasco** [PyCQA/flake8#1310]
The "help" for flake8 suggests `--ignore` arguments are used to filter out error codes:

https://github.com/PyCQA/flake8/blob/e0116d8e77fb04acc62095734ec49e779f24ee54/src/flake8/main/options.py#L206-L214

The docs for flake8 routinely mention "specific errors", such as `docs/source/index.rst`

> Alternatively, if you want to *ignore* only one specific warning or error:
>.. code::
>    flake8 --ignore E24,W504 path/to/code/

The arguments to --ignore are used as prefixes though, which I only learned through several contributors explaining that all docs plugins can be silenced by using their prefixes, e.g. `--ignore D,RST`

This behavior is GREAT and a lifesaver. However, the docs and help teach against this - and if it weren't for contributors answering this question many times across the internet, even fewer people would know about it.

**Comment by asottile** [comment]
this is documented already in [selecting and ignoring errors](https://flake8.pycqa.org/en/latest/user/violations.html)

**Comment by asottile** [comment]
note that your link also documents that, E24 is not a real code but a prefix match

**Comment by sigmavirus24** [comment]
It's _not_ just prefixes though. It can be exact matches or it can be a prefix. It's either or.

**Comment by FichteFoll** [comment]
One could argue that an exact match is still a prefix match (a "full prefix match" so to say?).

**Comment by sigmavirus24** [comment]
Anyone can argue anything they like. One can also argue that exclusively describing it as a prefix match will confuse some people into thinking they _can't_ specify a full error code. So one could argue anything without getting to the root of "What will user's react best to?"

Is there a gap explaining that prefixes _can_ be used? Maybe? I think there are plenty of examples. Is it fair to confuse people by only describing it as a prefix match? Absolutely not
