### ISSUE TITLE
flake8 hangs indefinitely on macOS Big Sur

### ISSUE THREAD

**Issue by philippefutureboy** [PyCQA/flake8#1313]
flake8 hangs indefinitely and consumes high amounts of CPU (99.9% of a single core).

```
$ black "." --check
All done! ✨ 🍰 ✨
255 files would be left unchanged.
# near instantaneous

$ isort "." --check-only
Skipped 4 files
# near instantaneous

$ flake8 "." --select F5,F6,F7,F8,E9,W
^C... stopped
# stopped after 5 minutes
```

**Please describe how you installed Flake8**

**OS:** MacOS Big Sur 11.2.3 (20D91)
**Model:** MacBook Pro (16-inch, 2019)
**Processor:** 2.4 GHz 8-Core Intel Core i9
**Memory:** 32 GB 2667 MHz DDR4
**Python version:** Python 3.8.7
**pyenv version:** pyenv 1.2.26
**pip version:** pip 21.0.1

Example:

```
$ . .venv/bin/activate
$ python -m pip install --upgrade -r requirements.dev.txt
```

where `requirements.dev.txt` is the following:

```
black
flake8
GitPython==3.1.14
invoke
isort
jupyterlab-server==2.1.3
matplotlib==3.3.4
pylint==2.6.0
pyroots==0.5.0
pytest-describe==1.0.0
pytest-snapshot==0.4.2
pytest-watch==4.2.0
pytest==6.2.1
python-dotenv==0.15.0
python-githooks==1.0.6
python-redis-cache==1.1.1
redis==3.5.3
rope==0.18.0
setuptools
wheel
```

**Please provide the exact, unmodified output of `flake8 --bug-report`**

```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.7",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    }
  ],
  "version": "3.9.0"
}
```

Let me know if you need any extra information :)

**Comment by asottile** [comment]
probably has nothing to do with big sur, you're probably linting a virtualenv (need to tweak your `exclude`)

**Comment by philippefutureboy** [comment]
Touché! Doing an exclude=(the whole content of gitignore) makes flake8 return fine.

You can close whenever you want. Thanks @asottile !
