### ISSUE TITLE
Possible to register per-file builtins?

### ISSUE THREAD

**Issue by minrk** [PyCQA/flake8#1316]
*Please describe how you installed Flake8*

Example:

```
$ pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

<details>
<summary> flake8 --bug-report </summary>

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.8",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.6.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.2.0"
    }
  ],
  "version": "3.8.4"
}
```

</details>

*Please describe the problem or feature*

flake8 supports declaring [builtins](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-builtins) to avoid F821 errors in specific names, e.g. for custom names injected into the namespace.

I have a few files with specific injected names, e.g. functions deserialized into a remote namespace, or config files run in a pre-populated namespace,  where pyflakes can't reasonably be expected to resolve certain names. I, however, know exactly what these names are, so it's a perfect use case for the `builtins` config. However, they are not 'global' builtins, injected for every file, they are only in certain files, and some are not shared across files. It would be great to be able to declare the injected names via the existing builtins config *per-file*, but I haven't figured out how. Lots of `#  noqa: F821` lines isn't ideal, both because it hides F821 for other symbols on the line, and because it's needed once per symbol occurrence rather than per symbol. I would love to be able to do something like:

```python
# flake8: builtins=get_config,something_else
```

similar to what can currently be done with `#flake8: noqa`. I'm not sure if this is a feature request or a documentation request, but I couldn't figure out how to do it. It seems plausible that any file with `# flake8: option=value` would have the equivalent result of the same config in `.flake8`, but I'm guessing that's not how things work, as much as I'd like it to.

I'm open to any solution to "declare names that would otherwise cause F821" that doesn't require a noqa comment for every line where the name occurs.

So far, the best I've come up with is:

```python
if False:
    # declare injected names with unreachable code
    name = None
```

**Comment by sigmavirus24** [comment]
> # flake8: builtins=get_config,something_else

That's not at all how this works or has ever been documented to work. Further, given the current complexity of configuration in the project, it's not in sight as a reasonable goal.

> I'm open to any solution to "declare names that would otherwise cause F821" that doesn't require a noqa comment for every line where the name occurs.

This sounds like an incredibly niche use case. I don't think this is something we should be supporting (and thus encouraging). Starting to try to support/ignore injected built-ins seems like encouraging people to start writing code with more injected built-ins and that way lies Ruby (which is a language I enjoy, but not the language Flake8 is designed for).

**Comment by asottile** [comment]
I'm going to reject this feature request -- injected builtins is a smell / hack to begin with (your code is doing something that goes against reasonable static expectations) and my recommendation is to refactor your code to fix the maintainability issue (magical variables)

**Comment by minrk** [comment]
Thanks for the note. You're wrong about the code, but I'll deal with it.
