### ISSUE TITLE
Feature: option to display configuration used

### ISSUE THREAD

**Issue by peendebak** [PyCQA/flake8#1324]
*Please describe how you installed Flake8*

Installation in `virtualenv` under Windows:
```
$ pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

`flake8 --bug-report`
```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.6",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.6.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.2.0"
    }
  ],
  "version": "3.8.4"
}
```
*Please describe the problem or feature*

When setting up `flake8` the tool can retrieve configuration from various locations. Can we create an option for `flake8` to display which configuration options are used (or, display which configuration files are used)? 
This can help to avoid confusion when `flake8` is (for one reason or the other) not finding or using the desired configuration.

**Comment by asottile** [comment]
`-vv` includes this information
