### ISSUE TITLE
per-file-ignores specified in file

### ISSUE THREAD

**Issue by bagerard** [PyCQA/flake8#1325]
I know the feature exists at the config level (`per-file-ignores`) but I see added value for large projects in having it explicitely defined in the file itself instead of being centralized in the config.

This would be something like `# flake8 noqa: A1,F821` on top of the file, extending the `# flake8: noqa` feature that ignores the whole file

I manage to make this work by patching flake8's Violation class from a plugin but that's clearly a hack, I was wondering if the feature was of interest for you? Let me know what you think

**Comment by asottile** [comment]
dupe #1079

**Comment by asottile** [comment]
it may be a possible extension in the future, but for now it'd be difficult to hack it on.  I'm currently (slowly) working on a reorganization that would make a feature like this easy

**Comment by bagerard** [comment]
HI @asottile, sorry to bother you with this again but could you mind provide an update on this "reorganization task"? Not pushing but just so that I have an idea if it was done or will/won't be done. In fact it's unclear to what task you are referring to and it would be helpful if you could link a ticket or something. Thanks ;)

**Comment by asottile** [comment]
I wouldn't count on it happening any time soon, there's a lot of structural change that needs to happen for this to be possible without ballooning complexity

additionally, you can already accomplish what you want today via `per-file-ignores` so this feature likely won't ever be implemented

**Comment by bagerard** [comment]
Alright, no problem, thanks for the update :+1:

**Comment by bagerard** [comment]
For future ref, I ended up implementing this as a plugin https://github.com/bagerard/flake8-in-file-ignores

**Comment by asottile** [comment]
mutating the options like that is going to break. I would not recommend that
