### ISSUE TITLE
Why not flake8 disable linter only for a block of code (multiple lines)

### ISSUE THREAD

**Issue by xareelee** [PyCQA/flake8#1336]
## Feature request

This problem has been issued on stackoverflow for a long time:

- https://stackoverflow.com/questions/50099780/tell-flake8-to-ignore-a-few-consecutive-lines
- https://stackoverflow.com/questions/46795404/how-to-flake8-ignore-in-multiline-code
- https://stackoverflow.com/questions/64428794/flake8-disable-linter-only-for-a-block-of-code

Now I need to add `# noqa: E272` to each line to ignore spaces for alignment:

```python
def get_fruit(value) -> int:
    return (
        FruitType.APPLE     if value == "apple" else    # noqa: E272
        FruitType.ORANGE    if value == "orange" else   # noqa: E272
        FruitType.BANANA    if value == "banana" else   # noqa: E272
        FruitType.GRAPE     if value == "grape" else    # noqa: E272
        None
    )
```

Why not support something like `# noqa-start: E272` / `# noqa-end: E272` between lines:

```python
def get_fruit(value) -> int:
    return (
         # noqa-start: E272
        FruitType.APPLE     if value == "apple" else   
        FruitType.ORANGE    if value == "orange" else
        FruitType.BANANA    if value == "banana" else
        FruitType.GRAPE     if value == "grape" else
         # noqa-end: E272
        None
    )
```

I think this feature is common in other linters, doesn't it?

**Comment by asottile** [comment]
dupe #324

**Comment by kerrick-js** [comment]
Issue #324 is currently locked. Can we unlock it so that discussion can continue there?

**Comment by asottile** [comment]
no
