### ISSUE TITLE
--jobs Doesn't Work on Mac with Python 3.8+

### ISSUE THREAD

**Issue by wbond** [PyCQA/flake8#1337]
*Please describe how you installed Flake8*

```
$ pipenv install
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.5",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "black",
      "version": "0.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "21.4.3"
    },
    {
      "is_local": false,
      "plugin": "flake8-print",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_builtins",
      "version": "1.5.2"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    }
  ],
  "version": "3.9.0"
}
```

*Please describe the problem or feature*

The `--jobs` parameter does nothing on macOS with Python 3.8+.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

I ran `flake8 --jobs=8` and it took as long as `flake8 --jobs=1`. It appears that Python 3.8+ on Mac uses `spawn` as the default multiprocessing method. This apparently doesn't work with flake8.

I see this as mostly a documentation bug. Currently the docs say `--jobs` is ignored on Windows, but it should mention Mac and 3.8+.

An alternative, and possibly better, fix would be to error if `--jobs` is specified on a platform that can't respect that arg.

**Comment by asottile** [comment]
fwiw I have plans in the future to rework the plugin system to enable multiprocessing on all platforms which have a multiprocessing module.  but it's a lot of work and I haven't had a ton of freetime to hack on it recently

**Comment by wbond** [comment]
To be honest, the documentation change would still require the vast majority of users to dig into the source code to determine why jobs isn’t working.

**Comment by asottile** [comment]
there is a warning at least:

```console
$ ./venv/Scripts/flake8.exe -v t.py |& grep multiprocessing
flake8.checker            MainProcess    115 WARNING  The multiprocessing module is not available. Ignoring --jobs arguments.
```

**Comment by wbond** [comment]
It did not strike me to turn on verbose mode. Although the error message is somewhat inaccurate, since clearly the multiprocessing module *is* available, it just doesn't support the proper mode.

Either way, my intent is mostly to try and help users determine why jobs isn't working sooner. Hopefully this issue being indexed by Google will help.

**Comment by amw** [comment]
For what it's worth I found `flake8` to be quite safe to use with `fork` multiprocessing start method under macOS. I have this modified CLI script that I use, but maybe we could just do it in official `flake8` CLI?

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import sys
from flake8.main.cli import main
from multiprocessing import set_start_method
if __name__ == '__main__':
    set_start_method('fork')
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

And the results:
```fish
$ time flake8

________________________________________________________
Executed in   13.56 secs    fish           external
   usr time   13.21 secs    0.06 millis   13.21 secs
   sys time    0.32 secs    1.23 millis    0.32 secs

$ time bin/flake8

________________________________________________________
Executed in    3.79 secs    fish           external
   usr time   15.33 secs    0.06 millis   15.33 secs
   sys time    0.45 secs    1.51 millis    0.45 secs

```

I also think it should not be difficult to support `spawn` (Python 3.8 default on macOS) start method even if you need to read all configuration and load all plugins again in new processes. It will still be way faster than single threaded processing. There is similar effort in Django with promising results:
https://code.djangoproject.com/ticket/31169

`flake8`'s work is so easily dividable that I can get the same speed-up just by using `xargs -P`:
```fish
# count number of files
fd .py | grep -v additional_tests | wc -l
     803
# process them in single thread
$ time fd .py | grep -v additional_tests | xargs flake8

________________________________________________________
Executed in   13.32 secs    fish           external
   usr time   13.09 secs    0.15 millis   13.09 secs
   sys time    0.29 secs    2.52 millis    0.29 secs

# divide them into 10 processes sending 81 paths to each
time fd .py | grep -v additional_tests | xargs -L 81 -P 10 flake8

________________________________________________________
Executed in    3.85 secs    fish           external
   usr time   15.12 secs    0.28 millis   15.12 secs
   sys time    1.54 secs    3.52 millis    1.54 secs

```

**Comment by asottile** [comment]
yeah I'm currently in the process of making the parts reusable enough that spawn would work and also devising a replacement plugin system that is not dependent on fork

**Comment by sigmavirus24** [comment]
Yeah, the problem with 3.x was keeping backwards compatibility with 2.x. The plugin system should mostly be thrown out as it works today and prefer the better/less fragile method that would work across all operating systems, not just *nixes
