### ISSUE TITLE
Enhancement Request: Flag improper use of string.find()

### ISSUE THREAD

**Issue by gsexton** [PyCQA/flake8#1339]
Title: Flag Improper Use of string.find()

Description
The string.find() method is easy to mis-use. A common error is:

```python
mystring='abc'
if mystring.find('def'):
  print("def is contained in {}".format(mystring)
```

The issue is that if string.find fails, it returns -1, which is "truthy". If string.find() locates the output at the beginning of the line, it returns 0 which is "false".

```python
mystring='abc'
if mystring.find('a'):
  print("a is in {}".format(mystring))
else:
  print('a is not in {}'.format(mystring))
```

It would be awesome of flake8 could flag any logical test involving string.find() that does not compare to a numerical value.

**Comment by asottile** [comment]
as the issue template states: flake8 does not implement any checks -- you can implement a plugin which does this though -- check out [the docs on building a plugin](https://flake8.pycqa.org/en/latest/plugin-development/)
