### ISSUE TITLE
STDIN "less than" sign redirection in Windows 10 command prompt produces no output

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [PyCQA/flake8#1346]
*Please describe how you installed Flake8*

pip install flake8

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.5",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    }
  ],
  "version": "3.9.2"
}
```

*Please describe the problem or feature*

STDIN "less than" sign redirection in Windows 10 command prompt produces no output:

flake8 - < file.py

Windows 10 version: 21H1 OS Build 19043.1023
Python Version: 3.9.5

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

The following commands works as expected:

type file.py | flake8 -

A simple test for python interpreter redirection works as expected:

python -c "import sys;print(*[x for x in sys.stdin])" < file.py

Since python interpreter works fine with redirection, there must be something in flake8 code that mishandles the argument "-"

The problem manifested itself in ALE plugin for Vim editor. Since ALE hardcodes the invocation of its linters there is no workaround.

**Comment by asottile** [comment]
cannot reproduce:

```console
C:\Users\asott\workspace>venv\Scripts\flake8.exe - < t.py
stdin:1:1: F401 'os' imported but unused

C:\Users\asott\workspace>venv\Scripts\flake8.exe --version
3.9.2 (mccabe: 0.6.1, pycodestyle: 2.7.0, pyflakes: 2.3.1) CPython 3.9.0 on Windows
```

**Comment by Konstantin-Glukhov** [comment]
This does not work with Python 3.9.5. It works with 3.9.4 and below.

**Comment by asottile** [comment]
still can't reproduce:

```
C:\Users\asott\workspace>venv\Scripts\flake8.exe --version
3.9.2 (mccabe: 0.6.1, pycodestyle: 2.7.0, pyflakes: 2.3.1) CPython 3.9.5 on Windows

C:\Users\asott\workspace>venv\Scripts\flake8.exe - < t.py
stdin:1:1: F401 'os' imported but unused
```

**Comment by Konstantin-Glukhov** [comment]
The problem is consistently reproduced on Windows 10 version: 21H1 OS Build 19043.1023 and Python Version: 3.9.5

**Comment by asottile** [comment]
please open an issue with cpython then if you suspect they have caused a regression -- https://bugs.python.org

**Comment by asottile** [comment]
(but even at that windows version I cannot reproduce)

**Comment by Konstantin-Glukhov** [comment]
I am not sure why you cannot reproduce. Maybe hardware differences?

From what I can see, platform.system() call moves stdin position to EOF for python > 3.9.4 on Windows 10. (The bug propagates from platform.py:win32_ver() function - a lot of changes there from version 3.9.4)

See if you can reproduce the following:

.pyenv\pyenv-win\versions\3.9.4\python.exe -c "import platform as p, sys as s;p.system();print(s.stdin.tell())" < test.py
0
.pyenv\pyenv-win\versions\3.9.5\python.exe -c "import platform as p, sys as s;p.system();print(s.stdin.tell())" < test.py
4000

flake8/utils.py:get_python_version() has platform.system() function call. As a result sys.stdin.buffer.read() always returns an empty list.
I understand it is not flake8 problem, but the fix is very easy: just add sys.stdin.seek(0) before sys.stdin.buffer.read(). I doubt that Python core team will address this problem quickly.

**Comment by asottile** [comment]
please open a bug with cpython
