### ISSUE TITLE
Inline comments in configuration files

### ISSUE THREAD

**Issue by adamsol** [PyCQA/flake8#1347]
The [documentation](https://flake8.pycqa.org/en/3.9.2/user/configuration.html#project-configuration) says that Flake8 does not support inline comments in configuration files. However, this actually seems to work without any problems, and IMHO it looks more readable than comments in separate lines:

```
[flake8]
ignore =
    E501,  # line too long
```

Should it be clarified in the documentation?

**Comment by asottile** [comment]
the docs are not wrong:

```console
$ flake8 
./t.py:1:1: F401 'os' imported but unused
$ babi setup.cfg
$ cat setup.cfg 
[flake8]
ignore =
    E501,  # what the F -- make shorter lines!
$ flake8 
```

**Comment by adamsol** [comment]
Oh, I see. So in this case adding the capital letter F in the "comment" suppresses error codes starting with F. I wouldn't call this a user-friendly configuration parsing, though :-)

**Comment by asottile** [comment]
and that's why the documentation says don't do it
