### ISSUE TITLE
FAQ states old versions in the "What is the next version of flake8?" section

### ISSUE THREAD

**Issue by fabianegli** [PyCQA/flake8#1357]
See https://flake8.pycqa.org/en/latest/faq.html#what-is-the-next-version-of-flake8

At the time of writing the published version of flake8 is 3.9, but the FAQ states it is 3.1.5 with the next release probably being 3.2.

I am not sure if this is a vlaluable FAQ at all. Reason being it gives a speculative answer which may be worse than no answer and on top of that it is wrong. I would scrap that Q completely from the FAQ without replacement. If anything link to the https://github.com/PyCQA/flake8/milestones website.

**Comment by asottile** [comment]
" **If** the last release on PyPI is 3.1.5 "

reading comprehension ;)

**Comment by fabianegli** [comment]
Sure. Sorry for the noise.
