### ISSUE TITLE
E123 makes the code more ugly

### ISSUE THREAD

**Issue by heckad** [PyCQA/flake8#1358]
```python
    project = ProjectBuilder() \
        .update_info(
            name=name, version=version
        ) \
        .set_storage(FakeStorage()) \
        .build()
```

Error got:
`E123 closing bracket does not match indentation of opening bracket's line`

Fix:
```
    project = ProjectBuilder() \
        .update_info(
        name=name, version=version
    ) \
        .set_storage(FakeStorage()) \
        .build()
```

Why does flake align brackets like that?

**Comment by asottile** [comment]
please read the issue template

**Comment by mxr** [comment]
FWIW you can format the code like so and it passes `flake8`:

```python
project = (
    ProjectBuilder()
    .update_info(name=name, version=version)
    .set_storage(FakeStorage())
    .build()
)
```

see [here](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADnAI1dAD2IimZxl1N_WmOQqqKVQcKikcDReWv4XqXT4tTAQ4ZyuZ-EehsBwZw2Bwf8WM3kU8JL0oKgY7nuiFhAPKZIiETBfyky672EmiJvbDttlot9mSExy6tCO8LU8_hufsWItkP70BFcnw_D-No-KQmJkMi7OHh45_uuc84XRycmGMOl5cyni300OZR0j50suAAAAABp6vRsH338SgABqQHoAQAAq74v0rHEZ_sCAAAAAARZWg==)
