### ISSUE TITLE
Incorrect error  when class name is used in argument to a class member

### ISSUE THREAD

**Issue by johann50** [PyCQA/flake8#1365]
For example,

class X :
    def __init__(self, x: int):
	self.x = x
	return
    def equal_to(self, other: X) -> bool:                                        
	return other.x == self.x

gives incorrect error:    F821 undefined name 'X'

**Comment by johann50** [comment]
My error.  Looks like python type hints ``doesnt` allow type to be used 
in this manner.

**Comment by asottile** [comment]
@johann50 please read the issue template next time
