### ISSUE TITLE
`per-file-ignores` not respected when overlapping files via globs

### ISSUE THREAD

**Issue by paw-lu** [PyCQA/flake8#1369]
*Please describe how you installed Flake8*

Example:

```sh
$ python -m pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```sh
% flake8 --bug-report
Usage: flake8 [OPTIONS] [PY_FILE]...
Try 'flake8 --help' for help.

Error: no such option: --bug-report
```

(what went wrong here?)

*Please describe the problem or feature*

If is specified twice in `per-file-ignores`—one explicitly one implicitly via globs (`*`), the ignored violation codes are not respected.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

With a project of the format:

```txt
.
├── dir
│  ├── bar.py
│  └── foo.py
└── .flake8
```

```py
"""foo.py"""
a = (1,2)
```

```py
"""bar.py"""
import os

a = (1,2)
```

```ini
# .flake8
[flake8]
per-file-ignores = 
    dir/*:E231
    dir/bar.py:F401
```

### What I expect

I expect `E231` to be ignored in both files, and `F401` to be ignored in `bar.py`.

### What happens

```sh
% flake8 dir/*
dir/bar.py:3:7: E231 missing whitespace after ','
```

Only `F401` is ignored in `bar.py`, but not not `E231`.

**Comment by asottile** [comment]
dupe #670

I'm also suspicious of your flake8 installation if `--bug-report` isn't working you've probably got a bigger problem with your installation

**Comment by paw-lu** [comment]
> dupe #670

Good catch. Sorry for missing that.

> I'm also suspicious of your flake8 installation if --bug-report isn't working you've probably got a bigger problem with your installation

Yeah I had some path confusion there and wasn't calling the right flake8 for that command. Thanks for the heads up!
