### ISSUE TITLE
Feature request for a new option: --max-errors=10

### ISSUE THREAD

**Issue by leon-matthews** [PyCQA/flake8#1371]
I'm an avid user of flake8. Thank you for providing such an excellent tool!

My workflow is to use a text editor and a terminal side-by-side. When I'm working on an old project I often run flake8 manually in the terminal, then open and edit files. So as to not get overwhelmed with screens of text, I often pipe it though ``head`` to print just the first few errors:

```bash
$ flake8 --config .flake8 | head
```

Usually flake8 runs so quickly I don't worry about all the error messages that I'm casually throwing away, but on the project I'm trying to update today there are hundreds of errors and files and it takes several seconds to run. 

It would be nice if there were an option to bail out early after a certain number of errors, so as to finish more quickly. I thought that ``--max-errors`` would work in nicely with the existing option names.

```bash
$ flake8 --config .flake8 --max-errors=10
```

Of course, it would only be worthwhile if using the argument caused the command to finish significantly faster than in the first example where output is simply discarded.  Would that be possible to do that with the way flake8 is built?

**Comment by asottile** [comment]
error collection and reporting are entirely separate steps so this isn't possible

**Comment by leon-matthews** [comment]
I feared that might have been the case... Thank you very much for the answer!
