### ISSUE TITLE
add color support for formatting

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1379]
~essentially replace `flake8-colors`

(needs a bit of design before implementation)

**Comment by and3rson** [comment]
:+1: Just following up on this so that I can update the flake8-colors readme to point to this functionality once it's implemented.

**Comment by Marsfan** [comment]
@asottile If you are going to work on this, please be aware of https://github.com/and3rson/flake8-colors/issues/12

**Comment by asottile** [comment]
@Marsfan check out the author of that issue

**Comment by Marsfan** [comment]
@asottile Oops. Lol
