### ISSUE TITLE
Question: How do we specify files in the .flake8 configuration file?

### ISSUE THREAD

**Issue by ecs-jnguyen** [PyCQA/flake8#1384]
Hi when I get the help prompt for flake8 I see this at the top:
```usage: flake8 [options] file file ...```

I would like to configure the `file file` part in the .flake8 configuration file so that I can run flake8 without any arguments. Currently I am running `flake8 src tests`, my desire is to put `src` and `tests` the configuration file so that I don't need to specify them at the command line.

I see that there is the `filename` option but that should be used for patterns.

**Comment by asottile** [comment]
there is not, though the default `flake8` with no arguments will recurse all files in the working directory (so it accomplishes the same as what you're requesting)
