### ISSUE TITLE
Spurious warning from internal plugin

### ISSUE THREAD

**Issue by kmurphy4** [PyCQA/flake8#1390]
*Please describe how you installed Flake8*

```sh
$ python3.6 -m venv /tmp/venv
$ source /tmp/venv/bin/activate
$ pip install flake8==3.9.2
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

<details>
<summary>

```sh
$ flake8 --bug-report
```

</summary>

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.9",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "example",
      "version": "0.1.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    }
  ],
  "version": "3.9.2"
}
```

</details>

*Please describe the problem or feature*

I'm trying to create a custom plugin for `flake8`.  This is working great overall, but I'm encountering one small logging bug.  Every time I run `flake8` after installing my plugin, I get this warning (from the internal `mccabe` plugin).
```
option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
```

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

Here's a minimal reproduction:

```python
# setup.py
import setuptools
setuptools.setup()
```

```cfg
# setup.cfg
[metadata]
name = example
version = 0.1.0

[options]
py_modules = example
install_requires =
  flake8

[options.entry_points]
flake8.extension =
  EXE101 = example:ExamplePlugin
```

```python
# example.py
import logging


# Set up a basic logger to write to stderr
logger = logging.getLogger()
handler = logging.StreamHandler()
logger.addHandler(handler)

# Log everything for WARNING + above
logger.setLevel(logging.WARNING)


class ExamplePlugin:
    name = "example"
    version = "0.1.0"

    def __init__(self, tree):
        pass

    def run(self):
        yield from []  # empty yield needs a `yield` keyword :)
```

(installed via `$ pip install -e .`)

Setting a breakpoint [here](https://github.com/PyCQA/flake8/blob/3.9.2/src/flake8/options/manager.py#L207) and typing `up` a couple times reveals that this is in fact being triggered by the `mccabe` checker:
```python
> /tmp/venv/lib/python3.6/site-packages/flake8/plugins/manager.py(402)generated_function()
-> return method(optmanager, *args, **kwargs)
(Pdb) ll
399  	        def generated_function(plugin):  # noqa: D105
400  	            method = getattr(plugin, method_name, None)
401  	            if method is not None and callable(method):
402  ->	                return method(optmanager, *args, **kwargs)
(Pdb) p plugin
Plugin(name="C90", entry_point="mccabe:McCabeChecker")
```

I can work around this warning for now by explicitly setting the logging configuration for that module, e.g.,
```python
logging.getLogger("flake8.options.manager").setLevel(logging.ERROR)
```
but that feels brittle and unreliable (plus it might suppress some warnings I _do_ want to see).

Let me know if there's any more details I can provide!

**Comment by asottile** [comment]
you're looking for [mccabe's issue tracker](https://github.com/pycqa/mccabe)  -- as noted in the issue template, flake8 does not implement any plugins of it sown

**Comment by kmurphy4** [comment]
Agh, sorry about that!
