### ISSUE TITLE
Type hints for plugins

### ISSUE THREAD

**Issue by kasium** [PyCQA/flake8#1392]
Hello,

I maintain a flake8 plugin where I add options by using the OptionManager. Of course, there are examples and also API documentation, however type hints would help a lot to find issues early. Since flake8 is python 3.6+ only, this should not be a huge issue. What do you think about making flake8 a typed project? 

As an alternative, type hints for the most important "public" API could be added to the typeshed repository.

Thanks a lot.

**Comment by asottile** [comment]
we use type hints internally but I'm not comfortable making them part of a public interface

typeshed is also not accepting new stubs

**Comment by kasium** [comment]
Out of curiously, where is the information that typeshed doesn't accept new stubs?

**Comment by asottile** [comment]
they just split out all of typeshed into tiny packages, they're not accepting new ones and instead recommending building your own tiny package
