### ISSUE TITLE
Stop using deprecated SelectableGroups interface

### ISSUE THREAD

**Issue by bmw** [PyCQA/flake8#1397]
In https://github.com/PyCQA/flake8/pull/1375, the deprecation warning from `importlib.metadata.SelectableGroups` was ignored in `pytest.ini`. Now that Python 3.10 is out, it'd be nice to stop ignoring this warning and switch to the new interface so that `flake8` doesn't cause DeprecationWarnings causing its users to also ignore this warning in their own tests.

**Comment by asottile** [comment]
we can't without unacceptable side-effects:
- reintroducing a backport
- dropping everything <3.10

**Comment by stephenfin** [comment]
Hey @asottile sorry for raising this from the dead but could you give me a reproducer for causing this warning? I can't figure out a reproducer, which means I can't work on resolving this and removing the cap.
