### ISSUE TITLE
Feature request: command line arg to show files run upon

### ISSUE THREAD

**Issue by jamesbraza** [PyCQA/flake8#1398]
*Please describe the problem or feature*

When debugging if `flake8` is running as intended, I use `flake8 --verbose`.  This contains some great information, but I am looking for more information: a printed list of the file(s) `flake8` is actually taking into account.

I have searched through the issues here, and didn't see anything requesting this specific feature.

I think this would be a useful feature to include as part of `--verbose`, or add as a command line arg like `--show-files`.

What do you think?  I find it hard to believe this is the first time a request like this has been brought up.

**Comment by asottile** [comment]
try more `--verbose` (it's additive)!

**Comment by sigmavirus24** [comment]
You can also write your own reporter. It would be able to print every file name I believe

**Comment by jvanasco** [comment]
FYI, `--verbose` does not cleanly do this.

`--versbose` / `-v` will log to `INFO` - "Checking {n} files"
`-vv` will log to `DEBUG` either one of:
* "{filepath} has not been excluded", or
* "{filepath} has been excluded"

This requires quite a bit of post-processing to determine.

IMHO, the ability to cleanly and clearly show the files should be provided in first-party support for flake8 or an official plugin.

As the Python ecosystem continually evolves, new directories -- often hidden -- start to appear in projects to handle various uses (such as caches, vendoring, etc).  flake8 picks these up without users knowing, which often leads to long processing times.  I typically only find these when I see a spike in CI systems across historical runs and look to investigate.

debugging this type of stuff takes a lot more work than it should.

**Comment by asottile** [comment]
@jvanasco perhaps try the suggestion directly above your comment?

this won't be part of core -- the output is intentionally not stable in any way and this is not a core functionality but a debugging one at best
