### ISSUE TITLE
`ignore` option default behaviour is unexpected

### ISSUE THREAD

**Issue by jamesquilty** [PyCQA/flake8#1402]
I've been an on-again off-again user of flake8 and a couple of weeks ago I encountered a _hard to track down_ problem when returning after a long break: the presence of an `ignore` line in `~/.config/flake8` has the pernicious side-effect of silently _including_ and _enabling_ rules.

#### Desired Behaviour

In the presence of, for example, `ignore = D203` the rule `D203` is ignored and no other behaviour changes occur. 

#### Actual Behaviour

The presence of `ignore = D203` causes rule `D203` to be ignored _and also_ enables rules `E24`, `E226`, `W504`, `E121`, `E126`, `E704`, `W503` and `E123` which leads to flake8 generating rule violation messages which are not generated when `ignore` is omitted.

The cause of this problem is that `ignore` overrides the default `ignore` configuration which has grown to include several rules.  Overriding is a destructive operation, which are not usually coded as default behaviours, and easily leads to flake8 appearing to be _given to unaccountable changes in behaviour_ and _changing according to no discernible rules_.

From this perspective, the preferred fix for this bug is to make `ignore` non-destructive (like `ignore-extend`) and add an option (e.g. `ignore-override`) which must be explicitly invoked to obtain the  destructive override behaviour.

I installed with `pip install flake8`, the output of `flake8 --bug-report` is:

```shell
$ flake8 --bug-report
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.3",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    }
  ],
  "version": "3.9.2"
}
```

**Comment by jamesquilty** [comment]
I realise that the override behaviour of `ignore` is mentioned in the documentation, and wanted to point out the limitations of documentation as work-arounds for "idiosyncratic" behaviour: the entry for the [`--ignore`](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-ignore) option does not mention that it overrides the defaults; the entire [Configuring Flake8](https://flake8.pycqa.org/en/latest/user/configuration.html) does not mention the overriding behaviour of `ignore` _at all_ and, indeed, applying the examples given on that page will have the pernicious side-effect of silently _including_ and _enabling_ rules; the [Aggregating Configuration File and Command Line Arguments](https://flake8.pycqa.org/en/latest/internal/option_handling.html#aggregating-configuration-file-and-command-line-arguments) section of the Option Handling page explicitly states that options and configurations are _merged_ and doesn't mention the overriding behaviour. The only places where the overriding behaviour of `ignore` appears to be mentioned is in the description of the [`--extend-igore`](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-extend-ignore) option and the not-linked-to-the-full-options-page [Selecting and Ignoring Violations](https://flake8.pycqa.org/en/latest/user/violations.html). A lot of the latter page is devoted to explaining the idiosyncratic behaviour of `ignore`, and my first thought was that fixing the behaviour would be better than trying to explain it.

**Comment by asottile** [comment]
you generally want `--extend-ignore` and not `--ignore`

**Comment by jamesquilty** [comment]
I generally want software that is not _given to unaccountable changes in behaviour_ and which does not _change according to any discernible rules_. Thanks for your time.
