### ISSUE TITLE
Option to pass input filenames through a file or the standard input

### ISSUE THREAD

**Issue by piotr-dobrogost** [PyCQA/flake8#1429]
It would be useful to have an option to pass input filenames through a file or the standard input to avoid problem of exceeding maximum command line size when passing filenames as arguments.
The standard way of solving this problem by using `xargs` is not possible when one also uses `--output-file` option.

**Comment by asottile** [comment]
use xargs, it is designed for this -- no need for every tool to reinvent the wheel

**Comment by piotr-dobrogost** [comment]
Thank you. I forgot that this specific output file can be written incrementally as opposed to some xml output file.
