### ISSUE TITLE
Add .nox to the default exclude list

### ISSUE THREAD

**Issue by Spectre5** [PyCQA/flake8#1442]
*Please describe the problem or feature*

Would flake8 consider a PR to add ".nox" to the default exclude list?  Nox is similar to and inspired by tox, but uses a Python file to create and manage the sessions.

https://nox.thea.codes/en/stable/index.html

**Comment by sigmavirus24** [comment]
I'm on board with that

**Comment by asottile** [comment]
here's where to add it: https://github.com/PyCQA/flake8/blob/e34647fb37a78f87a815f239697222f00785c94d/src/flake8/defaults.py#L4
