### ISSUE TITLE
Unpaired Bidi Control Character Detection

### ISSUE THREAD

**Issue by GBeauregard** [PyCQA/flake8#1444]
Unpaired bidi control characters can lead to security problems in python source code, as demonstrated at https://trojansource.codes/

Although some languages (rust) and compilers (clang, gcc) are being modified to reject unpaired bidi characters, the python security team rejected this and the discussion is that this should be implemented in python linters instead: https://mail.python.org/archives/list/python-dev@python.org/thread/6DBJJRQHA2SP5Q27MOMDSTCOXMW7ITNR/

Can flake8 implement a new feature to detect unpaired bidi control characters?

**Comment by asottile** [comment]
please do not ignore the issue template:

> NOTE: flake8 is a linting framework and does not implement any checks

**Comment by GBeauregard** [comment]
> please do not ignore the issue template:
> 
> > NOTE: flake8 is a linting framework and does not implement any checks

:+1:  I'll move to pyflakes

**Comment by asottile** [comment]
> 
> 
> > please do not ignore the issue template:
> > > NOTE: flake8 is a linting framework and does not implement any checks
> 
> 👍 I'll move to pyflakes

you probably want `pycodestyle` -- pyflakes doesn't have access to that information
