### ISSUE TITLE
What does the last element of the tuple do?

### ISSUE THREAD

**Issue by decorator-factory** [PyCQA/flake8#1475]
I'm making my own plugin, and I have an unanswered question:

My plugin object's `__iter__`, as I understand, should return an iterator of 4-element tuples. What is the last element for? It seems like it is just ignored by flake8. My test plugin also works whatever I supply.
[Here](https://github.com/PyCQA/flake8/blob/main/src/flake8/checker.py#L445-L451) 
```py
            for (line_number, offset, text, _) in runner:
                self.report(
                    error_code=None,
                    line_number=line_number,
                    column=offset,
                    text=text,
                )
```

I've seen that other plugins pass `type(self)` as the last element. Is this somehow important?

**Comment by asottile** [comment]
it's unfortunately left over from a previous implementation and does nothing currently

it will likely it be removed when a v2 interface is implemented
