### ISSUE TITLE
comment is misleading in `_write`

### ISSUE THREAD

**Issue by jrobbins-LiveData** [PyCQA/flake8#1478]
re this comment: https://github.com/PyCQA/flake8/blob/7a02d04919a2209bc2612373d46d2edfa4d59773/src/flake8/formatting/base.py#L190

When the [change](https://github.com/PyCQA/flake8/commit/7a353d2e23ed336cea41a05a03732a35e45801c2) was made to `_write`, the comment should have been changed, since the method no longer uses `print()`, but, rather, now uses `sys.stdout.buffer.write`.

(Breaking [an illicit use](https://github.com/tholo/pytest-flake8/issues/81) by `pytest-flake8`  of this method, breaking my efforts to use the `tox` setup in [keyring](https://github.com/jaraco/keyring))

The comment is misleading because `print()` works for me, on Windows, for the `tox` test I am trying to run, but `sys.stdout.buffer.write` crashes, because `sys.stdout` doesn't (always) have a `.buffer` attribute.  

While I certainly hope that [pytest-flake8](https://github.com/tholo/pytest-flake8) fixes whatever illicit or erroneous call it is making to  `flake8`, in any event, the `flake8` code base should try to keep its comments in sync with its changes, to facilitate code review.

**Comment by asottile** [comment]
there's pinned issues and a search box
