### ISSUE TITLE
Flake8 ignores locations ~/.flake8 and ~/.config/flake8 for its configuration

### ISSUE THREAD

**Issue by 515k4** [PyCQA/flake8#1479]
I have very simple config file with `max-line-length = 88` and by running `flake8 example.py`, I got errors about line length but with `flake8 --config ~/.config/flake8 example.py` or `flake8 --config ~/.flake8 example.py` everything works fine. Example:

```
$ cat ~/.flake8 
[flake8]
max-line-length = 88
$ cd subdir
$ cat example.py 
print("This is very long line. This is very long line.This is very long line. End")
$ flake8 example.py 
example.py:1:80: E501 line too long (83 > 79 characters)
$ flake8 --config ~/.flake8 example.py
<no output>
```

I've installed flake8 using `pip install --user flake8`.  This is detailed version:
```
$ flake8 --bug-report
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.0",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}
```

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Comment by 515k4** [comment]
> In the future, please search **closed and** open issues before creating new ones that are duplicates.

Well, my bad. But this whole issue takes me at least one hour of investigation what's went bad in my toolstack. Is it possible to add a warning for other users when flake8 detects `~/.flake8` or `~/.config/flake8` that those files are deliberately ignored in 4.0? The warning could be printed in verbose mode, but something is better then nothing (or that one line in 4.0.0 changelog)

**Comment by 515k4** [comment]
Or at least add something like _Please take into account that ~/.flake8 or ~/.config/flake8 are no longer supported._ to https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations

**Comment by asottile** [comment]
it doesn't even discover those files to ignore them so a warning would not be possible
