### ISSUE TITLE
[doc][good first issue?] Mention the versioning scheme on the release notes page

### ISSUE THREAD

**Issue by webknjaz** [PyCQA/flake8#1492]
There was a case where I wanted to see how flake8 should be pinned in the deps because one project assumed SemVer and I wanted to verify this.

I expected that this information would be at least hinted above https://flake8.pycqa.org/en/latest/release-notes/ because this is the document supposedly targeting the consumers wanting to upgrade.

Having not found it there, I tried to search via RTD and this didn't work: https://flake8.pycqa.org/en/latest/search.html?q=semver&check_keywords=yes&area=default.
But what worked was using extended wording: https://flake8.pycqa.org/en/latest/search.html?q=semantic+versioning&check_keywords=yes&area=default#.

Apparently, it's documented in the *internal* section that is not targeted at average users: https://flake8.pycqa.org/en/latest/internal/releases.html?highlight=semantic%20versioning#releasing-flake8.

Possible action items:
* [ ] Add `semver` keyword somewhere in the documents, so it's googlable
* [ ] Add a note (maybe even reuse via `.. include::`) at the top of the release notes document setting the expectations for the consumers

**Comment by asottile** [comment]
I don't think it needs to be stated, the version does not look like a calendar so it can be assumed to be semver
