### ISSUE TITLE
feature to ignore any error from commented lines

### ISSUE THREAD

**Issue by DeboBurro** [PyCQA/flake8#1500]
*Please describe how you installed Flake8*
```
python3 -m pip install flake8
```

**Note**: Some *nix distributions patch Flake8 arbitrarily to accommodate incompatible software versions. If you're on one of those distributions, your issue may be closed and you will be asked to open an issue with your distribution package maintainers instead.

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.9",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    }
  ],
  "version": "3.9.2"
}

```

Currently, if a commented line breaks any rule without giving it a `# noqa`, it will report an error. 
```
burro@burro:~/test/abc$ cat abc.py 
# just long comment dasdasdsaddfdsgdfsgdsfhdghdfsgdfgdfgdfgdfgdfgdfgdfgdfgdfgdfgdfdsfgdf
def main():
    return 2
```
What happened now is
```
burro@burro:~/test/abc$ flake8 --max-line-length 80  abc.py 
abc.py:1:81: E501 line too long (88 > 80 characters)
```
What I am expecting is
```
burro@burro:~/test/abc$ flake8 --max-line-length 80 --ignore-all-error-from-comment  abc.py 
burro@burro:~/test/abc$ 
```
Can we ignore any error from commented lines without explicitly using `# noqa`?
I am expecting that there is an option like  `--ignore-all-error-from-comment` so we can use ` flake8 --max-line-length 80 --ignore-all-error-from-comment  abc.py ` without any error return from any commented lines.

**Comment by asottile** [comment]
from the issue template:

> NOTE: flake8 is a linting framework and does not implement any checks

**Comment by sigmavirus24** [comment]
Also, no, we won't add flags to blanket ignore all errors from specific lines.
