### ISSUE TITLE
Support for pyproject.toml 

### ISSUE THREAD

**Issue by eddiebergman** [PyCQA/flake8#1501]
Hello,

I realise that supporting `pyproject.toml` is not happening in the short term as indicated by the relevant [closed issues and PR's](https://github.com/PyCQA/flake8/issues?q=pyproject.toml) and the [main issue thread #234](https://github.com/PyCQA/flake8/issues/234) for which links have staled and it is not possible to contribute or indicate any desire for this feature. Understandably legacy config options and config parsing are quite difficult to change at this point and this feature is likely not going to see the light of day anytime soon.

There is however little means to communicate want for this feature without being closed and linked to the locked issue thread. 

Could at least one pinned issue be left open where a simple explanation for not implementing it is described and request for this feature could be communicated by a simple thumbs up. It would prevent future issues such as this one from popping up.

**Comment by asottile** [comment]
duplicate #234
