### ISSUE TITLE
Improve explanation of how to ignore per file if the file name contains spaces

### ISSUE THREAD

**Issue by 1kastner** [PyCQA/flake8#1519]
*Please describe the problem or feature*
I have a file called `01 Einfuehrung in Python.ipynb` and I would like to ignore specific issues here. In the file, I harm some design principles purposefully and show the user how this creates an issue lateron. However, my per-file-ignores are not considered. I am not sure how exactly the glob pattern is working. There are a few examples, e.g. at https://flake8.pycqa.org/en/latest/user/options.html?highlight=glob%20#cmdoption-flake8-filename but they are not exhausting enough for me.

Extract of my config:
```
per-file-ignores =
    "01 Einfuehrung in Python.ipynb": F403, F405, E116, E731
```
With or without hyphens around the file name, in both cases the extract of the console output looks like this:
```
01-einfuehrung-in-toolbox\01 einfuehrung in python.ipynb#In[14]:1:19: E226 missing whitespace around arithmetic operator
01-einfuehrung-in-toolbox\01 einfuehrung in python.ipynb#In[14]:3:1: E731 do not assign a lambda expression, use a def
01-einfuehrung-in-toolbox\01 einfuehrung in python.ipynb#In[23]:2:23: E226 missing whitespace around arithmetic operator
01-einfuehrung-in-toolbox\01 einfuehrung in python.ipynb#In[23]:4:1: F403 'from math import *' used; unable to detect undefined names
01-einfuehrung-in-toolbox\01 einfuehrung in python.ipynb#In[23]:8:7: F405 'sin' may be undefined, or defined from star imports: math
01-einfuehrung-in-toolbox\01 einfuehrung in python.ipynb#In[23]:8:11: F405 'pi' may be undefined, or defined from star imports: math
01-einfuehrung-in-toolbox\01 einfuehrung in python.ipynb#In[23]:8:13: E226 missing whitespace around arithmetic operator
```

So I would wish to be able how exactly the glob patterns work but in the documentation I could not find sufficient information how to deal with spaces in file names. Thanks a lot for your assistance!

**Comment by MarcoGorelli** [comment]
Looks like you're using [flake8-nb](https://github.com/s-weigand/flake8-nb)? If so, the bug report should probably go there

**Comment by asottile** [comment]
don't skip the issue template, it's there for a reason

**Comment by 1kastner** [comment]
> Looks like you're using [flake8-nb](https://github.com/s-weigand/flake8-nb)? If so, the bug report should probably go there

It is not a bug, it is a request for clarification. Unless you tell me that I was doing everything in a correct manner and it should have worked.

**Comment by MarcoGorelli** [comment]
Either way, the request for clarification should go to flake8-nb
