### ISSUE TITLE
File based comments

### ISSUE THREAD

**Issue by busterbeam** [PyCQA/flake8#1521]
Please read carefully

I am requesting this from the point that I like to use tabs and do on all my code, but I also would love to have guidance and support for all other PEP8 things.  Quoting [PEP8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces)

_Spaces are the preferred indentation method._
_Tabs should be used solely to remain consistent with code that is already indented with tabs._

**preferred**... not by the interpreter, most likely by the developers who wrote python.  And PEP8 allows code written initially with tabs to continue with tabs, If I start my own new files... I'm always starting with tabs.

So can you please add a comment feature to apply a PEP8 fix across an entire file?  Its not even a fix.  flake8 should not throw an error on a script written completely with tabs as PEP8 doesn't say to do so.  I'm also of the opinion that spaces have a place in doc strings so any indentation within the the docstring block can use spaces, for example coders wanting to make ascii art.

**Comment by asottile** [comment]
please read the issue template
