### ISSUE TITLE
Allow newer versions of importlib-metadata

### ISSUE THREAD

**Issue by kasium** [PyCQA/flake8#1522]
flake8 currently pins `importlib-metadata<4.3;python_version<"3.8"`, but e.g. sphinx needs a newer version `importlib-metadata>=4.4; python_version < '3.10'`. Can we allow flake8 to consume newer versions?

**Comment by MarcoGorelli** [comment]
Hey - from https://github.com/PyCQA/flake8/pull/1438 this seems unlikely, I'd suggest closing this to reduce the load on the maintainers

**Comment by kasium** [comment]
Okay, I read thru the thread, but how should this now move on? Should I ask sphinx to relax their pin?

**Comment by MarcoGorelli** [comment]
One suggestion could be to run `flake8` via `pre-commit`, so it runs in its own virtual environment and there's no dependency clash

> Should I ask sphinx to relax their pin?

Could do, but check if it's been asked already first

**Comment by sigmavirus24** [comment]
If you can, use something that isolates your different tools for you. There are lots of things that do this:

- pipx
- nox
- rox
- virtualenv
- pre-commit
- and plenty more I probably don't know about or have forgotten
