### ISSUE TITLE
error in anyjson setup command: use_2to3 is invalid.

### ISSUE THREAD

**Issue by justinTM** [PyCQA/flake8#1525]
### how did you install flake8?

```console
$ poetry add flake8
$ poetry add flake8@3.8.3
$ poetry add flake8@3.5.0
$ poetry add setuptools@57

none of these fixed it.

flake8 relies on anyjson. anyjson relies on use_2to3.

since anyjson repo literally does not exist anymore, i'm posting here mostly out of desperation.
```

### unmodified output of `flake8 --bug-report`

```json
cannot get to this step yet.
```

#### what I expected to happen

...

#### sample code

```python
print('hello world!')
```

#### commands ran

```console
$ flake8 t.py
...
```

**Comment by asottile** [comment]
flake8 doesn't depend on anyjson and as far as I can tell never has:

```console
$ git log -G anyjson
$
```

also you did not fill out the issue template

**Comment by justinTM** [comment]
yeah i think i'm just unfamiliar with poetry (vs pip) but the problem was elsewhere. there's a command `poetry show --tree` which will show which package relies on what, and for some reason this error was only showing up when adding to (known good) dockerfiles the flake8 package using poetry. turns out the problem was with an old version of celery needing anyjson; upgraded everything to latest python (no more python2.7) which fixed it. 

originally i tried my best to abide by the issue template. upon re-reading i definitely did it wrong. 

thank you
