### ISSUE TITLE
Check argparse created members 

### ISSUE THREAD

**Issue by tdegeus** [PyCQA/flake8#1530]
### describe the request

I made a mistake in my code:
```python
import argparse 

parser = argparse.ArgumentParser()
parser.add_argument("-f", "--foo", type=str, help="Output file")
check = os.path.isfile(args.bar)
```
i.e. I forgot to change `args.bar` to `args.foo`. 

It would be great (but probably hard) if *flake8* could check for `argparse` members created by the parser.

**Comment by sigmavirus24** [comment]
Flake8 does not itself implement any checks. This is best done in a plugin.
