### ISSUE TITLE
Comments in configuration file break configuration file usage

### ISSUE THREAD

**Issue by BilgeRatPDX** [PyCQA/flake8#1532]
### how did you install flake8?

```console
C:\Windows\System32>pip install flake8
Collecting flake8
  Downloading flake8-4.0.1-py2.py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 933 kB/s
Requirement already satisfied: pyflakes<2.5.0,>=2.4.0 in c:\users\tcalderwood\appdata\roaming\python\python38\site-packages (from flake8) (2.4.0)
Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in c:\users\tcalderwood\appdata\roaming\python\python38\site-packages (from flake8) (2.8.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in c:\users\tcalderwood\appdata\roaming\python\python38\site-packages (from flake8) (0.6.1)
Installing collected packages: flake8
Successfully installed flake8-4.0.1
```

### unmodified output of `flake8 --bug-report`

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.5",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "alphabetize",
      "version": "0.0.17"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "1.8.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.6.0, pydocstyle: 6.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "1.2.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-print",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-pytest",
      "version": "1.3"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_pep3101",
      "version": "1.2.1"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.11.1"
    },
    {
      "is_local": false,
      "plugin": "nitpick",
      "version": "0.27.0"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    },
    {
      "is_local": false,
      "plugin": "use-fstring-format",
      "version": "1.3"
    },
    {
      "is_local": false,
      "plugin": "use-fstring-percent",
      "version": "1.3"
    },
    {
      "is_local": false,
      "plugin": "use-fstring-prefix",
      "version": "1.3"
    }
  ],
  "version": "4.0.1"
}
```

#### what I expected to happen

Per the documentation and examples, the configuration file should be able to support

```
[flake8]
# B011 - Do not call assert False since python -O removes these calls. Instead callers should raise AssertionError()
# C901 - Function is too complex
ignore=B011,C901

```

#### What Happens

Flake8 ignores the configuration files, reports no errors, and uses default settings. Had to use the -v option to figure out why the configuration file was being ignored. 

#### commands ran

Flake8 -config=flake8.txt -v

#### Error In Log File
flake8.options.config     MainProcess    703 ERROR    There was an error decoding a config file.The file with a problem was flake8.
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\flake8\options\config.py", line 66, in _read_config
    found_files.extend(config.read(filename))
  File "c:\program files\python38\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "c:\program files\python38\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "c:\program files\python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 660: character maps to <undefined>

[flake8.txt](https://github.com/PyCQA/flake8/files/7907712/flake8.txt)

**Comment by asottile** [comment]
the issue appears to be the `“` (curly quote) in your configuration file being incompatible with your platform-default encoding

**Comment by BilgeRatPDX** [comment]
Turns out the issue was the encoding for two of comments were not ANSI and thus could not be converted. See RST303 and RST304. Because of this silent failure, we were not checking our code with Flake8 for a few weeks and spent a some time tracking down the issue. How do we put in feature request to put in a non-silent failure on encoding issues?

**Comment by asottile** [comment]
it should already behave that way on the `main` branch due to some breaking changes that will be released in 5.x -- though I am going to additionally force it to use UTF-8

**Comment by asottile** [comment]
thanks for the issue!

**Comment by BilgeRatPDX** [comment]
So in the new version, if there is a problem with the configuration file, the user will be notified instead of silently failing? 
    On Thursday, January 20, 2022, 11:03:17 AM PST, Anthony Sottile ***@***.***> wrote:  
 
 


it should already behave that way on the main branch due to some breaking changes that will be released in 5.x -- though I am going to additionally force it to use UTF-8

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
