### ISSUE TITLE
I would like to be able to disable all the formatting rules all at once

### ISSUE THREAD

**Issue by matthewdeanmartin** [PyCQA/flake8#1546]
### describe the request

Right now, if you use any code formatter tool (say, black or isort), generally you don't want the formatter and the linter to argue with each other. In otherwords, why should flake8 force users to only do reformatting by hand instead of using autoreformatters? (Rhetorical question, I will continue to use code reformatters and I wish the people who prefer to manually format their code all the best) 

I find myself disabling all of the formatting rules one by one as they turn up. 

I [can see that making flake8 compatible with black has already been suggested and closed](https://github.com/PyCQA/flake8/issues/1096). That would be a preferrable solution, but since I'm not in a position to make a PR, I guess I'll abide by that decision.

It would be useful if there was a way to disable all the formatting rules in one go. Is this already possible, or could this be a feature, thanks.

**Comment by asottile** [comment]
flake8 does not implement any checks and does not do any formatting

you probably want to consult [black's guide for tool compatibility](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html)

**Comment by matthewdeanmartin** [comment]
I think I see what you mean, I have to configure "pycodestyle, pyflakes, mccabe, and third-party plugins" each directly to disable the formatting warnings.

`max-line-length = 88` and `extend-ignore = E203` can't possibly be an exhaustive list of the incompatibilities between black an "pycodestyle, pyflakes, mccabe, and third-party plugins". In the future I won't call this flake8, but instead "pycodestyle, pyflakes, mccabe, and third-party plugins"
