### ISSUE TITLE
Using flake8 inside python

### ISSUE THREAD

**Issue by germa89** [PyCQA/flake8#1547]
### Request Description

Hi there,

I believe it will be very useful to be able to format strings from inside python. Meaning, using flake8 as module.

### Example code
```python
>>> import flake8

>>> unformatted_string = """def function():
"""this is wrong identation"""
return
"""
>>> formatted_string = flake8.format_string(unformatted_string)
>>> print(formatted_string)
def function():
    """this is wrong identation"""
    return
```

#### Disclaimer
I did try to find something similar inside flake8, but it seems everything is focused toward CLI. I might be missing something though.

**Comment by asottile** [comment]
flake8 is a linter, not a code formatter -- perhaps you're looking for something like autopep8 / black / yapf
