### ISSUE TITLE
Reproducible order of default arguments in --help output

### ISSUE THREAD

**Issue by echoix** [PyCQA/flake8#1550]
### describe the request

Currently, at each invocation of `flake8 --help`, the order of the arguments of the `--ignore` parameter always come out in a different order. Try calling it 3 times in a row to see (I'm using docker+alpine, or wsl2 ubuntu 20). It seems the only list-like option to have this handling.

I tried to look in the code, and at the time of invoking `add_option()` in `/src/flake8/main/options.py`, the value of the keyword argument `default` is indeed a string and is correctly ordered, so using `default=",".join(sorted(defaults.IGNORE)),` doesn't change the random output.
https://github.com/PyCQA/flake8/blob/ddae449ceceb83bab3a273cad9554016cfacc41e/src/flake8/main/options.py#L232-L240
Further on, I understand that the `comma_separated_list=True` leads to an call of `parse_comma_separated_list()` in `/src/flake8/utils.py`
https://github.com/PyCQA/flake8/blob/ddae449ceceb83bab3a273cad9554016cfacc41e/src/flake8/utils.py#L31-L48
However, I can't seem to find a reason why the order of the string split into a list would change only for the `default` argument, since the regex seems to really split by comma, and a list comprehension using a `for` should really respect the order.

What the impact is: when tools or doc generators keep the output of the help in its files, it leads to always having two lines of diff of the ignored checks in a different order, but always the same set. More specifically, in a project like Megalinter, each build will have changes for flake8, even when no changes are made to flake8. Take a look at any PR with a name starting with "[automation] Auto-update linters version, help and documentation" in https://github.com/megalinter/megalinter/pulls?q=is%3Apr+is%3Aclosed
Thanks for your time!

**Comment by asottile** [comment]
you can probably set `PYTHONHASHSEED=0` as it looks like a set is getting involved in an intermediate somewhere

**Comment by asottile** [comment]
in the future please follow the bug report template -- this is not a feature request and you're missing useful debugging information that the other template requires you to fill out

**Comment by echoix** [comment]
Sorry for the poor choice of template, I started writing in a feature request, like "could it be reproducible for...", but the final issue indeed was written more like a bug request.

**Comment by asottile** [comment]
oops, didn't mean to click close -- this might be fixable but then it wouldn't reflect the values coming from the configuration -- and it might be fixable just for ignore but not for everything

**Comment by echoix** [comment]
> but then it wouldn't reflect the values coming from the configuration

For now it only for `--ignore` that it doesn't represent the tuple order from the defaults file, so it already doesn't respect the configuration when it is blank/not set up already.
https://github.com/PyCQA/flake8/blob/62ce3e491860aa34cfd3438715ade74a8a45bfac/src/flake8/defaults.py#L16

If some default values are used (assumed), it is important for me (or users) to see what is used by default before changing options on our side.
