### ISSUE TITLE
Bug when combining --select and --extend-ignore

### ISSUE THREAD

**Issue by thomie** [PyCQA/flake8#1553]
### how did you install flake8?

```console
$ pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
flake8 --bug-report                           
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.10",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}
```

#### what I expected to happen
When combining `--select=E` with `--extend-ignore=Exxx`, and `Exxx` is on the default ignore list, then I expect `Exxx` to be ignored, because `Exxx` is [more specific](https://flake8.pycqa.org/en/latest/user/violations.html#selecting-and-ignoring-simultaneously-for-fun-and-profit) than `E`.

#### sample code

```python
1+1
```

#### commands ran

This demonstrates the bug:
```console
$ flake8 --select=E --extend-ignore=E226 test.py
test.py:1:2: E226 missing whitespace around arithmetic operator
```

When adding `--ignore=`, the error does get ignored (as it should):
```console
$ flake8 --select=E --ignore= --extend-ignore=E226 test.py
<no output>
```

**Comment by asottile** [comment]
unfortunately the way it works is if the default ignore list is identical to the default then it is treated as "implicit" whereas the `--select=E` is "explicit"

fortunately, you don't need `--select=E` as it is always enabled
