### ISSUE TITLE
Help text for `--count` option incorrectly specifies that the count is output to stderr

### ISSUE THREAD

**Issue by tmarice** [PyCQA/flake8#1554]
### how did you install flake8?

```console
$ pip install flake8==4.0.1
```

### unmodified output of `flake8 --bug-report`

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.7",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}
```

### describe the problem

When running `flake8 --help`, the `--count` options is described as:
```
  --count               Print total number of errors and warnings to standard error and set the exit code to 1 if total is not empty.
```

The count is printed to `stdout`, not `stderr`, according to the [documentation](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-count), this [issue](https://github.com/PyCQA/flake8/issues/455), and my own experience.

**Comment by sigmavirus24** [comment]
Would you like to send a PR to update the `help` text? It should be a trivial change.

**Comment by tmarice** [comment]
👍🏻 I'll send a PR within the next couple of days.
