### ISSUE TITLE
Changelog for dependabot?

### ISSUE THREAD

**Issue by philippefutureboy** [PyCQA/flake8#1566]
### describe the request

Hey there, wonderful flake8 team :)

This is an entirely optional request, but would be nice to have;
Currently dependabot cannot detect your release notes automatically since your release notes format is not supported by it.
Would it be possible for you to start using a form of release notes supported by dependabot, like a CHANGELOG.md?

Thank you! 🙏

**Comment by asottile** [comment]
sorry, but no thanks -- if you want the changelog you can view it on our site
