### ISSUE TITLE
Support hyphens in error codes

### ISSUE THREAD

**Issue by jarshwah** [PyCQA/flake8#1568]
### describe the request

I'd like to be able to use hyphens in error codes so that I can have readable error codes that are name-spaced. For example, here's a list of some error codes we're currently using:

COMPANY-UNIT-TESTS-FILEPATH
COMPANY-FUNCTIONAL-TESTS-FILEPATH
COMPANY-PRINT-STATEMENTS
COMPANY-MOCK-ASSERT-METHODS

These codes work fine with `noqa` directives. The only place they don't seem to work is in flake8 configuration files (such as setup.cfg). That is, the following config file crashes flake8:

```
[flake8]
per-file-ignores =
    tests/test_flake8_plugin.py:COMPANY-UNIT-TESTS-FILEPATH
```

With the error:

```
There was a critical error during execution of Flake8:
Expected `per-file-ignores` to be a mapping from file exclude patterns to ignore codes.

Configured `per-file-ignores` setting:

    tests/test_flake8_plugin.py:COMPANY-UNIT-TESTS-FILEPATH
```

I believe it comes down to this line: https://github.com/PyCQA/flake8/blob/94ed800b2a256dd4feb7e3d680b9c273448f6885/src/flake8/utils.py#L59

The fix could be a simple update of the regex. I will put a patch together shortly to demonstrate a potential fix.

**Comment by jarshwah** [comment]
It sounds like this feature request is rejected, so rather than continue the discussion on the PR I thought I'd try to plead my case here. I'd like to understand the reasons for rejecting this, and wanted to dig in a little deeper to the reasons I think it's a good idea. 

I don't think HYPHENATED-CODES should replace SRT123 codes but there's room for both to exist.

(I also understand that there's no obligation for the maintainers to continue this conversation, and if that's the case, so be it, no worries).

Firstly, the rest of flake8 and the ecosystem of plugins already works without incident with HYPHENATED-CODES. There is code out there in the wild producing error codes that don't match the form SRT123. I could only find the config parser with the original constraints (and a [pycodestyle](https://github.com/PyCQA/pycodestyle/blob/6678922f8d4fb6a34fb77f4f5a7992ade45aaf2f/pycodestyle.py#L129) regex that enforces A123 type codes).

Second, ignoring rules using short-codes impairs readability, as you usually have to go search for what a code means or add comments into the config file to understand what they're used for. Eg 
![image](https://user-images.githubusercontent.com/541083/158481459-e2c97a2f-159e-474f-ab87-6c83e6be813f.png)

Similarly, adding NOQA lines with HYPHENATED-CODES can read a bit nicer:

`print(summary)  # noqa: NS-PRINT-STATEMENTS`

Coming up with unique SHR123 codes can also be a bit of a hassle. You need to make sure you're not clashing with existing prefixes that other plugins have defined. Then you need some kind of numbering scheme so that similar rules are within the same range.

Finally, supporting arbitrary length codes with hyphens doesn't seem to cause any issues either.

I hope you can reconsider, thanks

**Comment by asottile** [comment]
this isn't the first time this has come up. I encourage you to search the tracker and find the duplicates where this has been decided

**Comment by jarshwah** [comment]
Thanks for the pointer (I did a cursory search prior but searching for code and regex wasn't the easiest search I've ever had to perform).

https://github.com/PyCQA/flake8/issues/325 seems to be one of the most relevant issues. It seems to boil down to being able to differentiate between codes and files, and playing nice with other tooling. Fair enough, cheers!

**Comment by asottile** [comment]
fwiw, you generally want `extend-ignore` and not `ignore` -- it'd cut half of your ignore list
