### ISSUE TITLE
pyproject.toml support blockers

### ISSUE THREAD

**Issue by bmwant** [PyCQA/flake8#1571]
### describe the request

Hey, I'd like to understand what are current blockers preventing to implement `pyproject.toml`-based configuration for flake8. Is there any ongoing work in this direction?

List of blockers from this thread is not available at the moment https://github.com/PyCQA/flake8/issues/234.
Maybe it's about time to resume implementation of the feature?

cc @asottile

**Comment by asottile** [comment]
scroll up in the thread
