### ISSUE TITLE
Unable to install latest version of flake8 and sphinx togehter

### ISSUE THREAD

**Issue by vilhelmprytz** [PyCQA/flake8#1582]
### how did you install flake8?

```console
$ pipenv --python 3.7
$ pipenv install flake8
$ pipenv install sphinx
# (fails because flake8 requires importlib-metadata<4.3 and sphinx importlib-metadata>=4.4)
# also tried this in normal venv (i.e. not pipenv) with same result
```

### unmodified output of `flake8 --bug-report`

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.13",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}
```

#### what I expected to happen

I expect sphinx and flake8 to be installable in the same virtual environment.

...

#### commands ran

Not really applicable.

**Comment by asottile** [comment]
please search the issue tracker next time -- for example "sphinx" or "sphinx importlib-metadata" have multiple duplicates

**Comment by vilhelmprytz** [comment]
Ah, I did actually search before opening the issue but I realize now my mistake; I only searched for open issues... sorry! I had to dig around quite a bit to find a comment addressing why it's not "fixed". I understand I'm not the first one to open this duplicate issue but probably not the last either :(.
