### ISSUE TITLE
Run flake8 on code snippets in docstrings or RST files

### ISSUE THREAD

**Issue by KushalBeniwal** [PyCQA/flake8#1587]
### describe the request

We at [pandas](https://github.com/pandas-dev/pandas/issues/46865) are currently using flake8-rst to run flake8 on code snippets in docstrings or RST files, but flake8-rst is not maintained.
I searched around for a maintained tool that does the same thing but couldn't find much, any leads/help will be appreciated!

**Comment by asottile** [comment]
I'm not aware of any such tool beyond flake8-rst -- it's not really in scope for flake8 itself but I'm hoping to make flake8's api easier to use such that a "flake8 rst checker" could presumably be made without needing to reach into internals
