### ISSUE TITLE
select setting in .flake8 does not recognize comments

### ISSUE THREAD

**Issue by MHLut** [PyCQA/flake8#1592]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.13",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "22.4.25"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}
```

#### what I expected to happen

The setting `select` in `.flake8` to does not distinguish between values and comments on the same line. I mentioned a non-selected error code in a comment and flake8 proceeded to check for it.

I use `flake8-bugbear` in my examples but have confirmed that this issue also happens with other error codes (including `E`).

The bug occurs ONLY when the comment is on the same line as the selected error code. It happens for both comments starting with `#` and `;`.

#### sample code

Context: `flake8-bugbear` uses error codes starting with `B`. The package excludes `B9` by default, and requires you explicitly select `B9`.

**Situation 1:** without mentioning `B9` in a comment

```ini
[flake8]
# Non-relevant settings left out for brevity
select =
    B, # flake8-bugbear
count = True
statistics = True
```

**Situation 2:** mentioning `B9` in a comment

```ini
[flake8]
# Non-relevant settings left out for brevity
select =
    B, # flake8-bugbear (sans B9, which must be activated separately)
count = True
statistics = True
```

#### commands ran

```console
$ flake8 src/
...
```

Output for **situation 1** (expected):

```
0
```

Output for **situation 2** (unexpected):

```
src/REDACTED:LINE:COLUMN: B950 line too long (139 > 119 characters)
1     B950 line too long (139 > 119 characters)
1
```

**Comment by asottile** [comment]
please read the docs, this is addressed in a big warning box

**Comment by MHLut** [comment]
Apologies!

I just found the information in an info box on https://flake8.pycqa.org/en/latest/user/configuration.html ("Following the recommended settings for [Python’s configparser](https://docs.python.org/3/library/configparser.html#customizing-parser-behaviour), Flake8 does not support inline comments for any of the keys.")

Is it possible to update the docs to display a concise warning instead of a note box? Also, while the note says flake8 doesn't support inline comments, they do work somewhat.

**Comment by asottile** [comment]
not sure what you mean, I think the current docs are pretty clear

they also don't "somewhat work" the online comments aren't parsed at all and become the value

**Comment by MHLut** [comment]
> "not sure what you mean, I think the current docs are pretty clear"

I expected an actual warning box and not a note since warnings attract more attention.

> "they also don't "somewhat work" the online comments aren't parsed at all and become the value"

Check. The documentation doesn't explicitly mention that, which means my original code only gave the impression that it did work (no warning or errors thrown)
