### ISSUE TITLE
Extend extend-exclude with both config file and command line option

### ISSUE THREAD

**Issue by shangxiao** [PyCQA/flake8#1593]
### describe the request

Currently if you specify an `extend-exclude` in your config as well as a command line option `--extend-exclude` then this appears to override that of the config files. Having both is a useful way to exclude certain patterns specific to the source code then again extend depending on how it's invoked, eg for CI.

I was kinda hoping both would extend to the exclude list instead of the CLI option taking preference. Perhaps a new option to extend the extend-exclude?

**Comment by asottile** [comment]
command line options always override the configuration -- anything else would be confusing

**Comment by shangxiao** [comment]
@asottile 

> command line options always override the configuration -- anything else would be confusing

I wasn't referring to having `--extend-exclude` extend the config option, which is why I asked:

> Perhaps a new option to extend the extend-exclude?

**Comment by asottile** [comment]
yes and my response is that's not how command line options work in flake8, nor in any normal command line tool -- doing so would add a very special case and would be a confusing and breaking behaviour for users
