### ISSUE TITLE
Add enabling/disabling of error codes throughout the file

### ISSUE THREAD

**Issue by amirebrahimi** [PyCQA/flake8#1594]
### describe the request

Currently, it's possible to disable error checks for a whole file with:
```
# flake8: noqa
```

It's possible to ignore a warning on a single line:
```
example = lambda: 'example'  # noqa: E731
```

Would it be possible to enable and disable warnings throughout the file similar to [C#'s pragma statements](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#pragma-warning)?

An example would be (on it's own line):
```
# noqa: disable E731
... code
... more code
# noqa: enable E731
```

If this isn't easy to add, then would it be possible to get per-file warning disables instead of having to use the `.flake8` configuration file:

Ex:
```
# flake8: noqa: E731
```

**Comment by asottile** [comment]
please search the issue tracker next time #1559 #1336 #324

**Comment by amirebrahimi** [comment]
Forgot to check closed issues, but disappointed nonetheless.
