### ISSUE TITLE
Explicit select list ignored if it matches the default list

### ISSUE THREAD

**Issue by duncanmmacleod** [PyCQA/flake8#1604]
### how did you install flake8?

```console
$ conda install -c conda-forge flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.4",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "3.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-colors",
      "version": "0.1.9"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.6.0, pydocstyle: 6.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "4.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "3.3.1"
    },
    {
      "is_local": false,
      "plugin": "import-order",
      "version": "0.18.1"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    },
    {
      "is_local": false,
      "plugin": "radon",
      "version": "5.1.0"
    }
  ],
  "version": "4.0.1"
}
```

#### what I expected to happen

When I manually specify `--select`, it should **always** be used, even if it happens to match the default select list. Currently if the select list matches the default, it is ignored.

#### sample code

```python
print("hello world!")
```

#### commands ran

```console
$ flake8 --select C90,E,F,W test.py
test.py:1:1: D100 Missing docstring in public module
test.py:1:7: Q000 Double quotes found but single quotes preferred
```

**Comment by asottile** [comment]
dupe #284

**Comment by asottile** [comment]
nope, we never plan to release again

**Comment by asottile** [comment]
of course there will be a release

**Comment by asottile** [comment]
and what would you possibly do with such an answer?

asking for a release is rude, it'll happen when it happens -- if you want to be notified watch the repository

**Comment by duncanmmacleod** [comment]
@asottile, I'm sorry if I offended, and sorry if I'm now flogging a dead horse. I'm not asking _for_ a release, just curious to know the timeline.

'It'll happen when it happens' is a fine answer.

**Comment by asottile** [comment]
why are you asking for a timeline?

**Comment by duncanmmacleod** [comment]
I am curious to know when I would be able to install a new version of flake8 that doesn't have the problem I reported. It won't impact any schedules or work plans, I'm just curious.
