### ISSUE TITLE
Fix GitLab setting for default branch

### ISSUE THREAD

**Issue by georgemarshall** [PyCQA/flake8#1605]
### describe the request

The GitLab mirror still uses "master" as its default branch instead of "main".

https://gitlab.com/pycqa/flake8/

This breaks the `pre-commit autoupdate` command causing it to downgrade from `4.0.1` to `3.9.2`.

Here is the relevant update logic that is used for the `autoupdate` command.

https://github.com/pre-commit/pre-commit/blob/44cb80f74ac95f347fd66e0eb8d432b7cee4ca83/pre_commit/commands/autoupdate.py#L36-L72

**Comment by asottile** [comment]
use github, we've migrated away from gitlab and will not be updating the mirror

**Comment by georgemarshall** [comment]
> use github, we've migrated away from gitlab and will not be updating the mirror

I understand that, but this is non-obvious issue and a simple fix for anyone that has the correct admin access to the repository.

**Comment by asottile** [comment]
the simple fix is to not use gitlab

**Comment by georgemarshall** [comment]
@asottile that's a rather sarcastic and rude response.

To get to the desired outcome, I am looking for one of the following:

* Fix the default branch setting for the GitLab repository
* Remove the GitLab mirror altogether
