### ISSUE TITLE
flake8 docs outdated regarding user-level configuration

### ISSUE THREAD

**Issue by ihasdapie** [PyCQA/flake8#1608]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
n/a
```

### describe the problem

https://flake8.pycqa.org/en/4.0.1/user/configuration.html

`flake8 > 4` doesn't support user-level configuration i.e. `~/.config/flake8`. I could not figure out why this wasn't working until I went through the changelog. The docs have not yet been updated to reflect this change.

**Comment by asottile** [comment]
you're looking at docs for a particular tag -- which unfortunately at the time of that tag the docs were not updated --  you want https://flake8.pycqa.org/en/latest/user/configuration.html

**Comment by ihasdapie** [comment]
Ah ok, glad to see it's been fixed since.
