### ISSUE TITLE
Support for command line option --prepend-config

### ISSUE THREAD

**Issue by tobast** [PyCQA/flake8#1616]
### describe the request

Support for a user-wide (XDG config) was recently dropped through #1404. As I understand it, it was a hassle to maintain because of people not understanding this feature correctly. However, setting default options is particularly useful, especially when using flake8 by default at editor-level (I use it through ALE in Vim). By default, I expect my Python files to have a line length of at most 88 characters, which is not Flake8's default ; I would thus like to configure flake8 by default when invoked from Vim to use this limit instead.

I cannot, however, just pass `--config ~/.config/flake8` to flake8: this would overrule project-level configuration files. I cannot either use `--append-config`, since I want project-level configuration files to take precedence.

I believe a good solution would be to support a `--prepend-config` option, which would be exactly the same as `--append-config`, with the only difference of having less precedence than the automatically discovered configuration files.

I have seen that there was a previous merge request #1301 describing such a feature; however, I cannot figure out what happened to it exactly with the gitlab migration. It seems to me that it was never merged, and as I don't see a discussion in the thread, I would like to bring forward the idea again -- although I imagine the code will have to be at least adapted, at worst re-written since the project has moved a bit since then.

**Comment by asottile** [comment]
the behavior you're describing is exactly what we wanted to prevent by removing the global configuration -- that a user can surprisingly get different results when working on a project. so I don't think this use case is enough to add the complexity and option you're describing

also you can use append config -- just use your base configuration as the config and the project one as the appended config
