### ISSUE TITLE
DeprecationWarning in flake8,plugins.manager

### ISSUE THREAD

**Issue by diekhans** [PyCQA/flake8#1619]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.5",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}
```

### describe the problem

If one runs flake8 with PYTHONWARNINGS=always, one gets

..../python3.10/site-packages/flake8/plugins/manager.py:261: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  eps = importlib_metadata.entry_points().get(self.namespace, ())
..../python3.10/site-packages/flake8/plugins/manager.py:261: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  eps = importlib_metadata.entry_points().get(self.namespace, ())

#### what I expected to happen

no warning in flake8 code

#### sample code

```
print("foo")
```

#### commands ran

```console
$ PYTHONWARNINGS=always flake8 foo.py 
...

**Comment by asottile** [comment]
search the tracker
