### ISSUE TITLE
flake8 5.0 seemingly deprecated .flake8 config without writing it in the changelog

### ISSUE THREAD

**Issue by eivindjahren** [PyCQA/flake8#1630]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.4",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.0"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.0"
}
```

### describe the problem

After upgrading to flake8 5.0, it now silently ignores my .flake8 file. I had not expected this as it is not described in the changelog. Everything works fine once the flake8 config is moved to setup.cfg.

**Comment by asottile** [comment]
show your configs? they should both work and we test that they both work

**Comment by asottile** [comment]
ah, you have flake8 config in both files. the first one wins and the first one was changed (this *is* called out in the changelog under fixes, that the config containing `[flake8]` is considered)

you were in undefined behavior before with config in two files

**Comment by eivindjahren** [comment]
Thanks for the help! We understand what was going on now :)
