### ISSUE TITLE
Configuration file feature request revisited now that concerns addressed

### ISSUE THREAD

**Issue by NeilGirdhar** [PyCQA/flake8#1632]
### describe the request

Now that the situation has significantly changed, I would humbly like to request support for configuration using pyproject.toml.  Apologies for not contacting the maintainer privately as requested, but I believe this should be on the tracker so that the community can observe any discussion!

In https://github.com/PyCQA/flake8/issues/234, Aaron [wrote](https://github.com/PyCQA/flake8/issues/234#issuecomment-812800722) that the two blockers are:

- pip to change its behaviour so mere presence of the file does not change functionality, and
- python to consider adding a standard library toml implementation.

The problem with Pip is summarized in https://github.com/pypa/pip/issues/6433 and https://github.com/pypa/pip/issues/6434 and solved by https://github.com/pypa/pip/pull/6442.

[PEP 680](https://peps.python.org/pep-0680/) added `tomllib` to Python 3.11.  Before that, equivalent library support is provided by the stable [`tomli`](https://github.com/hukkin/tomli).

Are there any other blockers for pyproject.toml support?  If not, it appears that a patch would be [quite short](https://github.com/csachs/pyproject-flake8/blob/main/pflake8/__init__.py).

**Comment by asottile** [comment]
- neither of the pip issues you linked are related
- you did not read the issue template: **NOTE: if you ask about pyproject.toml your issue will be closed as a duplicate of [#234](https://github.com/PyCQA/flake8/issues/234)**
