### ISSUE TITLE
Plugin name restriction might be a bit too aggressive

### ISSUE THREAD

**Issue by mCodingLLC** [PyCQA/flake8#1643]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.4",
    "system": "Windows"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.0"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.2"
}
```

### describe the problem

It seems that https://github.com/PyCQA/flake8/commit/f3443f4a7836aa947de29466902127d527f0ab89 introduced a restriction on plugin codes to follow the regex `^[A-Z]{1,3}[0-9]{0,3}$`. While I am generally in favor of restricting plugin codes to follow a reasonable pattern, I think that this regex is a bit too limiting. If a plugin uses a common letter prefix then this limits the number of distinct checks a plugin can define to 1000. Moreover, the limit of 3 letters just happens to hit me as I have previously made a flake8 tutorial [video](https://www.youtube.com/watch?v=OjPT15y2EpE) where I used plugin codes like `MCOD101`, which seems reasonable to me but does not follow this regex.

I suggest a slightly less limiting regex:

     `^[A-Z]{1,8}[0-9]{0,8}$`

or even just

     `^[A-Z]{1,}[0-9]*$`

**Comment by asottile** [comment]
your video is incorrect, sorry -- flake8 only allows up to 3 letter codes

if you read the PR and the linked issue there's an explanation

**Comment by mCodingLLC** [comment]
Hi @asottile, I believe the linked issue you are referring to is https://github.com/PyCQA/flake8/pull/1579, but my issue concerns error codes that already comply with that regex:

E.g.:
    # ``# noqa:E123,W451,MCOD123``

matches `# noqa(?::[\s]?(?P<codes>([A-Z]+[0-9]+(?:[,\s]+)?)+))?`.

I'm sure my video contains numerous errors as I'm sure you understand from your own experience producing videos, but an `ABCD123` plugin code has been working just fine for years, as was demonstrated in the video. Moreover, the latest documentation for writing plugins does not mention this 3 letter limit anywhere. The only relevant documentation I can find on this naming convention is https://flake8.pycqa.org/en/5.0.2/plugin-development/registering-plugins.html where it specifically notes:

> Please Note: Your entry point does not need to be exactly 4 characters as of Flake8 3.0. Consider using an entry point with 3 letters followed by 3 numbers (i.e. ABC123 ).

This appears to me to indicate flexibility in naming, not a hard 3-letter 3-number limit. So while you may have been privately assuming plugins must be at longest `ABC123` for some time now, the documentation has not communicated this to plugin writers, and calling a fully functional plugin using a code `ABCD101` "incorrect" due to undocumented restrictions about the name when `A101`, `AB101`, and `ABC101` are all fine seems a bit much.

Ultimately I appreciate the work you do on flake8 regardless of the outcome of this issue and if you so choose to enforce this 3-letter limit ultimately that's not a big deal, but at the very least I would ask you document this assumption in the plugin development section.

**Comment by asottile** [comment]
`MCOD` does not match `{1,3}` which is required for flake8 to function properly (4+ letter names are silently ignored in `noqa` and `per-file-ignores` as the linked issues speak about)

This has been documented since it was allowed in flake8 3.0: https://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html

> Your entry point does not need to be exactly 4 characters as of Flake8 3.0. Consider using an entry point with 3 letters followed by 3 numbers (i.e. ABC123 ).

**Comment by asottile** [comment]
also it hasn't been working "just fine" for years -- it's been subtly broken for years -- and now I am choosing to enforce that things are correct rather than allowing them to silently fail

**Comment by mCodingLLC** [comment]
@asottile This message (which I already quoted) does not communicate the 3-letter-maximum requirement.

> Your entry point does not need to be exactly 4 characters as of Flake8 3.0. Consider using an entry point with 3 letters followed by 3 numbers (i.e. ABC123 ).

"Consider" here is being used to indicate a requirement, which is the opposite of its normal meaning in English, an option. I recommend changing this as the way it is currently worded is conveying the opposite meaning as the way you are using it.

**Comment by asottile** [comment]
the sentence to me reads "you used to only be able to use 1 character codes, now you can use 3"

**Comment by mCodingLLC** [comment]
@asottile I can see how you can reasonably interpret it that way and I'm glad you intended to document this restriction. However, the text is not reading to me and apparently to other developers who are posting these issues as the way you intended it to be read. I think it has and will continue to be reasonably interpreted as "you used to only be able to use 1-character codes, that restriction no longer exists, CONSIDER using 3-character codes" indicating that 3-characters is a suggestion, not a requirement.

If your intention is that only 1- and 3-character codes are allowed, please change it to explicitly say that. I don't want to change `MCOD101` to `MC101` in all of my codebases just to have 2-character codes broken in the future. I apologize for all the fuss I really just think the documentation is not coming off as intended and I think it would help developers in the future to clarify the requirements, whatever they they happen to be.

**Comment by sigmavirus24** [comment]
@mCodingLLC having not watched any of your videos it doesn't seem like you're testing things closely. The tool didn't validate the codes early and would silently ignore things later if it didn't match expectations. This is failing early to let folks know things will break. That's the change. That's all. You're welcome to profit off this project by making your content but it doesn't give you the right to try to make up nonsense arguments to have. There's no potential future where a 2 letter prefix isn't allowed. We may increase the upper limit as I did in 3.x to help avoid conflicts but that's a backwards compatible change and not one there's any need to do now.

To reiterate, **these are not new restrictions, just a better user experience. **
