### ISSUE TITLE
issue #1598 appears to have been locked by mistake

### ISSUE THREAD

**Issue by zacharyburnett** [PyCQA/flake8#1651]
### describe the request

I noticed that issue #1598 appears to have been insta-locked without discussion; I imagine this is accidental (perhaps an automated process?), as the issue does bring up a good point on legacy support for a now-deprecated installation / configuration method, and usage of a new method that is adopted by a large amount of projects and now has beta support by `setuptools`. 

I would be interested in discussing this issue further, as I use `flake8` on a lot of downstream projects and supporting this legacy `setup.cfg` configuration method is fast becoming an exception that I have to make for `flake8` alone. I would ask that issue #1598 be unlocked so as to have a place to discuss this, if that is convenient for you. Thank you for your time!

**Comment by sigmavirus24** [comment]
Not by mistake. You united the issue template as well

**Comment by asottile** [comment]
from the issue template:

> **NOTE: if you ask about pyproject.toml your issue will be closed as a duplicate of #234**
