### ISSUE TITLE
`flake8.exceptions.FailedToLoadPlugin`: Flake8 failed to load plugin `flake8-isort` due to cannot import name `SortImports` from `isort`

### ISSUE THREAD

**Issue by wiseaidev** [PyCQA/flake8#1654]
### how did you install flake8?

I am using flake8 as a pre-commit hook:

https://github.com/wiseaidev/awesome-code/blob/9810a6b6da43c1622a0c4da4ef5ef158746fc81a/.pre-commit-config.yaml#L29-L33

### unmodified output of `flake8 --bug-report`

You can refer to [this `pre-commit.ci` output](https://results.pre-commit.ci/run/github/503733526/1659390598.KG7L59I7TouCwGYjr-75yQ) for more info.

#### what I expected to happen

I am expecting `pre-commit-ci` to run as expected. However, it seems like the `flake8-isort` plugin was removed in the newer version of flake8.

You can refer to this PR [#awesome-code/pull/12](https://github.com/wiseaidev/awesome-code/pull/12) for more context about the issue.

**Comment by sigmavirus24** [comment]
You haven't provided the output of the bug report debug output and we don't control flake8-isort. It seems to be importing something from isort which no longer exists. Without knowing more, it would seem that this is just the first run to detect this issue for you. This is not a bug in flake8
