### ISSUE TITLE
assert() is no loner valid

### ISSUE THREAD

**Issue by JakobDev** [PyCQA/flake8#1659]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.5",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}
```

### describe the problem

The following expression was valid in earlier versions.
```python
assert(1 == 1)
```
But in the newest version it throws this error:
```
E275 missing whitespace after keyword
```
I don't know if this is supposed to throw an error, but since the [release note](https://flake8.pycqa.org/en/latest/release-notes/index.html) did not say anything about a change that could affect this, I guess it is a bug. If not feel free to close.

**Comment by asottile** [comment]
you missed the prompt at the issue selection screen and the comment at the top of the template
