### ISSUE TITLE
flake8 color config not picked up in either .flake8, setup.cfg, or tox.ini

### ISSUE THREAD

**Issue by velicanu** [PyCQA/flake8#1661]
### how did you install flake8?

```console
pip install flake8  # currently version 5.0.4
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.13",
    "system": "Darwin"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}
```

#### what I expected to happen
Added a `color = never` to the .flake8 config in my project and expected the color output to be disabled. I confirmed that the config file itself was being picked up by toggling the warnings flake8 produced. I also tried with both `setup.cfg` and `tox.ini` but the color config isn't picked up in those either.

I stumbled across this because I suspect that color defaulting to `on` in 5.0 is responsible for breaking [flycheck](https://github.com/flycheck/flycheck/issues/1969) compatibility.

#### sample code

Full .flake8 config
```
[flake8]
ignore = E203, E266, E501, W503
max-complexity = 18
color = never
```

Python code
```python
def bar():
    x = "123"

    json.dumps({})
```

#### flake8 output

<img width="598" alt="Screen Shot 2022-08-10 at 8 03 01 AM" src="https://user-images.githubusercontent.com/5022772/183938599-d2ba9fa6-ad79-4455-bc30-391f706fd5c3.png">

**Comment by asottile-sentry** [comment]
I don't think this is what's breaking flycheck -- it looks like they execute always with `--apend-config .flake8rc` which will now error if `.flake8rc` does not exist

they should adjust their call to not pass configuration files which don't exist

**Comment by asottile** [comment]
I don't think this is what's breaking flycheck -- it looks like they execute always with `--apend-config .flake8rc` which will now error if .flake8rc does not exist

they should adjust their call to not pass configuration files which don't exist
