### ISSUE TITLE
Improve bug report template

### ISSUE THREAD

**Issue by hans2520** [PyCQA/flake8#1664]
> yeah you were in undefined territory before -- now flake8 only looks at files containing `[flake8]` (and stops at the first one) (the 5.0 changelog mentions this)
> 
> but none of your original issue came even close to describing your scenario -- in the future please actually follow the template and fill it out properly -- we don't have access to your computer so we can't possibly help you if you don't provide any information about your problem

_Originally posted by @asottile in https://github.com/PyCQA/flake8/issues/1663#issuecomment-1212721553_

In the referenced issue, the template was filled out exactly as requested. There were no details left out from what was requested by the instructions.

The issue was only discovered after analysis, which could not have been detected without a back-and-forth discussion as the cause of reproducibility / lack thereof was not obvious. This could not have been obvious on initial pass without the template asking for all the source code of relevant files, which the template does not request.  For example, the template did not ask for [flake8] settings, nor was it indicated that [flake8] settings may be present in different files concurrently (it was also suggested that 5.0 changelog may have 
 made this obvious (i.e. https://flake8.pycqa.org/en/latest/release-notes/5.0.0.html), although the template does not mention changelogs (nor was this issue apparently mentioned in the aforementioned release notes)

**Comment by asottile** [comment]
it does, you just didn't read it or fill it out:

> # describe the problem
>
> please provide sample code and directions for reproducing your problem including the commands you ran, their unedited output, and what you expected to happen

**Comment by hans2520** [comment]
Sample code `was` provided in the attached issue, which reproduced issue on source system... but it was not `all` the relevant code (because it was not apparent that there were multiple files with multiple [flake8] settings at first). It might be better to request all the code of a reproducible project in the template vs just sample code.

**Comment by asottile** [comment]
I'm sorry but I can't give you the benefit of the doubt that you earnestly believe what you posted constitutes "sample code" and "directions for reproducing your problem".  there's no code there and no directions

**Comment by hans2520** [comment]
You did recreate the sample environment perfectly from the instructions of the issue report (which contained configuration code) and proved it was not valid in your environment. If there was a genuine bug simply with a single config file, the report instructions _would have been_ sufficient to recreate the problem.

All that said, the exact same output provided in your first comment could have been in initial report, and it still would have been reproducible in the source system and still not reproducible in yours. 

Since the root cause was due to two [flake8] sections in two different files (one of which the issue opener was not aware of without further investigation), the only way issue could have been solved on first pass would have been to request all code of all [flake8] sections (and to note they may be defined in multiple files), and not request only a mere sample. 

I do want to thank you for the response as your your first comment provided exactly the insight needed to figure out something else was off with the source environment to do the additional analysis needed. This might have been done on its own prior to bug open if the template asked for all code pertaining to [flake8] sections in all files.

**Comment by asottile** [comment]
ok well in case it's not clear -- what you did was not good and was a waste of time for everyone involved

for your future success in open source (independent of this project) I need you to understand that what you did was not ok

when reporting bugs to maintainers who you are expecting to support you **for free** you need to put in an ounce of effort to report your actual problem

at **minimum** this should include enough information to reproduce your problem in a vacuum **independent of there being an issue template which tells you to do precisely that**

the template is there because so many individuals like you don't know this and expect us to be mind readers (which we're not exceptionally good at, but as you saw from your thread sometimes we hit)

if video-form is more your style I'd recommend watching this -- https://youtu.be/ritp4gAqNMI
