### ISSUE TITLE
Help text claims custom config values to be the default values

### ISSUE THREAD

**Issue by chrisRedwine** [PyCQA/flake8#1666]
### how did you install flake8?

```console
pyenv install 3.9.13
pyenv local 3.9.13
pyenv virtualenv flake8-py39
pyenv activate flake8-py39
pip install -U pip
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.13",
    "system": "Darwin"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}
```

### What I expected to happen
<br/>

Let's say I have a `.flake8` config file such as:

```
[flake8]
exclude = 1,2
```

When I run `flake8 -h`, I would expect the help text for the `--exclude` option to say the following (note the defaults):

```
  --exclude patterns    Comma-separated list of files or directories to exclude. (Default: ['.svn', 'CVS', '.bzr', '.hg', '.git', '__pycache__', '.tox', '.nox', '.eggs', '*.egg'])
```

However, the actual output clobbers the true defaults and instead claims the config values as the default values (which is quite unintuitive and can be very misleading if you take them to be the actual default values that flake8 provides):

```
  --exclude patterns    Comma-separated list of files or directories to exclude. (Default: ['1', '2'])
```

One other trivial thing is that the current output of comma-separated lists does not match the format shown in the [documentation](https://flake8.pycqa.org/en/latest/user/invocation.html#invoking-flake8): 

`['.svn', 'CVS', '.bzr', '.hg', '.git', '__pycache__', '.tox', '.nox', '.eggs', '*.egg']` 
vs. the documented:
`.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.nox,.eggs,.egg`.

  
### Why it happens
<br/>

Looking at `src/flake8/options/aggregator.py`, the `aggregate_options` function overrides the default option values with the config values. Moreover, in `src/flake8/main/options.py`, we're using the `%(default)s` format specifier in the option help strings. Thus, when the help text actually gets printed it uses the updated values instead of the original defaults 😢 .

  
### Failing test case
<br/>

Adding this test case to `tests/integration/test_main.py` asserts the desired behavior and successfully reproduces the issue:

```python
import re

from flake8.defaults import EXCLUDE


def test_config_value_does_not_clobber_default_help_text(tmpdir, capsys):
    """Test a config value does not clobber the default help text output."""
    setup_cfg = """\
[flake8]
exclude = 1,2
"""
    expected = ",".join(EXCLUDE)

    default_pattern = re.compile(r"\(Default:(.*?)\)")
    whitespace_pattern = re.compile(r"\s+")

    with tmpdir.as_cwd():
        tmpdir.join("setup.cfg").write(setup_cfg)
        with pytest.raises(SystemExit):
            cli.main(["-h"])

    out, err = capsys.readouterr()

    for section in out.split("--"):
        if section.startswith("exclude patterns"):
            section = re.sub(whitespace_pattern, "", section)
            default_groups = re.search(default_pattern, section)
            assert default_groups is not None
            default = default_groups.group(1)
            assert default == expected
```

  
### Potential solution
<br/>

I believe the simplest solution would be to handle this in the initializer for the `Option` class (`src/flake8/options/manager.py`), binding any instance of `%default` or `%(default)s` in the `help` arg with the passed `default` arg, such that it doesn't subsequently get overridden by later argparse shenanigans. This should also fix the difference in format vs. the documentation that I mentioned.

If there's an appetite for it, **I would love to put together a PR** with the above test/implementation. Thanks!

**Comment by asottile** [comment]
https://github.com/PyCQA/flake8/pull/1667#issuecomment-1214341943
