### ISSUE TITLE
Copyright in docs is outdated

### ISSUE THREAD

**Issue by kasium** [PyCQA/flake8#1675]
### describe the problem

When looking at the [documentation](https://flake8.pycqa.org/en/latest/), the copyright states `© Copyright 2016, Ian Stapleton Cordasco Revision a929f124`.

Definitive the year is wrong, however the copyright owner is maybe also outdated (not sure but it worth's a check)

**Comment by sigmavirus24** [comment]
Copyright years don't need updating. Copyright doesn't change owners, I still own the copyright under copyright law.
