### ISSUE TITLE
Missing incompatible change in release notes

### ISSUE THREAD

**Issue by kasium** [PyCQA/flake8#1676]
### describe the problem

In difference to flake8 4.x, a `off_by_default` plugin must be explicitly activate in flake8 5.x by using `enable-extensions`. This is not documented [here](https://flake8.pycqa.org/en/latest/release-notes/5.0.0.html#backwards-incompatible-changes) and took me some time to figure out, why my plugins are not loaded anymore.

Therefore it would be great if this could be added

**Comment by asottile** [comment]
can you describe further, that didn't change afaik

**Comment by kasium** [comment]
Sure, so I just need to clarify, that I meant with "disabled" `off_by_default` (corrected it also above).

So here is an example

**setup.py**
```py
from setuptools import find_packages, setup
if __name__ == "__main__":
    setup(
        packages=find_packages(include=("src",)),
        entry_points={"flake8.extension": ["X = src.plugin:Plugin"]},
    )
```

**src/plugin.py**
```py
class Plugin:
    name = "test"
    version = "1.0.0"
    off_by_default = True

    def __init__(self, tree):
        pass

    def run(self):
        yield (1, 1, "X this is a test", type(Plugin))
```

Then run `flake8 src --select X`
* flake8 4.x : `src/__init__.py:1:2: X this is a test`
* flake8 5.x: _no output_

For flake8 I need to create a config file with the content
```ini
[flake8]
enable-extensions = X
```
Afterwards the output appears

**Comment by asottile** [comment]
the 4.x behavior looks wrong, if it's off it shouldn't be running

**Comment by asottile** [comment]
note also that `off_by_default` is undocumented and I'm not sure if it's supposed to be supported or not

**Comment by kasium** [comment]
Thanks for the clarification. I guess I've seen the flag in some plugin before. Can you please check if you want to support this flag. IMHO it's a cool feature.

If documentation is needed, I'm happy to create a PR

**Comment by asottile** [comment]
sure feel free to send some docs
