### ISSUE TITLE
Use `extend-ignore` in documentation examples over `ignore`

### ISSUE THREAD

**Issue by wookie184** [PyCQA/flake8#1679]
Generally, the behaviour of `--extend-ignore` is preferred over that of `--ignore`, and the difference is a fairly common confusion. Due to this I think it would make more sense to show `--extend-ignore` in general examples.

The instance I noticed that gave me this idea was this one on the front page:
https://github.com/PyCQA/flake8/blob/e249dc47dfd314c34bbd0946c3fad970a8b15d6c/docs/source/index.rst#L67

I also had a look for other examples. One I noticed was this, which could probably also be changed anyway given that flake8's config now uses `extend-ignore` (there are a couple of other things there that are no longer flake8's current config, not that it really matters):
https://github.com/PyCQA/flake8/blob/e249dc47dfd314c34bbd0946c3fad970a8b15d6c/docs/source/user/configuration.rst#L88-L103

I'd be happy to open a PR if this is a change you think is worth doing. (Note: there were a couple of other examples that could be changed, for example [here](https://github.com/PyCQA/flake8/blob/e249dc47dfd314c34bbd0946c3fad970a8b15d6c/docs/source/internal/writing-documentation.rst#L63), although as they're more internal I don't mind as much).

Thanks for flake8!

**Comment by asottile** [comment]
feel free to send a patch !
