### ISSUE TITLE
Make pycodestyle optional ?

### ISSUE THREAD

**Issue by joaoe** [PyCQA/flake8#1685]
Hi.

Black is becoming more and more popular. It is unlikely that developers at this time spend time formatting code manually and instead trust their formating tools to keep formatting consistent (black, autopep8, yapf).

Therefore the dependency on pycodestyle is something many do not need for their projects, while it adds to run time. This is significant for big projects. Despite filtering away all E and W warnings, flake8 will still invoke pycodestyle, and filter warnings after.

So, the suggestion is for flake8 by default not depend on pycodestyle, and only if pycodestyle is installed will flake8 then load and run its pycodestyle plugin.

**Comment by asottile** [comment]
#488 is a better approach

I don't necessarily agree with the sentiment though -- there are things which black does not format

**Comment by joaoe** [comment]
> there are things which black does not format

True, like long strings og long identifiers, but that does not mean that the developer wants pycodestyle to slowly run through all the code.
