### ISSUE TITLE
warn on invalid codes in `ignore` / `extend-ignore`

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1689]
### describe the request

for example https://github.com/getsentry/sentry-python/blob/b36d84a76bd6f8344c9b0a9694591939296e9c06/.flake8#L2-L13

this disables a code called `//` and a code called `I` (among many others) due to incorrect comment syntax

**Comment by jaap3** [comment]
For those coming here from the release notes, any type of inline comment is considered invalid. But comment lines **are** valid, so in other words:

Invalid:

```
ignore =
    W503  # https://www.flake8rules.com/rules/W503.html
```

Valid:

```
ignore =
    # https://www.flake8rules.com/rules/W503.html
    W503
```
