### ISSUE TITLE
Make better use of my CPU

### ISSUE THREAD

**Issue by gcobr** [PyCQA/flake8#1690]
### describe the request

I am running `flake8` 4.0.1 over a very large codebase. I am using a MacBook with an M1 Pro processor which has 10 cores.
I am running Python for Apple Silicon.
When `flake8` is running, even though I use `--jobs=auto` or `--jobs=10`, it takes forever and I don't see any meaningful increase in CPU usage in the macOS Activity Monitor. I don't know much about the internal architecture of `flake8`, but I wonder if it couldn't really make better use of concurrency, use more of my idle CPU capacity, and complete the job faster.
My CPU is around 90% idle while `flake8` is running, and it takes about 5 mins to complete a scan.

**Comment by asottile** [comment]
I'm reworking the plugin system such that we can do this -- but macos is "spawn" based and currently plugins depend on global mutation and `fork` semantics so multiprocessing is disabled there (add some `-vv` and notice the warning)

also please do not skip the template, it includes important information
