### ISSUE TITLE
Expose package root to plugins

### ISSUE THREAD

**Issue by PeterJCLaw** [PyCQA/flake8#1691]
### describe the request

It would be great if there was a way for plugins to know what the apparent root of a package being linted is. This would be useful mostly for import linters which want to apply rules about where imports can come from, though there may be other uses.

I'll admit I'm not entirely sure what the "correct" way to define the root of a project is (nor what to do for a source tree that contains several independent packages), though these all feel like things that would be best solved centrally rather than by each plugin separately.

https://github.com/PyCQA/flake8/issues/759 miiiight be related here given that that relates to local relative paths, though I can also imagine it being solved separately.

**Comment by asottile** [comment]
flake8 doesn't know this information and it isn't determinable statically -- it would have to be a plugin option and supplied explicitly in the case that the import root isn't the project root (otherwise a file option which defaults to `.` should get the right absolute value)
