### ISSUE TITLE
suggest isinstance calls for runtime-checkable protocols instead of using hasattr

### ISSUE THREAD

**Issue by twoertwein** [PyCQA/flake8#1697]
### describe the request

Static type checkers do not understand statements like:
```py
if hasattr(x, "__len__") and len(x) > 0:
    ...
if hasattr(x, "__hash__") and hash(x) == hash(something_hashable):
    ...
```
but they understand very similar statements like
```py
from collections.abc import Sized, Hashable

if isinstance(x, Sized) and len(x) > 0:
    ...
if isinstance(x, Hashable) and hash(x) == hash(something_hashable)::
    ...
```

I'm not sure how common `__hash__/Hashable` is but `__len__/Sized` occurs more frequently.

It might be nice to discourage `hasattr(x, "__len__")` and suggest `isinstance(x, Sized)` instead.

**Comment by asottile** [comment]
please read the template:

> ** NOTE: flake8 is a linting framework and does not implement any checks**
