### ISSUE TITLE
Open to funding?

### ISSUE THREAD

**Issue by lorenzwalthert** [PyCQA/flake8#1700]
### describe the request

At work, we extensively use flake8 and benefit from it. Great job. We'd like to support the ongoing development financially, but could not figure out a way to do so, but it seems it's handled on a per repo basis in PyCQA. Would you consider giving your user this option, e.g. through GitHub Sponsors or Tidelift?

**Comment by sigmavirus24** [comment]
I think @asottile could configure this for themselves if they wanted to. I can't receive additional money here as part of my employment contract

**Comment by asottile** [comment]
I guess I can throw my sponsors profile in a FUNDING.yml -- will reference this issue as well

it looks like `flake8` is also eligible for tidelift, idk if we'd want to do that as well

**Comment by asottile** [comment]
had to click the checkmark in settings -- should be live now
