### ISSUE TITLE
Configuration files are silently ignored

### ISSUE THREAD

**Issue by dHannasch** [PyCQA/flake8#1704]
### how did you install flake8?

```console
pip install flake8
Collecting flake8
  Downloading flake8-5.0.4-py2.py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 9.4 MB/s eta 0:00:00
Collecting mccabe<0.8.0,>=0.7.0
  Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting pyflakes<2.6.0,>=2.5.0
  Downloading pyflakes-2.5.0-py2.py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.1/66.1 kB 21.3 MB/s eta 0:00:00
Collecting pycodestyle<2.10.0,>=2.9.0
  Downloading pycodestyle-2.9.1-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.5/41.5 kB 11.7 MB/s eta 0:00:00
Installing collected packages: pyflakes, pycodestyle, mccabe, flake8
Successfully installed flake8-5.0.4 mccabe-0.7.0 pycodestyle-2.9.1 pyflakes-2.5.0
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.7",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}
```

### describe the problem

Configuration files can be silently ignored: https://github.com/dHannasch/test-flake8

(To be specific, if setup.cfg is present, then .flake8 is ignored, as shown in the linked minimal example. This is particularly surprising since you would expect the priority order to go the other way. Needless to say, the priority order is not mentioned by https://flake8.pycqa.org/en/latest/user/configuration.html; I'm speculating that it wasn't deliberate, but rather a happenstance artifact of the order that the file names happened to get typed into https://github.com/PyCQA/flake8/blob/main/src/flake8/options/config.py#L31.)

#### what I expected to happen

I expected that when a .flake8 file was provided, flake8 would either read it or fail with an error. (Or do anything, really, except for silently ignoring it.)

Needless to say, silently ignoring anything is pretty much guaranteed to be unexpected behavior.

The most obvious alternative is to just allow flake8 to read multiple configuration files (and perhaps emit a warning on duplicate keys, though silently ignoring duplicate keys would still be an improvement over silently ignoring entire files).

This is a straightforward change to https://github.com/PyCQA/flake8/blob/main/src/flake8/options/config.py, with the only caveat being that https://github.com/PyCQA/flake8/blob/main/src/flake8/options/config.py currently has a lot of things intermingled, so even a logically trivial change *looks* like a big complicated change. We could refactor https://github.com/PyCQA/flake8/blob/main/src/flake8/options/config.py to allow separation of concerns first, and then this change would be much more readable. But I'm happy with however you like doing things. (It looks like you don't like https://github.com/PyCQA/flake8/pull/1703, so I can put everything together if that would be better.) (As a bonus, a bit of reorganization might also help to prevent future problems like https://github.com/PyCQA/flake8/issues/1617. Obviously https://github.com/PyCQA/flake8/pull/1618 has handily fixed that particular problem, but it might not have happened in the first place if the different bits of code were separated.)

If, for whatever reason, you specifically don't want to allow this, then we can also fail with an error if an invalid configuration is provided. (That's a perfectly legitimate choice, the real problem is only the "silently" part.) It just so happens that it looks straightforward to handle the provided configuration as the user intended.

#### sample code

https://github.com/dHannasch/test-flake8

#### commands ran

```console
$ flake8 main.py
```

**Comment by sigmavirus24** [comment]
Definitely we won't read both. We deliberately changed away from that. The docs could be updated to mention the order if precedence

**Comment by dHannasch** [comment]
Okay. I can make it emit an error, then.

Just curious, why did you change away from that?

**Comment by asottile** [comment]
because people were very confused why settings they were changing were not taking affect because they were being overridden by another file

note that this isn't exactly "silent" as you can use `--verbose`

**Comment by dHannasch** [comment]
> because people were very confused why settings they were changing were not taking affect because they were being overridden by another file

That makes sense. Like I mentioned, we could still read multiple files and emit an error only if the configuration settings actually do conflict.

**Comment by dHannasch** [comment]
> note that this isn't exactly "silent" as you can use `--verbose`

I don't understand this. Can you clarify what you mean?

The output from `--verbose` looks like this:
```
$ flake8 main.py --verbose
flake8.checker            MainProcess    111 INFO     Making checkers
flake8.checker            MainProcess    112 INFO     Checking 1 files
flake8.main.application   MainProcess    120 INFO     Finished running
flake8.main.application   MainProcess    120 INFO     Reporting errors
flake8.main.application   MainProcess    120 INFO     Found a total of 2 violations and reported 1
```
As far as I can tell, `--verbose` or no `--verbose` is completely irrelevant, since none of the output from `--verbose` even remotely implies that the configuration is invalid. Nothing in https://github.com/PyCQA/flake8/blob/main/src/flake8/options/config.py#L31 looks like it could possibly take notice of this error condition, either.

**Comment by asottile** [comment]
it's additive, try more

**Comment by dHannasch** [comment]
> it's additive, try more --verbose

```
$ flake8 main.py --verbose --verbose --verbose --verbose
flake8                    MainProcess     82 DEBUG    Added a None logging handler to logger root at flake8
flake8.options.manager    MainProcess    115 DEBUG    Registered option "Option(-q, --quiet, action='count', default=0, help='Report only file names, or nothing. This option is repeatable.')".
flake8.options.manager    MainProcess    115 DEBUG    Registered option "Option(--color, default='auto', choices=('auto', 'always', 'never'), help='Whether to use color in output.  Defaults to `%(default)s`.')".
flake8.options.manager    MainProcess    115 DEBUG    Registered option "Option(--count, action='store_true', help='Print total number of errors to standard output and set the exit code to 1 if total is not empty.')".
flake8.options.manager    MainProcess    115 DEBUG    Registered option "Option(--diff, action='store_true', help='(DEPRECATED) Report changes only within line number ranges in the unified diff provided on standard in by the user.')".
flake8.options.manager    MainProcess    116 DEBUG    Registered option "Option(--exclude, default='.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.nox,.eggs,*.egg', type=functools.partial(<function _flake8_normalize at 0x7fc[47](https://github.com/dHannasch/test-flake8/actions/runs/3170391134/jobs/5162942894#step:4:48)534fe20>, comma_separated_list=True, normalize_paths=True), help='Comma-separated list of files or directories to exclude. (Default: %(default)s)', metavar='patterns')".
flake8.options.manager    MainProcess    116 DEBUG    Registered option "Option(--extend-exclude, default='', type=functools.partial(<function _flake8_normalize at 0x7fc47534fe20>, comma_separated_list=True, normalize_paths=True), help='Comma-separated list of files or directories to add to the list of excluded ones.', metavar='patterns')".
flake8.options.manager    MainProcess    116 DEBUG    Registered option "Option(--filename, default='*.py', type=functools.partial(<function _flake8_normalize at 0x7fc47534fe20>, comma_separated_list=True, normalize_paths=False), help='Only check for filenames matching the patterns in this comma-separated list. (Default: %(default)s)', metavar='patterns')".
flake8.options.manager    MainProcess    116 DEBUG    Registered option "Option(--stdin-display-name, default='stdin', help='The name used when reporting errors from code passed via stdin. This is useful for editors piping the file contents to flake8. (Default: %(default)s)')".
flake8.options.manager    MainProcess    116 DEBUG    Registered option "Option(--format, default='default', help='Format errors according to the chosen formatter.', metavar='format')".
flake8.options.manager    MainProcess    116 DEBUG    Registered option "Option(--hang-closing, action='store_true', help="Hang closing bracket instead of matching indentation of opening bracket's line.")".
flake8.options.manager    MainProcess    116 DEBUG    Registered option "Option(--ignore, type=functools.partial(<function _flake8_normalize at 0x7fc47534fe20>, comma_separated_list=True, normalize_paths=False), help='Comma-separated list of error codes to ignore (or skip). For example, ``--ignore=E4,E51,W234``. (Default: E121,E123,E126,E226,E24,E704,W[50](https://github.com/dHannasch/test-flake8/actions/runs/3170391134/jobs/5162942894#step:4:51)3,W504)', metavar='errors')".
flake8.options.manager    MainProcess    117 DEBUG    Registered option "Option(--extend-ignore, type=functools.partial(<function _flake8_normalize at 0x7fc47534fe20>, comma_separated_list=True, normalize_paths=False), help='Comma-separated list of error codes to add to the list of ignored ones. For example, ``--extend-ignore=E4,E[51](https://github.com/dHannasch/test-flake8/actions/runs/3170391134/jobs/5162942894#step:4:52),W234``.', metavar='errors')".
flake8.options.manager    MainProcess    117 DEBUG    Registered option "Option(--per-file-ignores, default='', help='A pairing of filenames and violation codes that defines which violations to ignore in a particular file. The filenames can be specified in a manner similar to the ``--exclude`` option and the violations work similarly to the ``--ignore`` and ``--select`` options.')".
flake8.options.manager    MainProcess    117 DEBUG    Registered option "Option(--max-line-length, default=79, type=<class 'int'>, help='Maximum allowed line length for the entirety of this run. (Default: %(default)s)', metavar='n')".
flake8.options.manager    MainProcess    117 DEBUG    Registered option "Option(--max-doc-length, default=None, type=<class 'int'>, help='Maximum allowed doc line length for the entirety of this run. (Default: %(default)s)', metavar='n')".
flake8.options.manager    MainProcess    117 DEBUG    Registered option "Option(--indent-size, default=4, type=<class 'int'>, help='Number of spaces used for indentation (Default: %(default)s)', metavar='n')".
flake8.options.manager    MainProcess    117 DEBUG    Registered option "Option(--select, type=functools.partial(<function _flake8_normalize at 0x7fc47[53](https://github.com/dHannasch/test-flake8/actions/runs/3170391134/jobs/5162942894#step:4:54)4fe20>, comma_separated_list=True, normalize_paths=False), help='Comma-separated list of error codes to enable. For example, ``--select=E4,E51,W234``. (Default: E,F,W,C90)', metavar='errors')".
flake8.options.manager    MainProcess    117 DEBUG    Registered option "Option(--extend-select, type=functools.partial(<function _flake8_normalize at 0x7fc47534fe20>, comma_separated_list=True, normalize_paths=False), help='Comma-separated list of error codes to add to the list of selected ones. For example, ``--extend-select=E4,E51,W234``.', metavar='errors')".
flake8.options.manager    MainProcess    117 DEBUG    Registered option "Option(--disable-noqa, action='store_true', default=False, help='Disable the effect of "# noqa". This will report errors on lines with "# noqa" at the end.')".
flake8.options.manager    MainProcess    118 DEBUG    Registered option "Option(--show-source, action='store_true', help='Show the source generate each error or warning.')".
flake8.options.manager    MainProcess    118 DEBUG    Registered option "Option(--no-show-source, action='store_false', dest='show_source', help='Negate --show-source')".
flake8.options.manager    MainProcess    118 DEBUG    Registered option "Option(--statistics, action='store_true', help='Count errors.')".
flake8.options.manager    MainProcess    118 DEBUG    Registered option "Option(--exit-zero, action='store_true', help='Exit with status code "0" even if there are errors.')".
flake8.options.manager    MainProcess    118 DEBUG    Registered option "Option(-j, --jobs, default='auto', type=<class 'flake8.main.options.JobsArgument'>, help='Number of subprocesses to use to run checks in parallel. This is ignored on Windows. The default, "auto", will auto-detect the number of processors available to use. (Default: %(default)s)')".
flake8.options.manager    MainProcess    118 DEBUG    Registered option "Option(--tee, action='store_true', default=False, help='Write to stdout and output-file.')".
flake8.options.manager    MainProcess    118 DEBUG    Registered option "Option(--benchmark, action='store_true', default=False, help='Print benchmark information about this run of Flake8')".
flake8.options.manager    MainProcess    118 DEBUG    Registered option "Option(--bug-report, action='store_true', help='Print information necessary when preparing a bug report')".
flake8.options.manager    MainProcess    119 DEBUG    Registered option "Option(--max-complexity, action='store', default=-1, type=<class 'int'>, help='McCabe complexity threshold')".
flake8.options.manager    MainProcess    119 DEBUG    Extending default select list with ['C90']
flake8.options.manager    MainProcess    119 DEBUG    Registered option "Option(--builtins, type=functools.partial(<function _flake8_normalize at 0x7fc47534fe20>, comma_separated_list=True, normalize_paths=False), help='define more built-ins, comma separated')".
flake8.options.manager    MainProcess    119 DEBUG    Registered option "Option(--doctests, action='store_true', default=False, help='also check syntax of the doctests')".
flake8.options.manager    MainProcess    119 DEBUG    Registered option "Option(--include-in-doctest, default='', type=functools.partial(<function _flake8_normalize at 0x7fc4[75](https://github.com/dHannasch/test-flake8/actions/runs/3170391134/jobs/5162942894#step:4:76)34fe20>, comma_separated_list=True, normalize_paths=True), dest='include_in_doctest', help='Run doctests only on these files')".
flake8.options.manager    MainProcess    119 DEBUG    Registered option "Option(--exclude-from-doctest, default='', type=functools.partial(<function _flake8_normalize at 0x7fc47534fe20>, comma_separated_list=True, normalize_paths=True), dest='exclude_from_doctest', help='Skip these files when running doctests')".
flake8.options.manager    MainProcess    120 DEBUG    Extending default select list with ['F']
flake8.options.manager    MainProcess    120 DEBUG    Extending default select list with ['E']
flake8.options.manager    MainProcess    120 DEBUG    Extending default select list with ['W']
flake8.options.config     MainProcess    120 DEBUG    Option "max-line-length" returned value: 140
flake8.options.aggregator MainProcess    120 DEBUG    Overriding default value of ([79](https://github.com/dHannasch/test-flake8/actions/runs/3170391134/jobs/5162942894#step:4:80)) for "max_line_length" with (140)
flake8.checker            MainProcess    120 INFO     Making checkers
flake8.discover_files     MainProcess    121 DEBUG    "/home/runner/work/test-flake8/test-flake8/main.py" has not been excluded
flake8.checker            MainProcess    122 INFO     Checking 1 files
flake8.checker            MainProcess    128 DEBUG    Logical line: "import os"
flake8.checker            MainProcess    128 DEBUG    Logical line: "import requests"
flake8.checker            MainProcess    128 DEBUG    Logical line: "def main():"
flake8.checker            MainProcess    129 DEBUG    Logical line: "my_input = os.environ["xxxxxxxxxxxxx"]"
flake8.checker            MainProcess    129 DEBUG    Logical line: "my_output = f"xxxxxxxxxxxxxxxx""
flake8.checker            MainProcess    129 DEBUG    Logical line: "print(f"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")"
flake8.checker            MainProcess    130 DEBUG    Logical line: "def E111():"
flake8.checker            MainProcess    130 DEBUG    Logical line: "pass"
flake8.checker            MainProcess    130 DEBUG    Logical line: ""
flake8.checker            MainProcess    130 DEBUG    Logical line: "if __name__ == "xxxxxxxx":"
flake8.checker            MainProcess    131 DEBUG    Logical line: "main()"
flake8.main.application   MainProcess    131 INFO     Finished running
flake8.main.application   MainProcess    131 INFO     Reporting errors
flake8.style_guide        MainProcess    131 DEBUG    The user configured 'F401' to be <Selected.Implicitly: 'implicitly selected'>, <Selected.Implicitly: 'implicitly selected'>
flake8.style_guide        MainProcess    131 DEBUG    "F401" will be "Decision.Selected"
flake8.violation          MainProcess    131 DEBUG    Violation(code='F401', filename='main.py', line_number=2, column_number=1, text="'requests' imported but unused", physical_line='import requests  # noqa We are just importing this to prove the dependency installed correctly\n') is ignored by a blanket ``# noqa``
flake8.style_guide        MainProcess    131 DEBUG    The user configured 'E111' to be <Selected.Implicitly: 'implicitly selected'>, <Selected.Implicitly: 'implicitly selected'>
flake8.style_guide        MainProcess    131 DEBUG    "E111" will be "Decision.Selected"
flake8.violation          MainProcess    131 DEBUG    Violation(code='E111', filename='main.py', line_number=14, column_number=3, text='indentation is not a multiple of 4', physical_line='  pass\n') is not inline ignored
flake8.main.application   MainProcess    132 INFO     Found a total of 2 violations and reported 1
```
(You can see this in operation at https://github.com/dHannasch/test-flake8.)
`--verbose --verbose` outputs quite a bit, but does not indicate that the configuration is invalid. It would be surprising if it did, because https://github.com/PyCQA/flake8/blob/main/src/flake8/options/config.py#L31 does not appear to have any ability to notice this error condition.

**Comment by asottile** [comment]
it doesn't of course, but it does show you your loaded configuration

**Comment by dHannasch** [comment]
It certainly shows that the configuration loaded is not as expected, but of course that's obvious anyway; that's the entire problem in the first place. What it doesn't show is *why* the loaded configuration is not as expected.

It doesn't show that the configuration itself is invalid. Instead it silently ignores the error, no?

That's why I'm suggesting that flake8 should emit an error in this case. (Or alternatively, just allow multiple files and only emit an error if they conflict.)

If the problem is speed, I can use tricks to make it faster. (Though it also seems worth noting that flake8 actually did read multiple configuration files before, and as you noted, people were confused by settings being overridden, but *speed* was apparently not a problem.)

**Comment by asottile** [comment]
I'm not sure why you're being persistent about this. the behavior is not changing. only reading 1 instead of mistakenly overriding was a conscious decision and eliminated an extremely surprising experience. even before 5.x it did not recurse when finding the configuration

if you want to improve the docs if you believe they're not clear than by all means please do. but I am not going to continue this discussion otherwise

**Comment by dHannasch** [comment]
> the behavior is not changing. only reading 1 instead of mistakenly overriding was a conscious decision

Sorry, can you clarify whether you're referring to emitting an error, or only to parsing multiple configuration files?

I mentioned parsing multiple configuration files only as an aside, it's perhaps a distraction.

**Comment by sigmavirus24** [comment]
> If not emitting an error when the config is invalid is a conscious decision, then...okay?

Neither file is invalid configuration from what I saw in the repo you linked. There's no reason for an error.

**Comment by dHannasch** [comment]
> Neither file is invalid configuration from what I saw in the repo you linked. There's no reason for an error.

It is certainly true that both configuration files in https://github.com/dHannasch/test-flake8 are individually valid. But isn't the overall configuration invalid? Maybe the word 'valid' is making me unclear. The point is that *there's something wrong with the configuration in the repo*. Because there is, right? If you, the human you, looked at this repo, you'd say "Your repo is wrong", wouldn't you?

> there is no error that's helpful

The error that would be helpful is "Your configuration is wrong" or "ERROR: Multiple config files found" or better yet "ERROR: [flake8] found in both /path/to/.flake8 and /path/to/setup.cfg."

Because that's what you, the human, would say to somebody who did in fact show you this repo. I mean, right? Valid or invalid, if it's *wrong* --- which it is --- then isn't that what you, the human, would in fact say?

> The why is in the logs you posted. We found valid configuration and stopped looking for more.

I don't understand this at all.

I'm re-reading the logs and they don't mention in any way that it found a valid configuration and stopped looking for more. They don't even say which file it's reading.

> To be clear you've taken a stance of either something is 'invalid' or it must be that we read both and produce an error message.

To be clear, *I am in no way saying that we need to read both*. As I said above, I only mentioned the option of reading both in passing, and clearly that was a mistake. The actual thing is just failing with an error if the repo is wrong. Preferably with an error message communicating the same thing that you would in fact say if someone came to you and you saw that they were configuring flake8 wrong.

**Comment by sigmavirus24** [comment]
Why do you insist that finding valid configuration in one of the known and accepted configuration files locations should result in an error if we don't even check the other locations?

If you had asked me, I wouldn't say you had erred. I'd say you were duplicating configuration and creating confusion for yourself in the future trying to use two files. Neither of those is a reason to make the tool slower or break it's behavior for people who aren't having problems.

You got a poorly documented edge case. That doesn't require breaking things for others. It doesn't require degrading 100% of users' experience to improve 1% or fewer of users' experience.

I get that you seem frustrated by this but you seen to be ignoring our explanation of the trade-offs that make your solution undesirable

**Comment by asottile** [comment]
I surveyed some other tools as well, none of them work like you're asking:

```console
$ tail -n999 pyproject.toml  pytest.ini 
==> pyproject.toml <==
[tool.pytest.ini_options]
addopts = ["--wat2"]

==> pytest.ini <==
[pytest]
addopts = -q
$ pytest t.py

no tests ran in 0.00s
```

```console
$ tail -n999 .pylintrc pyproject.toml 
==> .pylintrc <==
[MAIN]
fail-under=0

==> pyproject.toml <==
[tool.pylint.main]
fail-under = 10.0

jobs = "wat"
$ pylint t.py 
************* Module t
t.py:2:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
t.py:3:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
t.py:1:0: C0114: Missing module docstring (missing-module-docstring)
t.py:1:8: C0103: Argument name "a" doesn't conform to snake_case naming style (invalid-name)
t.py:1:10: C0103: Argument name "b" doesn't conform to snake_case naming style (invalid-name)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

```console
$ tail -n999 setup.cfg tox.ini 
==> setup.cfg <==
[tox:testenv:wat]
commands = python -c 'print("hi")'

==> tox.ini <==
[testenv:wat2]
commands = python -c 'print("hi")'
$ tox -e wat
ERROR: unknown environment 'wat'
$ tox -e wat2
ERROR: pyproject.toml file found.
To use a PEP 517 build-backend you are required to configure tox to use an isolated_build:
https://tox.readthedocs.io/en/latest/example/package.html
```

also **you tried to sneak this in under false pretenses** -- you created [this blank issue](https://github.com/PyCQA/flake8/issues/1702) which looks like spam and then you made this PR which completely hides that you're trying to change the behaviour https://github.com/PyCQA/flake8/pull/1703 -- fortunately I closed it because it also looked like spam

**Comment by dHannasch** [comment]
> **you tried to sneak this in under false pretenses** -- you created [this blank issue](https://github.com/PyCQA/flake8/issues/1702) which looks like spam and then you made this PR which completely hides that you're trying to change the behaviour #1703 -- fortunately I closed it because it also looked like spam

It is utterly false that I tried to sneak anything in under false pretenses.

https://github.com/PyCQA/flake8/pull/1703 did not and does not change *any* behavior of any kind. It did exactly, precisely what it said it did. It simply extracted the behavior of walking up the directories into a separate function to make it easier to document, and documented it. That seemed useful regardless of any change in behavior. The point *was* of course to make it easier to later change the behavior of https://github.com/PyCQA/flake8/blob/main/src/flake8/options/config.py in *any number of ways*; that is, as always, the point of refactoring. In particular, it could have made this change easier. But it was not strictly related.

I mentioned that at the top of this issue:

> We could refactor https://github.com/PyCQA/flake8/blob/main/src/flake8/options/config.py to allow separation of concerns first, and then this change would be much more readable. But I'm happy with however you like doing things. (It looks like you don't like https://github.com/PyCQA/flake8/pull/1703, so I can put everything together if that would be better.) (As a bonus, a bit of reorganization might also help to prevent future problems like https://github.com/PyCQA/flake8/issues/1617. Obviously https://github.com/PyCQA/flake8/pull/1618 has handily fixed that particular problem, but it might not have happened in the first place if the different bits of code were separated.)

It *is* true that I misclicked and created https://github.com/PyCQA/flake8/issues/1702 blank. That's my mistake, and I'm sorry to have cluttered your inbox with that. Naturally, I noticed my mistake and tried to correct it by editing the issue. However, as you know, you locked that issue within 90 seconds, so you were faster and I was unable to correct my mistake. Again, I'm sorry I accidentally clicked to create the issue without the description. If I *had* had the chance to fix the issue description, what it was supposed to be was solely about giving a PEP-0257 docstring to the behavior of walking up the directories, now that https://github.com/PyCQA/flake8/pull/1618 has made that not-completely-trivial. Since you commented on the pull request that you specifically didn't want a pull request that didn't change any behavior (https://github.com/PyCQA/flake8/pull/1703#issuecomment-1264729268), I naturally shrugged and abandoned it, and only mentioned it at the top of this issue.

**Comment by Dreamsorcerer** [comment]
> because people were very confused why settings they were changing were not taking affect because they were being overridden by another file

FYI, this is exactly the reason that lead me to this issue. After upgrading flake8, no changes to our setting were taking effect, because the `.flake8` file was no being ignored.

Seems that many of repos I've taken over maintaining *appeared* as if flake8 had never been used on the project, so I set up flake8 using the `.flake8` file. But, after finding this bug report I'm now discovering that many of them had a 2 line config in `setup.cfg` that I was unaware of.

As mentioned, checking for other configs and producing an error would have helped avoid the same situation you were trying to fix from happening again. Whether it's worth the performance tradeoff is up to you, but I assume checking for other files is <1 second, compared to the >30 mins it took me to figure out why nothing was working correctly.

**Comment by asottile** [comment]
please read the discussion that's already happened here -- as above, we're not going to do this and no other tool does that either
