### ISSUE TITLE
Allow setting maximum complexity per method

### ISSUE THREAD

**Issue by sharkwouter** [PyCQA/flake8#1709]
### describe the request

I've been using flake8 for checking complexity of methods. I now set the max complexity to 6, which mostly results in more readable code, but I did find there are some exceptions. Now it's easy to exclude one method from the complexity check, but I would prefer to have a different max complexity just for this method instead. That way it won't go up further without anyone noticing.

I'm not sure what an implementation for this would look like, though. If I had an idea, I could give it a shot.

Perhaps something like `# max-complexity: 7` could work. Right now `# noqa: C901` is the only option.

**Comment by asottile** [comment]
![image](https://user-images.githubusercontent.com/1810591/194432478-f316e9bb-d1ce-4a6a-acd6-d1b872d758ee.png)
