### ISSUE TITLE
Bug marked as invalid with no explanation

### ISSUE THREAD

**Issue by staticdev** [PyCQA/flake8#1712]
### how did you install flake8?

```console
poetry
```

### unmodified output of `flake8 --bug-report`

```json
-
```

### describe the problem

I created this issue #1711 that was marked as invalid by @asottile. Can you please elaborate on why? I have 2 points I think it is valid.

1. importlib_metadata 5.0 introduces this backward incompatible changes
https://github.com/python/importlib_metadata/issues/409
1. flake8 config forces use of <4.3: https://github.com/PyCQA/flake8/blob/main/setup.cfg#L44

I just want a bit of consideration since I took the effort to write in the project and I am a strong advocate of flake8 for years.

**Comment by asottile** [comment]
I understand but you're not doing the charitable thing and researching where this has [already been discussed multiple times and that there's nothing that can be done](https://github.com/PyCQA/flake8/issues?q=is%3Aissue+importlib+metadata+is%3Aclosed)

please don't open another issue and please understand we've already put in a lot of work to solve this and there's nothing we can do and when we drop python3.7 we won't even use importlib-metadata (maybe your solution is to just ignore python3.7 as well)
