### ISSUE TITLE
bump `importlib_metadata` version

### ISSUE THREAD

**Issue by nnrepos** [PyCQA/flake8#1714]
### describe the request

since flake8 issues only begin when using `importlib_metadata>=5.0.0`, i think it would be better to bump `setup.cfg` to the latest supported version: `importlib_metadata<5`.
if you're interested, please assign me, thanks 😄

**Comment by asottile** [comment]
please search the issue tracker as the template asks you to do -- there are many duplicates about why we are not doing this

**Comment by asottile** [comment]
also you're almost certainly using a version of flake8 which is not supported
