### ISSUE TITLE
noqa behavior differs between flake8 and pycodestyle

### ISSUE THREAD

**Issue by DominikVollandTNG** [PyCQA/flake8#1719]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.12",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}
```

#### what I expected to happen

A single `noqa: E131` in the first line of a multi-line statement disables the check for the entire statement.

#### sample code

```python
example = (  # noqa: E131
    "this"
        "is"
            "an"
        "example"
            "for"
        "my"
    "issue"
)
```

#### commands ran

```console
$ flake8 test.py
# Output:
# test.py:3:9: E131 continuation line unaligned for hanging indent
# test.py:4:13: E131 continuation line unaligned for hanging indent
$ pycodestyle test.py
# No output
```

Is this behavior intendend? pycodestyle behaves as I expected, flake8 does not.
The comments on the accepted answer for [this Stackoverflow question](https://stackoverflow.com/questions/46795404/how-can-i-disable-flake8-for-a-multiline-import) seem to be related to this.

Thanks in advance for the help!

**Comment by asottile** [comment]
yes -- for flake8 the noqa comment must appear on the line containing the error -- or in the case of backslash / triple-quoted-strings it must appear on the final line

**Comment by DominikVollandTNG** [comment]
Thanks a lot for the quick response. Unfortunately, in the above example, a single noqa in the final line doesn't suppress the error either. But I will find a different solution.

**Comment by asottile** [comment]
I didn't say it should -- read my message again

also note that pycodestyle doesn't support the syntax you're using `# noqa: ABC123` -- pycodestyle sees that as a blanket `# noqa`
