### ISSUE TITLE
--append-config: should error if file does not exist

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#1729]
### describe the request

similar to #1498 -- this should also error for `--append-config`

```console
$ flake8 --config does-not-exist setup.py; echo $?
There was a critical error during execution of Flake8:
The specified config file does not exist: does-not-exist
1
$ flake8 --append-config does-not-exist setup.py; echo $?
0
```

**Comment by LeetaoGoooo** [comment]
https://github.com/PyCQA/flake8/blob/ff8988bd586a4af192390e4316772333f34ba1e5/src/flake8/options/config.py#L89

Just raise an ExecutionError?

**Comment by asottile** [comment]
yep, this should be very easy

**Comment by LeetaoGoooo** [comment]
> yep, this should be very easy

i saw there was a todo 

https://github.com/PyCQA/flake8/blob/ff8988bd586a4af192390e4316772333f34ba1e5/src/flake8/options/config.py#L86

should we fix it ,meanwhile refactor the code?

**Comment by asottile** [comment]
that todo is not simple to fix

**Comment by LeetaoGoooo** [comment]
> that todo is not simple to fix

ok 😂 let me fix the simple one, i'll make a pr later
