### ISSUE TITLE
Flake8 passes with syntactically incorrect Python

### ISSUE THREAD

**Issue by unode** [PyCQA/flake8#1735]
### describe the request

Using Flake8 version:
```
5.0.4 (mccabe: 0.7.0, pycodestyle: 2.9.1, pyflakes: 2.5.0) CPython 3.10.7 on Linux
```

The following code **passes** flake8 linting:
```
def function(test=1):
    def func():
        return test

    return func


@function(
    test=2,
    test=3,
)
def this():
    pass
```

But executing in Python 3.9 gives:
```
% python func.py 
  File "func.py", line 8
    @function(
        ^
SyntaxError: keyword argument repeated: test
```

and in Python 3.10:

```
% python func.py  
  File "func.py", line 10
    test=3,
    ^^^^^^
SyntaxError: keyword argument repeated: test
```

In this case Flake8 should either fail with a specific error code or abort due to invalid source code.

**Comment by asottile** [comment]
this is one of those "late" syntax errors which only happens at code generation time and not at ast parse

for those, pyflakes usually implements an error (I believe there's already an issue for this specific one there)
