### ISSUE TITLE
Gitlab mirror was deleted?

### ISSUE THREAD

**Issue by blackliner** [PyCQA/flake8#1737]
Hi, getting fails on our CI, saw [gitlab.com/pycqa/flake8](https://gitlab.com/pycqa/flake8) does not exist anymore. Was this intentional?

**Comment by sigmavirus24** [comment]
Yes. It hasn't been the active development location for years at this point, wasn't actively being mirrored or monitored for integrity and regularly causes confusion.

**Comment by RedTachyon** [comment]
Might be worth putting up an announcement somewhere, even in the readme. There's a huge number of CI pipelines which still used the gitlab miror for whatever reason, so it's likely that people will keep streaming in and making issues without checking the closed ones.

**Comment by asottile** [comment]
I'll just pin this
