### ISSUE TITLE
Inline comments incorrectly handled in setup.cfg

### ISSUE THREAD

**Issue by olliemath** [PyCQA/flake8#1745]
### how did you install flake8?

```console
(venv) $ pip install flake8
Collecting flake8
  Using cached flake8-5.0.4-py2.py3-none-any.whl (61 kB)
Collecting pycodestyle<2.10.0,>=2.9.0
  Using cached pycodestyle-2.9.1-py2.py3-none-any.whl (41 kB)
Collecting mccabe<0.8.0,>=0.7.0
  Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting pyflakes<2.6.0,>=2.5.0
  Using cached pyflakes-2.5.0-py2.py3-none-any.whl (66 kB)
Installing collected packages: pycodestyle, mccabe, pyflakes, flake8
Successfully installed flake8-5.0.4 mccabe-0.7.0 pycodestyle-2.9.1 pyflakes-2.5.0
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.10",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.4"
}
```

#### what I expected to happen

When creating a setup.cfg, I added a comment following an item in the ignores section. That comment contained a valid error code (in this case `E501`, but any code will do).

Expected behaviour: flake8 ignores all text following a `#` character on the same line (as per https://docs.python.org/3/distutils/configfile.html)

Actual behaviour: flake8 disables the error code which is included in the comment

#### sample code

Here's a minimal reproducer - this python file:

```python
import some_unused_import

"this is a vey loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong line"
```

along with this setup.cfg:

```setup.cfg
[flake8]
select =
    E, W, F
ignore =
    # some comment about F401
    W503, W504  # some comment about E501
```

should give two errors, an F401 and an E501, but only gives the F401. 

#### commands ran

```console
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install flake8
$ flake8 example.py
```

**Comment by asottile** [comment]
please [read the docs](https://flake8.pycqa.org/en/latest/user/configuration.html) or search the issue tracker next time (there are several duplicates) -- thanks!
