### ISSUE TITLE
flake8 v6 "broke" config file management

### ISSUE THREAD

**Issue by jesusch** [PyCQA/flake8#1757]
### how did you install flake8?

```console
pip install -U flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.13",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.10.0"
    },
    {
      "plugin": "pyflakes",
      "version": "3.0.0"
    }
  ],
  "version": "6.0.0"
}
```

#### what I expected to happen

Unitil now I used to write my `.flake8` file like this:

```
[flake8]
ignore =
    W,    # all warnings
    C901, # 'process' is too complex
    E1,   # some indention foo
    E2,   # whitespace foo
    E301, # expected 1 blank line, found 0
    E302, # expected x blank lines, found y
    E303, # too many blank lines
```

Since 6.0.0 (https://github.com/PyCQA/flake8/commit/1346ddefd315223b8f476bb02381a944e14f2cbc) a regex is used to verify a VALID_CODE_PREFIX which breaks above syntax

I'm not 100% sure about INI syntax if my syntax should be allowed, but the regex could be modified to support it?

**Comment by jaap3** [comment]
I also ran into this, but it appears this breakage is intentional. Check #1689 for more details.

**Comment by jesusch** [comment]
duplicates #1689
