### ISSUE TITLE
Mapping error codes to severities

### ISSUE THREAD

**Issue by WhyNotHugo** [PyCQA/flake8#1762]
### describe the request

IDEs and other developer tools usually handle diagnostics in multiple severities (the most common approach being Error, Warning, Info, Hint).

flake8 errors have no concept of severity, so when an IDE shows flake8 violations, there's no _correct_ severity. Because of this, [IDEs and/or their helpers have been instructed to  them as Error](https://github.com/PyCQA/flake8/issues/1467#issuecomment-1036510468).

This isn't helpful when trying to find an error in code. A scenarios I've faced many times, in trying to find what's the breakage in a file with many diagnostics: most of them being mere linting (e.g.: trailing whitespace), and one of them is a `SyntaxError`. Clearly, some of these are just `Info` and the latter is an `Error`. One _should_ stand out more than others. There's an intrinsic order of severity in these.

However, downstream integrations and tools have no reference for this, and an upstream one would seem best. Mostly, all IDEs/plugins/etc would be able to re-use the same definitions and stay consistent.

I'd like to propose some form of mapping from error codes to one of the severalties above. Aside from somehow surfacing these for each existing error code, we'd need some mechanism for flake8 plugin authors to do the same for the error codes that they emit.

**Comment by asottile** [comment]
how did you bypass the moderation limits?

**Comment by asottile** [comment]
this seems unmanageable, and I'd argue things shouldn't report anything not actionable

**Comment by asottile** [comment]
I don't think managing this in the framework or inside plugins makes sense.  it's really up to the _user_ to decide what severity they'd assign to various codes (for instance I might put "unused import" at error, but someone else might not care and put it at info or ignore it entirely).  to flake8 they are all errors.

and at that point it's probably best that the IDE and IDE configuration presents those options to users.
