### ISSUE TITLE
Change valid code regexp

### ISSUE THREAD

**Issue by Dimitryliss1** [PyCQA/flake8#1777]
### describe the request

Current version's regular expression (defined [here](https://github.com/PyCQA/flake8/blob/main/src/flake8/defaults.py#L46)) doesn't allow us to use any linter, that uses 4-or-more digit error codes, as a plugin for Flake8 (For example, PyLint uses 4-digit codes, e.g. [here](https://pylint.pycqa.org/en/latest/user_guide/messages/messages_overview.html)).

So now this regular expression blocks us from updating to newer versions of Flake8.

Idea is to change this RE to, for example:
```
^[A-Z]{1,3}[0-9]{0,4}$
```

or even
```
^[A-Z]{1,3}[0-9]*$
```
allowing for more custom linters to be used.

**Comment by asottile** [comment]
please search the issue tracker, there are many duplicates and this is not changing
