### ISSUE TITLE
unable to set flake8-unused-arguments in config

### ISSUE THREAD

**Issue by phubaba** [PyCQA/flake8#1784]
### describe the request

i create a config like
```
[flake8]

unused-arguments-ignore-dunder
unused-arguments-ignore-stub-functions
unused-arguments-ignore-variadic-name
unused-arguments-ignore-abstract-functions
```
and I will get errors when I run 

```
configparser.ParsingError: Source contains parsing errors: '~/.config/flake8'
        [line 18]: 'unused-arguments-ignore-dunder\n'
        [line 19]: 'unused-arguments-ignore-stub-functions\n'
        [line 20]: 'unused-arguments-ignore-variadic-name\n'
        [line 21]: 'unused-arguments-ignore-abstract-functions\n'
```

If I do the following there is no error but the arguments do not get parsed.
```
[flake8]

unused-arguments-ignore-dunder = True
unused-arguments-ignore-stub-functions = True
unused-arguments-ignore-variadic-name = True
unused-arguments-ignore-abstract-functions = True
```

The only way I can get them to work is by passing via command line

`flake8  pydag democritus knossos/knossos/pydag --unused-arguments-ignore-stub-functions --unused-arguments-ignore-lambdas --unused-arguments-ignore-variadic-name --unused-arguments-ignore-abstract-functions
`

https://pypi.org/project/flake8-unused-arguments/

**Comment by asottile** [comment]
don't skip the issue template, I can't reproduce

```console
$ tail -n999 t.py  setup.cfg
==> t.py <==
import abc


class C:
    @abc.abstractmethod
    def f(self, wat):
        pass

==> setup.cfg <==
[flake8]
unused-arguments-ignore-abstract-functions = true
$ flake8 t.py
$ echo $?
0
```

**Comment by phubaba** [comment]
I figured it out you have to use these underscore names then it works
unused_arguments_ignore_dunder_methods = True
unused_arguments_ignore_stub_functions = True
unused_arguments_ignore_variadic_names = True
unused_arguments_ignore_abstract_functions = True

**Comment by asottile** [comment]
flake8 normalizes the dashes / underscores so that should not matter -- but I can only guess at your problem because you have not filled out the issue template which requires you to fill out useful information

**Comment by phubaba** [comment]
I tried to fill out the template before giving up. I will try again.
