### ISSUE TITLE
Allow configuration option to fill default doctests namespace

### ISSUE THREAD

**Issue by skirpichev** [PyCQA/flake8#1787]
The doctest module allows such things with globs option for the testfile/testmod, etc.  The pytest provides the doctest_namespace fixture.   The sphinx's doctest extension also has doctest_global_setup option.

I believe it does make sense to add some option for the flake8 to provide the doctest setup code snippet (add default imports, etc).
Not sure about naming, perhaps `--doctest-setup`?

**Comment by asottile** [comment]
please read the issue template. flake8 does not provide any checks.

**Comment by skirpichev** [comment]
@asottile, I think you misunderstood the issue: I'm not suggesting any new checkers, just an option to adjust the current `--doctests` behaviour of the flake8.  Please reconsider.

Now I realize, this feature, probably, requires a kwarg for the pyflakes.checker.Checker - PyCQA/pyflakes#763.  But this will require some support from the flake8 side (cli switch or something).

**Comment by asottile** [comment]
tbh, just use builtins.  I think doctests are a bad idea so I'm not going to invest any work in this -- it requires a change in pyflakes if you want to push for it but honestly just use builtins or write your doctests as self-contained (tbh, making them self-contained is probably better anyway -- that way your readers can just run the code rather than having to guess about what's magically globally available)

**Comment by skirpichev** [comment]
> tbh, just use builtins

This is useful only in case of few names, which can be added by hand.  But consider
```
In [2]: import diofant; len(dir(diofant))
Out[2]: 668

In [3]: import sympy; len(dir(sympy))
Out[3]: 927
```
And this is not a doctests-only option.

> write your doctests as self-contained

This does make sense for small libraries, but in the real world this will require a lot of boilerplate code (and these names are usually anyway present in interactive sessions, etc).  E.g. numpy/scipy/matplotlib add a standard setup code (like `import numpy as np`).

The flake8 - is only tool (c.f. plain doctest, pytest, sphinx), that doesn't support such a feature.

**Comment by asottile** [comment]
yeah, you're not convincing me by saying "everything else supports this" which is a very simple strawman
