### ISSUE TITLE
Add `-l / --list-files` option to print out sorted set of files with style errors/warnings

### ISSUE THREAD

**Issue by brendancol** [PyCQA/flake8#1794]
### describe the request

I might be wrong about the problem statement...

## Problem
Currently, `flake8` does not have a flag to print out only the unique file paths with style errors.

This makes it difficult to see at a glance which files need to be fixed without having to sort through all of the error messages.

## Proposed Solution
Add an `-l` flag to `flake8` that prints only the set of file paths with style errors.

It would basically implement:
```bash
flake8 . | awk '{print $1}' | awk -F: '{print $1}' | sort | uniq
```
I find myself doing this often:

```zsh
vim `flake8 . | awk '{print $1}' | awk -F: '{print $1}' | sort | uniq`
```

It would be nice to do this instead:
```zsh
vim `flake8 . -l`
```

**Comment by asottile** [comment]
`flake8 | cut -d: -f1 | sort -u` is probably what you're looking for -- or you can write your own formatter plugin for whatever you need -- flake8 itself does not need to carry this complexity
