### ISSUE TITLE
Add support for a 4 digits error codes to support plugging in pylint

### ISSUE THREAD

**Issue by Cjkjvfnby** [PyCQA/flake8#1805]
### describe the request

With version, 6.0.0 new checks to the error codes in the exclusion list were introduced.

[Here](https://github.com/PyCQA/flake8/issues/1759#issuecomment-1326556905) it described as 

> flake8 has never supported more than 3 digit codes and it was silently doing the wrong thing

Technically it was supported and was doing the things I expected, I have never noticed that something is wrong. 
The first mention in the documentation about 3 digits is in 3.6.0

Even if was a long-lasting bug, people already build something on top of that. I know that this is a plugin problem and tails should not wag the dog, but this looks like changing the contract for plugin maintainers.

What is the reason why flake8 should drop this compatibility?  If this is only a matter of resources, I could contribute to supporting this.

PS. Pylint is quite a popular tool and having the option to run it inside flake8 is quite nice. I was pretty happy that I don't need one more command line tool.

**Comment by asottile** [comment]
you already found the duplicate that says no -- don't do this
