### ISSUE TITLE
support partially qualified object access on modules

### ISSUE THREAD

**Issue by sanderr** [PyCQA/flake8#1811]
### describe the request

Sometimes I find it useful to use partially qualified names to refer to objects in another module. In some cases it is a solid middle ground between just importing the object or deepest submodule without any context, and having to be way too verbose with fully qualified names. I do have to admit that I haven't seen this being used often, but as far as I can tell [PEP8](https://peps.python.org/pep-0008/#imports) isn't opinionated about this.

An exagerated example to highlight the use case:
```python
import this.is.my.deeply.nested.meaningful_name.common_name
from this.is.my.deeply.nested import meaningful_namespace

print(meaningful_name.common_name.my_object)
# compared to very verbose
print(this.is.my.deeply.nested.meaningful_name.common_name.my_object)
# or use the common name without its context
from this.is.my.deeply.nested.meaningful_name import common_name
print(common_name.my_object)
```

An example you can actually run but that doesn't show the motivation so much (I wouldn't use it myself in this case). I picked it only because it's one of the few cases in CPython's standard library that is sufficiently nested.
```python
import concurrent.futures.thread
from concurrent import futures

print(futures.thread.ThreadPoolExecutor)
```

Invoking `flake8` on this results in `main.py:1:1: F401 'concurrent.futures.thread' imported but unused`. I would like it to be smart enough to recognize the semi-qualified access.

I made this a feature request rather than a bug report because I'm not sure how common or conventional this approach is. Would it be aligned with flake8's intent to support something like this?

**Comment by asottile** [comment]
please read the bold text and the issue prompts

**Comment by sanderr** [comment]
For bookkeeping purposes: PyCQA/pyflakes#769
