### ISSUE TITLE
Flake8 should provide a way to set fallback pyflake configuration

### ISSUE THREAD

**Issue by zhou13** [PyCQA/flake8#1816]
### describe the request

pyflake8 works wonderfully when a project provides a flake8 configuration. However, it seems that it is hard to make flake8 fallback to a default configuration when a project does not provide flake8 configuration.  AFAIW, currently there are three ways to set a default configuration in the most recent flake8:
1. place a configuration at `~/.flake8`. However, if one project provides `setup.cfg` but does not provide `flake8` configuration in it, flake8 will ignore the fallback at `~/.flake8`;
2. let you editor use `flake8 <file> --append-config ~/.config/flake8`. The main problem with this strategy is that it interferes with projects that already provide a flake8 configuration, since you append something to it;
3. let you editor use `flake8 <file> -config ~/.config/flake8`. This is similar to 2, but even worse.

I think a better strategy will be that if no config is found, flake8 should fallback to ~/.config/flake8.

**Comment by asottile** [comment]
no it should not -- this was removed because it constantly caused confusion -- if you want to select a configuration outside of your project you can do so explicitly by using the `--config` / `--append-config` / etc. options

**Comment by zhou13** [comment]
The problem with using `--config` or `--append-config` is that it is hard to integrate it with an editor: For some files, you have to specify it and for others, you cannot specify it. If providing a fallback config might cause confusion in some cases, it would be best to provide options like `--preprend-config` or `--default-config` so users can provide a fallback.

**Comment by sigmavirus24** [comment]
We're not reintroducing this or adding yet more complexity to the configuration handling. A user configuration doesn't solve your problem since two people will have different configurations. There's already a "default" config for flake8.
