### ISSUE TITLE
Option to mark error codes as externaly managed

### ISSUE THREAD

**Issue by finswimmer** [PyCQA/flake8#1819]
### describe the request

Hey,

I'm not sure if this feature request is better suited over at the `yesqa` repo.

`# noqa` is used by multiple tools beside `flake8`, e.g. `ruff`, `darglint`, `pydocstyle`. If those tools are used as stand-alone applications and not as a `flake8` plugin, `yesqa` will happily  remove `# noqa`'s from the source code.

It would be great, to have a config option, to pass a list of error codes that are externally managed, so that `yesqa` will not remove those error code.

Thanks a lot.

**Comment by sigmavirus24** [comment]
How would flake8 marking those as "externally managed" (whatever that means) help yesqa?

**Comment by finswimmer** [comment]
@sigmavirus24: This is why I was saying that I'm not sure if its better suited in the yesqa repo :)

Until now it was said, that `yesqa` have no config options, because it completely relies on the `flake8` output. If this still should be true in the future, it would be necessary that `flake8` can output a list of externally managed error codes, so that `yesqa` can ignore those codes in the source code.

Or `yesqa` must start accepting a list of codes it should ignore. This would be probably easier to implement than the former.

**Comment by asottile** [comment]
it would not help yesqa

**Comment by finswimmer** [comment]
@asottile Does this mean "This is an useful option, we should implement in yesqa directly. Please open a Feature Request over there." or does this mean "No, thanks" at all?

**Comment by asottile** [comment]
noqa is flake8's comment. other tools should not use it
