### ISSUE TITLE
flake8 does not read .flake8 until I explicitly request it via --config argument

### ISSUE THREAD

**Issue by dmitry-kabanov** [PyCQA/flake8#1825]
### how did you install flake8?

```console
$ pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.10",
    "system": "Darwin"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.10.0"
    },
    {
      "plugin": "pyflakes",
      "version": "3.0.1"
    }
  ],
  "version": "6.0.0"
}
```

#### what I expected to happen

I have `.flake8` config file in the same directory where I run `flake8`. The file looks superinnocent:
```
[flake8]
max-line-length = 88
```

If I run command
```
flake8 .
```
I get the following output:
```
./docs/conf.py:6:80: E501 line too long (80 > 79 characters)
./docs/conf.py:14:1: F401 'os' imported but unused
./docs/conf.py:15:1: F401 'sys' imported but unused
./docs/conf.py:22:80: E501 line too long (80 > 79 characters)
./docs/conf.py:27:80: E501 line too long (80 > 79 characters)
... (omitted several E501 errors)
```
which means that the config file `.flake8` is ignored.

If I explicitly request to use this config file:
```
flake8 . --config .flake8
```
I get the correct output:
```
./docs/conf.py:14:1: F401 'os' imported but unused
./docs/conf.py:15:1: F401 'sys' imported but unused
```

This means that for some unknown reason, `flake8` has stopped reading the config file by default, although it should (according to the docs).

**Comment by asottile** [comment]
try `git grep -E '\[flake8\]'`

**Comment by dmitry-kabanov** [comment]
Seriously? You closed the issue and simply suggested a grep command?

**Comment by asottile** [comment]
did you run it? it will show you why

**Comment by dmitry-kabanov** [comment]
I does not show me why actually; it is a bit of a stretch to say so.

Only by looking to the documentation and seeing this:
```
Flake8 supports storing its configuration in your project in one of setup.cfg, tox.ini, or .flake8.
```
I can somehow deduce that if the settings are found in one file, they are not checked in another one.
Indeed, in the project there is also (generated) `tox.ini`, and it seems like it take precedence.

However, as a user, I would prefer that if I run `flake8` with `-v` (verbose) argument, it would at least give this information (config in `tox.ini` found, reading it; config in `.flake8` is ignored), such that I do not have to sit and wonder what is going on.

So, imho, there is still a bug, at least on the usability level. I do not spend every day of my life configuring `flake8`, so a little bit of clarity in how it reads its config would be really helpful.

**Comment by asottile** [comment]
search the issue tracker next time for duplicates please
