### ISSUE TITLE
--color=auto should disable color on monochrome terminals

### ISSUE THREAD

**Issue by trentbuck** [PyCQA/flake8#1834]
### describe the request

This snippet doesn't check if color is supported:
https://github.com/PyCQA/flake8/blob/54f1b3e9120e5289922535835a495c7698639f67/src/flake8/formatting/base.py#L50-L54
This results in a crap experience in Emacs M-x compile:
![image](https://github.com/PyCQA/flake8/assets/64124132/0bb0d592-5ab7-47b2-8a12-8baa2d0694d4)

Please check if $TERM supports 8+ colors (`tput colors` or equivalent), or *at least* check if $TERM is not dumb.
It looks like you're already doing something equivalent for Windows users, so this should not be contentious.

In the meantime, piping flake8 into cat is enough to defeat the "stdout is a tty" test:
![image](https://github.com/PyCQA/flake8/assets/64124132/abe57322-1c27-4dac-8d37-d388baff5aa2)

**Comment by asottile** [comment]
I'd recommend not using auto for emacs, it's why there's an option -- or send a patch if you see an obvious improvement

we can't assume tput is there and the windows check is specifically for modern windows and not really related

**Comment by trentbuck** [comment]
Re "I'd recommend not using auto for emacs, it's why there's an option" -- that was my first thought, to simply disable color globally. But https://github.com/PyCQA/flake8/blob/main/docs/source/user/options.rst says I can't disable it globally - I'd have to add --color=never every time I run flake8.

Re "send a patch if you see an obvious improvement", here are three approaches I had in mind.  None of them are pull-worthy because they don't add unit test mocking stuff -- I didn't immediately understand how to do that.

https://github.com/trentbuck/flake8/commit/denylist
https://github.com/trentbuck/flake8/commit/tput
https://github.com/trentbuck/flake8/commit/curses

Personally I think the curses one is the most elegant and correct, but it needs more testing.
I would be happy with just the denylist version.
I think the tput version should be dismissed out-of-hand, but I included it just for completeness.

**Comment by asottile** [comment]
yeah I agree the tput one is untenable.  the curses one won't work either because it is not available on windows without `windows-curses` -- and even if it were available `initscr()` takes over output so you'd get a weird flicker

the denylist seems fine enough

**Comment by crabbone** [comment]
Hi. Why was this closed?

Also, why can't color be configured at all, forget globally? This is such a bizarre and a bad choice...
