### ISSUE TITLE
Two minor changes needed for current git pycodestyle and pyflakes

### ISSUE THREAD

**Issue by AdamWill** [PyCQA/flake8#1844]
### how did you install flake8?

```console
Distro package.
```

### unmodified output of `flake8 --bug-report`

```json
N/A.
```

### describe the problem

I'm filing an issue rather than submitting a PR because it feels wrong to *land* these changes until there are new releases of pycodestyle and pyflakes, but I wanted to *log* them so nobody needs to duplicate the work. Also it gives me somewhere to link to in the Fedora spec file to explain the not-yet-upstreamed patches.

Current git pycodestyle's `missing_whitespace` now takes the `tokens` argument, so `flake8/plugins/pycodestyle.py` needs a trivial change:

    diff --git a/src/flake8/plugins/pycodestyle.py b/src/flake8/plugins/pycodestyle.py
    index 7eb90e1..b2b90de 100644
    --- a/src/flake8/plugins/pycodestyle.py
    +++ b/src/flake8/plugins/pycodestyle.py
    @@ -74,7 +74,7 @@ def pycodestyle_logical(
         yield from _imports_on_separate_lines(logical_line)
         yield from _indentation(logical_line, previous_logical, indent_char, indent_level, previous_indent_level, indent_size)  # noqa: E501
         yield from _maximum_doc_length(logical_line, max_doc_length, noqa, tokens)
    -    yield from _missing_whitespace(logical_line)
    +    yield from _missing_whitespace(logical_line, tokens)
         yield from _missing_whitespace_after_keyword(logical_line, tokens)
         yield from _missing_whitespace_around_operator(logical_line, tokens)
         yield from _module_imports_on_top_of_file(logical_line, indent_level, checker_state, noqa)  # noqa: E501

also, current git pyflakes removes the `ContinueInFinally` message (in https://github.com/PyCQA/pyflakes/commit/98d4fa33ccacf74c62c5a17cc35ce572fd35b223 ), so that needs removing from the flake8 shim:

    --- a/src/flake8/plugins/pyflakes.py
    +++ b/src/flake8/plugins/pyflakes.py
    @@ -48,7 +48,6 @@ FLAKE8_PYFLAKES_CODES = {
         "IfTuple": "F634",
         "BreakOutsideLoop": "F701",
         "ContinueOutsideLoop": "F702",
    -    "ContinueInFinally": "F703",
         "YieldOutsideFunction": "F704",
         "ReturnOutsideFunction": "F706",
         "DefaultExceptNotLast": "F707",

**Comment by asottile** [comment]
I maintain all three

**Comment by asottile** [comment]
and sorry I don't support redhat for free. please fix your own bugs and don't cause me more maintenance by packaging and forcing incompatible software versions
