### ISSUE TITLE
Invalid E231 missing whitespace after ':' with Python 3.12

### ISSUE THREAD

**Issue by grische** [PyCQA/flake8#1845]
### how did you install flake8?

```console
$ python -m pip install flake8 poetry

See https://github.com/grische/extremeflash/actions/runs/5585322641/jobs/10207909510?pr=3
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.12.0b4",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.10.0"
    },
    {
      "plugin": "pyflakes",
      "version": "3.0.1"
    }
  ],
  "version": "6.0.0"
}
```

### describe the problem

See https://github.com/grische/extremeflash/actions/runs/5585322641/jobs/10207909510?pr=3

#### what I expected to happen

Only the Python 3.12 run shows this error, while Python 3.10 and Python 3.11 succeed successfully.
Expecting to also pass for Python 3.12

#### sample code
https://github.com/grische/extremeflash/blob/b8419e6bc283cfcd3052f054961ba977d9d3aec4/extremeflash/tftp_server.py#L27-L32

#### commands ran

```
flake8 . --count --show-source --statistics
./extremeflash/tftp_server.py:28:63: E231 missing whitespace after ':'
        logging.info(f"Starting tftp server on {self.listenip}:{self.port} from {self.tmpdir}")
                                                              ^
1     E231 missing whitespace after ':'
1
```

**Comment by sigmavirus24** [comment]
Please re-read the issue template. Flake8 does not implement any checks.

**Comment by leopepe** [comment]
It also happens with `pycodestyle 2.9.1` and `python 3.10.12`.
I solved it by removing flake8 as our lintting tool and using [ruff](https://pypi.org/project/ruff/) instead ;-)
