### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by wuch-g2v** [PyCQA/flake8#1860]
### describe the request

Is it possible next time on release new version make the github release to have entry on https://github.com/PyCQA/flake8/releases
 entries? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

I'm fairly certain we've repeatedly rejected this. We tag all releases. The fact GitHub doesn't notify on those instead is a bug. Asking is to do more work to comply with some company profiting off of our new work and behavior is unacceptable

**Comment by bryevdv** [comment]
@sigmavirus24 In the future, please don't make baseless assumptions. If you are going to berate your users who care enough about your project to submit a feature idea and even include helpful supporting documentation, you should be more than "fairly certain". There are four pages of results at:

https://github.com/PyCQA/flake8/issues?page=2&q=is%3Aissue+github+release+is%3Aclosed

and none of them (besides this one) seem to bear any relevance. Frankly I think you owe an apology. That said, as consistently antagonistic as the maintainers here are to nearly every user who comes by, I am honestly not sure why you don't just turn the public issue tracker off completely, or even move off GitHub entirely. 

@wuch-g2v FYI in case it it useful to you, be aware that GitHub publishes an Atom feed for repo tags: 

https://github.com/PyCQA/flake8/tags.atom

**Comment by asottile** [comment]
@bryevdv fwiw I believe the duplicate ian is referring to became deleted when the account which created it was banned from github -- so apologies for that part.

the author in question of this issue however is a ban evasion account which is why this was not taken lightly.

**Comment by sigmavirus24** [comment]
To be clear https://github.com/certifi/python-certifi/issues/238 is another duplicate from this same person who has created three accounts to avoid the fact that the PSF has banned them for their behavior and many other communities do not want them involved.

They're not trying to hide that they want to evade bans. It's not hard to find their extremist views or their past behavior that has led to communities wanting to prevent their interactions
