### ISSUE TITLE
path separator typo

### ISSUE THREAD

**Issue by r-leyshon** [PyCQA/flake8#1862]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
NA
```

#### what I expected to happen

small catch where condition [checks for presence of alternate_separator twice](https://github.com/r-leyshon/flake8/blob/a2b02b8920e0223940e6eb9c9f062c182cd83038/src/flake8/utils.py#L179). 

#### sample code

```python
        or (alternate_separator and alternate_separator in path)
```

to

```python
        or (alternate_separator and separator in path)
```

#### commands ran

NA

**Comment by asottile** [comment]
no the code is correct.  it is for Windows
