### ISSUE TITLE
Warn when f-string with non-local variable used? Warn when f-string converting function to str is used?

### ISSUE THREAD

**Issue by mpasternak** [PyCQA/flake8#1872]
Hello, 

I am not sure if this belongs to flake8 and I'm not sure how to bite this exactly, but I have feeling somewhere in the back of my head, that this should be made visible to the end-user, aka programmer. 

If this does not belong to flake8, please help me and show me the direction I should take it to. 

I recently made a somewhat funny bug in my codebase. 

It looked like this: 

`SOME_CONST = f"http://some.host/{id}"
`

The bug-introducing character was that little "f" before the starting quote. 

I meant to declare a string, that gets `.format`'ted some time later (like first I defined the URL with the place for the parameters, then I wanted to do `SOME_CONST.format({"id": "some_id"})`)

Instead, I declared a constant that looked like `http://some.host/<builtin function id>`. To add to the injury, `.format()` on that constant worked without problems at all, obviously. 

First I wonder what would I like to do with that. We already have a warning for when there are f-string format characters and the string is missing the starting "f". 

This would be the opposite, but only for some symbols. 

On the other hand, there is very little chance somebody would want to have a string-description of a function embedded in a string constant. 

So, warning about a variable found in f-string not declared in the local scope could be okay, but I am not sure if this is even possible. That `SOME_CONST` was declared at the top level of the module, all the imported things and symbols were available. Of course that `id()` was in the builtins, not in the module scope. 

Maybe it would be sensible to warn the user about converting function-type object to a string in a string constant. I think that this is not the thing people like to do on the daily basis. 

I would like to know your opinion on this problem first, if there are any, I think that it would be worth to add a plugin for it some time later, maybe. 

Any opinions?

**Comment by asottile** [comment]
flake8 does not implement any checks
