### ISSUE TITLE
Warn about ignored flake8 configurations

### ISSUE THREAD

**Issue by ekoyle** [PyCQA/flake8#1881]
### describe the request

Would it be reasonable to add a warning that ~/.flake8 and ~/.config/flake8 are no longer honored if either of those files exists?  Maybe with a link to the relevant discussion of why the behavior has changed? The change in behavior is surprising to users and seems to be frequently reported. Adding a warning would keep users from spending a lot of time trying to figure out why their workflow broke only to find that the change was intentional and is not considered a bug.

It could also be helpful to add a similar warning if there are multiple flake8 configurations in the same project, stating which of them will be ignored and recommending that the less-preferred flake8 configuration be removed to avoid confusion.

**Comment by asottile** [comment]
search better and you will find the exact duplicates

**Comment by ekoyle** [comment]
I found this: https://github.com/PyCQA/flake8/issues/1479#issuecomment-981099907 and this: https://github.com/PyCQA/flake8/issues/1704#issuecomment-1265378099

I apologize if I missed more discussion somewhere. It is harder to find than I thought it would be as it is not all in one place.

After reading, it sounds like the main concern with adding these checks is affecting performance for the majority of users by doing additional checking.

I think it would be reasonable to emit a message if: 1) no flake8 config has been found and 2) one of the ~/.flake8 or ~/.config/flake8 files exists. Would you accept a PR that adds two calls to os.path.exists for this narrow case? That should have no measurable effect on performance, but could save a lot of time for people who were depending on the old behavior (which is almost guaranteed if those files exist). 

I also saw claims in some of the discussion threads that this is a corner case and/or undocumented feature, however it was clearly documented and Google still happily returns this page: https://flake8.pycqa.org/en/3.1.1/user/configuration.html . I don't have a problem with the change in behavior, but there are still blogs and old docs referencing it on the Internet. I think the feature may have been more widely used than you think, and you will likely continue to get bug reports when people find it doesn't work without adding some kind of feedback from flake8.

**Comment by asottile** [comment]
no means no
