### ISSUE TITLE
E712 recommends "worse" option

### ISSUE THREAD

**Issue by Tom-Finke** [PyCQA/flake8#1884]
### how did you install flake8?

```console
pre-commit https://github.com/pre-commit/pre-commit-hooks
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.5",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.11.1"
    },
    {
      "plugin": "pyflakes",
      "version": "3.1.0"
    }
  ],
  "version": "6.1.0"
}
```

#### what I expected to happen

Flake8 should recommend replacing "x == True" with just "x"
Instead it suggests using "x is True", which, according to the official Style guide (see https://peps.python.org/pep-0008/#programming-recommendations) is actually worse. Which makes sense, because x  has to be True not truthy when using "is True"

See also https://github.com/grantmcconnaughey/Flake8Rules/issues/58

#### sample code

```python
x = 1
x == True
```

**Comment by asottile** [comment]
please read the issue template and the prompts next time -- this is not the place
