### ISSUE TITLE
Support for union type hints using "bitwise or"

### ISSUE THREAD

**Issue by hakonhagland** [PyCQA/flake8#1889]
Does flake8 support union type hints using "bitwise or", see https://docs.python.org/3/library/stdtypes.html#types-union

For this signature:

    def __init__(self, path: Path, template_name: str|None) -> None:

I get error like:

    E227 missing whitespace around bitwise or shift operator

**Comment by sigmavirus24** [comment]
Flake8 does not implement any error codes and you haven't provided any information about the version of flake8. Please read the issue template
