### ISSUE TITLE
Q: List of available/active rules

### ISSUE THREAD

**Issue by mheden** [PyCQA/flake8#1892]
### describe the request

Is it possible to generate a list of all available rules (including plugins)? I couldn't see any suitable commandline switches nor the API but if its not there, I think it would be a useful feature to add.

**Comment by sigmavirus24** [comment]
Mobile search is failing me but plugins do not specify all of the rules they implement. They provide an entry point and we provide what they return as part of execution. This is impossible unless we break every existing plugin to require them to provide this information

**Comment by sigmavirus24** [comment]
I do believe there are duplicates so I'm closing this but I don't have a reference because mobile search isn't giving me everything

**Comment by asottile** [comment]
flake8 --help is the closest

**Comment by mheden** [comment]
@sigmavirus24 thanks, I didn't found any duplicate tickets when I searched but I can assume there probably are some.

Alright, an API change doesn't feel good so I get it. Thanks for a great tool non the less!
