### ISSUE TITLE
Throwing a lint error when there isn't one

### ISSUE THREAD

**Issue by L1st3r** [PyCQA/flake8#1904]
### how did you install flake8?

```console
pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.11.7",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.11.1"
    },
    {
      "plugin": "pyflakes",
      "version": "3.1.0"
    }
  ],
  "version": "6.1.0"
}
```

#### what I expected to happen

I have updated my docker compose files to use the new include functionality. Flake8 throws the error:

Incorrect type. Expected "include".yaml-schema: docker-compose.yml

#### sample code

```
version: '3.8'

include:
  - ../devops/docker-compose.yml

services:
```

That does properly call the other docker compose file as well. So I'm not sure why Flake8 is getting upset?

**Comment by asottile** [comment]
that's not flake8 telling you that -- that's something else

**Comment by L1st3r** [comment]
Damn my bad!
