### ISSUE TITLE
Allow the enforcing of some type hint practices

### ISSUE THREAD

**Issue by AdrianB-sovo** [PyCQA/flake8#1908]
### describe the request

I would like an option to enforce some coding style for the type hints.
For example:

- Enforce `dict[str, Any]` instead of `Dict[str, Any]` (and all the generic types from `typing` that are in the standard collection since 3.9).
- Enforce `TypeA | TypeB` instead of `Union[TypeA, TypeB]`.

**Comment by asottile** [comment]
use a plugin or formatter for it, pyupgrade helps

you'll note from the issue template that flake8 does not implement any checks
