### ISSUE TITLE
Update plugin registration documentation about entry points

### ISSUE THREAD

**Issue by Viicos** [PyCQA/flake8#1920]
### describe the request

Hello,

The documentation currently [states](https://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html#registering-a-plugin-with-flake8):

> **Flake8** relies on functionality provided by setuptools called [Entry Points](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points). These allow any package to register a plugin with **Flake8** via that package’s `setup.py` file.

Any interest in having this part of the documentation updated to point to the [Packaging user guide](https://packaging.python.org/en/latest/specifications/entry-points/) instead, so that people can be aware this is not a setuptools-only feature anymore?

(Without changing the setup.py example, I believe it is still up to date?)

**Comment by sigmavirus24** [comment]
Sure. If merge a PR that updates that. For reference pkg_resources is also deprecated for a library in the standard library so it's worth mentioning that too

**Comment by pomponchik** [comment]
It could be great add something about setting up by `pyproject.toml` file.

**Comment by sigmavirus24** [comment]
The packaging user guide already has examples for all types of package metadata config so that doesn't need to be replicated here

**Comment by Viicos** [comment]
Yes I was thinking more about linking the packaging user guide, and explicitly stating "we give an example with `setuptools` (and `setup.py`) but this is now a standard blabla.."

Will probably have time to work on this by the end of the week
