### ISSUE TITLE
you didn't search closed though did you?

### ISSUE THREAD

**Issue by senhalil** [PyCQA/flake8#1934]
you didn't search closed though did you?

_Originally posted by @asottile in https://github.com/PyCQA/flake8/issues/1933#issuecomment-2088917801_
            

The answer is in the description of the issue. Did you miss?

**Comment by sigmavirus24** [comment]
#1336 is one such issue you would have seen had you searched for duplicates. There are others. This would have answered your question that you ignored the template's instructions to ask in a curt manner. If you continue to open issues like this, you will be blocked from the organization for a period of time
