### ISSUE TITLE
flake8 consumes a lot of RAM and 100% CPU usage

### ISSUE THREAD

**Issue by vyunolbek** [PyCQA/flake8#1936]
### how did you install flake8?

```console
$ pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.12.3",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.9.1"
    },
    {
      "plugin": "pyflakes",
      "version": "2.5.0"
    }
  ],
  "version": "5.0.0"
}
```

#### what I expected to happen
flake8 succeeds with no issues
...

#### sample code
A typical project with multiple folders

#### commands ran

```console
$ flake8 --config=dir/.config/lint.cfg dir
...
```
I can't attach what the console outputs, because the computer just shuts down due to lack of RAM. Previously, it returned the RecursionError error: maximum recursion depth exceeded. Now he just goes on the defensive

**Comment by sigmavirus24** [comment]
There's not enough information to reproduce this and I haven't ever seen it behave like this, even on larger projects like openstack
