### ISSUE TITLE
B017 - Suppress warning when msg param is passed to assertRaises

### ISSUE THREAD

**Issue by slw07g** [PyCQA/flake8#1940]
### describe the request

Consider suppressing B017 where `msg=` is passed to assertRaises, as it also validates the actual message in the raised exception matches `msg`.

Example:
`assertRaises(Exception, msg="Some exception message")`

It is equivalent to `assertRaisesRegex(Exception, "^<regex_pattern>$")` which does not trigger B017.

**Comment by sigmavirus24** [comment]
Flake8 does not define any checks or implement them which is clearly described in the issue template and documentation. Please find the correct place to file this instead
