### ISSUE TITLE
release notes for 7.1.0, while in the repository, are not in the published documentation

### ISSUE THREAD

**Issue by colons** [PyCQA/flake8#1945]
### describe the problem

release notes for 7.1.0 are present [in the repo](https://github.com/PyCQA/flake8/blob/main/docs/source/release-notes/7.1.0.rst), but not [on the built docs website](https://flake8.pycqa.org/en/latest/release-notes/index.html)

**Comment by asottile** [comment]
should be available now, readthedocs kinda has gotten worse and worse over the years :/
