### ISSUE TITLE
Copy-pasted code seems to be missing attribution

### ISSUE THREAD

**Issue by lhinderberger** [PyCQA/flake8#1951]
### how did you install flake8?

```console
not applicable (see problem description)
```

### unmodified output of `flake8 --bug-report`

```json
not applicable (see problem description)
```

### describe the problem

Hello Flake8 maintainers,

while having a look at Flake8's source code, I found two files in which code seems to have been copy-pasted from other projects without full attribution:

- src/flake8/processor.py - The comment next to it says, mutate_string was taken wholesale from pycodestyle.
- src/flake8/_windows_color.py - The contents of this file seem to be copied verbatim from the pre-commit project, as indicated in the URL given in the file.

While it looks like both original projects use an MIT-style license just like Flake8, the original copyright notices were apparently not retained when copying the code to Flake8.

I want to bring this problem to your attention, but please be aware that I am not a lawyer and I cannot give legal advice.

**Comment by asottile** [comment]
yeah I copied my own code
