### ISSUE TITLE
Missing link to "pinned issue"

### ISSUE THREAD

**Issue by FlorentP42** [PyCQA/flake8#1956]
### how did you install flake8?

N/A

### unmodified output of `flake8 --bug-report`

N/A

### describe the problem

@asottile would you please update the comments in the following tickets with the actual link to what you call the "pinned issue" : 

- https://github.com/PyCQA/flake8/issues/1445
- https://github.com/PyCQA/flake8/pull/1382

For me there is no such thing as "pinned issues" in the [issues](https://github.com/PyCQA/flake8/issues) view of this repository : 
![Image](https://github.com/user-attachments/assets/18793648-1819-49a3-b079-3338acc21e0c)

And I am actually interested in what would be the solution to that problem as I encountered it in a completely different context.

**Comment by asottile** [comment]
search the error message then. you'll find the duplicates without my help
