### ISSUE TITLE
the config file .flake8 only work when it is at current work dir?

### ISSUE THREAD

**Issue by caixxiong** [PyCQA/flake8#1959]
### describe the request

I must put the .flake8 file to current dir, it will be work. And if i put it at ~/.flake8, it will not work now. I remember about one years ago, when put it at ~/.flake8, it works ok, but now?

here is my .flake8 at ~/.flake8

```shell
# ~/.flake8
[flake8]
ignore = E501, W605, E117, E116, F403, F405, W504, E711, E402, W503, E741

# line too long (95 > 79 characters) [E501]
# invalid escape sequence '\|' [W605]
```

**Comment by asottile** [comment]
the documentation answers your question

**Comment by caixxiong** [comment]
> the documentation answers your question
So? I read the doc, it say put at ~/.flake8 ok for linux? but it still failed when i use vim for python files.

**Comment by asottile** [comment]
where does it say that?

**Comment by sigmavirus24** [comment]
Nowhere in https://flake8.pycqa.org/en/latest/user/configuration.html does it say that. The documentation shows that over 3 years ago, your expectation stopped working purposefully. https://flake8.pycqa.org/en/latest/release-notes/4.0.0.html#backwards-incompatible-changes
