### ISSUE TITLE
Config uses tox file even when no flake8 config in it

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#199]
In GitLab by @adamchainz on Nov 21, 2016, 03:51

*Please describe how you installed Flake8*

```
$ pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
$ flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "23.1.0"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "2.7.12",
    "system": "Darwin"
  },
  "plugins": [
    {
      "plugin": "flake8-tidy-imports",
      "version": "1.0.0"
    },
    {
      "plugin": "mccabe",
      "version": "0.5.2"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.2.0"
    },
    {
      "plugin": "pyflakes",
      "version": "1.3.0"
    }
  ],
  "version": "3.2.0"
}
```

*Please describe the problem or feature*

I have a project with many subprojects each using `tox`. I'd like to define my lint rules at the top level in a `setup.cfg` and have individual `tox.ini` files for each subproject.

Currently the existence of `tox.ini`, without a `flake8` header, causes `flake8` to consider itself 'configured' with just the defaults, and the search for the config stops. I would expect it to find the flake8 config in my `setup.cfg` instead.

It's also non-deterministic based upon the current directory when `flake8` is run.

My current workaround is to always invoke `flake8` with `--config` pointed to the absolute path of the config file, which isn't ideal.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

```
$ tree .
.
├── setup.cfg
└── subproj
    ├── test.py
    └── tox.ini

1 directory, 3 files
$ cat setup.cfg
[flake8]
max-line-length = 120
$ cat subproj/tox.ini
[tox]
something = something
$ cat subproj/test.py
# this line is longer than 80 chars but less than 120 chars and so should be allowed, but it isn't
$ flake8  # passes
$ flake8 subproj/test.py  # fails
subproj/test.py:1:80: E501 line too long (98 > 79 characters)
$ cd subproj
$ flake8  # fails
./test.py:1:80: E501 line too long (98 > 79 characters)
```

**Comment by asottile** [comment]
In GitLab by @OmeGak on Dec 28, 2017, 10:50

> Currently the existence of `tox.ini`, without a `flake8` header, causes `flake8` to consider itself 'configured' with just the defaults, and the search for the config stops. I would expect it to find the flake8 config in my `setup.cfg` instead.

I don't think this is happening anymore. I cannot reproduce it, at least.

**Comment by asottile** [comment]
In GitLab by @manthey1 on Jan 8, 2018, 12:21

I just ran into this issue today (on version 3.5.0).  Mine was a variation caused by the same issue, I had a setup.cfg file in the subdirectory that had no flake8 related values in it, but flake8 stopped looking for a config file once it found that one.

**Comment by asottile** [comment]
In GitLab by @asottile on May 22, 2019, 14:14

can confirm given the setup above.  I might try and address this as part of the rework of configuration loading

**Comment by asottile** [comment]
via #1472

**Comment by adamchainz** [comment]
Awesome! 👍👍👍
