### ISSUE TITLE
Flake8 not compability with new walrus operator implanted in python3.8

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#323]
In GitLab by @MrYacha on Nov 19, 2019, 13:11

Please read this brief portion of documentation before going any further: http://flake8.pycqa.org/en/latest/internal/contributing.html#filing-a-bug

example:
```
k = [1,2,3,4,5,6]
if klen := len(k) > 3:
   print('yes')
else:
   print('no')
```
will trow:
```
test.py:2:8: E203 whitespace before ':'
test.py:2:9: E701 multiple statements on one line (colon)
test.py:2:9: E231 missing whitespace after ':'
```

*Please describe how you installed Flake8*

```
$ pip3 install git+https://github.com/PyCQA/flake8 -U
```

**Note**: Some *nix distributions patch Flake8 arbitrarily to accommodate incompatible software versions. If you're on one of those distributions, your issue may be closed and you will be asked to open an issue with your distribution package maintainers instead.

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.0",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.4.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    }
  ],
  "version": "3.7.9"
}
```

*Please describe the problem or feature*

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

**Comment by asottile** [comment]
In GitLab by @MrYacha on Nov 19, 2019, 13:12

changed the description

**Comment by asottile** [comment]
In GitLab by @asottile on Nov 19, 2019, 13:13

flake8 is just a framework and does not implement any lint checks itself, for E* you want pycodestyle

in the future please read the document at the beginning of the bug report and please search the issue tracker as well -- thanks!

**Comment by asottile** [comment]
In GitLab by @asottile on Nov 19, 2019, 13:13

closed

**Comment by asottile** [comment]
In GitLab by @heckad on Apr 27, 2020, 12:01

It's a core functionality of python. Why it's not supported?

+1 reopen

**Comment by asottile** [comment]
In GitLab by @asottile on Apr 27, 2020, 12:40

@heckad first off, please consider the words you are using -- while it's possible you don't mean ill intent from your message it is extremely easy for that to be construed as aggressive.  please be more considerate, especially when asking things of projects which are operating _for free_ (or consider sponsoring the maintainers instead of demanding work).

flake8 (as stated above) is just a framework, it (the framework) functions just fine in python3.8.

as for why there _were_ problems -- two of the things which flake8 wraps (pyflakes, pycodestyle) are reasonably sensitive to syntax changes (pyflakes is less so now that I've [done this](https://github.com/PyCQA/pyflakes/pull/490)) and take time to update.  the change in pycodestyle was particularly tricky because it required relaxing several rules to allow for the new "operator" because the `:` character could now appear in more contexts

lastly, you'll find that this is **already fixed and released**.  you can try it out in `flake8>=3.8.0a2`

**Comment by asottile** [comment]
In GitLab by @adam.hoelscher on Aug 5, 2020, 13:41

I'm still seeing this issue with `flake8==3.8.3`. Is there something I can do to help?

```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.1",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.2.0"
    }
  ],
  "version": "3.8.3"
}
```

**Comment by asottile** [comment]
In GitLab by @asottile on Aug 5, 2020, 15:16

@adam.hoelscher try running `pip check`

**Comment by asottile** [comment]
In GitLab by @justnpT on Sep 17, 2020, 04:44

@asottile  I run pip check and no broken requirements were found:
![image](/uploads/1dbfc181385594b1e27631ff6b907407/image.png)

my flake8 version is 3.8.3
![image](/uploads/63bab4d86f62a31938b9f4ae45e23c72/image.png)

yet I still get the walrus errors
![image](/uploads/971d3be64ffb56ccaccbb1d965f921e8/image.png)

so I need to exclude the errors from walrus lines
![image](/uploads/34cf6d85c479dfbed9ada959a8fa8e3e/image.png)

**Comment by asottile** [comment]
In GitLab by @asottile on Sep 17, 2020, 09:09

did you mean `pip3 check` (or whatever python `flake8` is installed to)?

also please do not post screenshots of text -- they are not accessible, searchable, or readable

**Comment by asottile** [comment]
In GitLab by @asottile on Sep 17, 2020, 09:10

also if you're getting E999, that means you're using a version of python which does not support walrus

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Sep 17, 2020, 15:56

@asottile I'm not convinced that people are respecting your time here and I'm thinking we should lock this issue. If folks read the prior comments and followed the debugging instructions you gave previously, they'd likely end up resolving this themselves and I'm not sure your providing the same help over-and-over again is productive

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Sep 17, 2020, 15:57

locked this issue

**Comment by justnpT** [comment]
Guys, i am just high after patty. I had to log in because I had the notification. Why are you asking me for attention. Anyway, God exists. And you know it . Peace eeeeeeee and be Strong
