### ISSUE TITLE
Feature proposal: baseline for legacy projects

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#330]
In GitLab by @sobolevn on Dec 23, 2019, 03:38

One of the greatest obstacles of using a good linter is legacy code and issues you already have.

`flakehell` solves this issue with the concept of a `baseline`: https://flakehell.readthedocs.io/commands/baseline.html

I propose to add it into the core, because it is priceless in terms of adoption.
I have spent from tens to hundreds hours of conversations with team and technical leads discussing adoption of https://github.com/wemake-services/wemake-python-styleguide and this problem was the first one in the list in 100% of cases.

How does `baseline` work? You run `flake8 --create-baseline > .flake8baseline` to save all violations you already have into a `json` file. Then when you run your linter as `flake8 --baseline=PATH` all old violations are ignored. And only new or changed ones raise an error:

1. When writing new code
2. When refactoring existing one and making at uglier/more complex/etc

This is an implementation of the "boy-scout rule": when you touch something, you have to clean it up.

I can work on this during the holiday season.

**Comment by asottile** [comment]
In GitLab by @asottile on Dec 23, 2019, 05:45

I think the idea is fine but playing devil's advocate: do we need this when there's already inline-ignore (`# noqa`) and `per-file-ignores`?

when we moved to establish a baseline at yelp when adopting flake8, we wrote a thing (that in retrospect probably would have been useful to open source -- but it's too late for that now that I don't work there!) that tried to apply `# noqa` comments to files with few violations, and excluded files with 100% violations (such as files which were just `*` imports or `__init__.py` files)

**Comment by asottile** [comment]
In GitLab by @sobolevn on Dec 23, 2019, 06:50

> do we need this when there's already inline-ignore (`# noqa`) and `per-file-ignores`?

Good point! The difference is simple. Imagine a large code base (like 100.000s lines of code) and a new linter with tons of violations. Every file will be over-floated with `noqa` and `per-file-ignores` will be too large. And you are required to analyse what is going on with each particular case, make a decision, put dozens of `noqa` here and there. It might be too long or even impossible for a human being.

But, `flake8 --create-baseline` just works. You run one command once and you are good to go. 

And one more thing. With `baseline` you can easily go further and enable (as I call it) "Refactoring mode". When you are required to reduce the violation count by the given threshold each time you commit your code. Details: https://github.com/life4/flakehell/issues/5 And possibly any other features you can imagine (like graphs, stats, burndown-charts, panning, etc) that are possible with `baseline` and are hardly possible with raw `noqa`.

My experience with `flakehell` was pleasant enough to propose this feature into the core library.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jan 23, 2020, 17:10

> But, `flake8 --create-baseline` just works. You run one command once and you are good to go.

So I've thought about this a few times. For one thing, how we do this is tricky. That baseline file could introduce extra frustration. What if someone renames a directory or file?

My first instinct is to use per-file-ignores but we know that doesn't perform well for giant projects. If instead we used something else we could be more efficient about storage and application of the baseline.

**Comment by asottile** [comment]
In GitLab by @sobolevn on Mar 23, 2020, 02:55

I have started to work on this in `wemake-python-styleguide`: https://github.com/wemake-services/wemake-python-styleguide/issues/1274

I am going to test this feature and then I can send a PR with the backport to `flake8` if you are interested.

**Comment by asottile** [comment]
In GitLab by @sobolevn on Mar 24, 2020, 01:06

Done: https://github.com/wemake-services/wemake-python-styleguide/pull/1276

I invite you guys to review it if you wish! @asottile @sigmavirus24

**Comment by Dreamsorcerer** [comment]
Before this gets lost, it looks like the baseline feature will not be implemented in wemake-python-styleguide, so someone will probably need to volunteer to reimplement the code in flake8 directly.

I no longer need the baseline functionality, so don't plan to do further development on it. However, I used it on a project for several months and am confident that it's ready for a public release. if someone wants to take on the port to flake8, my PR to wemake is available and I'm happy to answer any questions about it: https://github.com/wemake-services/wemake-python-styleguide/pull/1471

There are a few additional ideas that could be implemented to improve future releases (in particular see [#1276 (comment)](https://github.com/wemake-services/wemake-python-styleguide/pull/1276#issuecomment-646757232) and the disabled all_change test: https://github.com/wemake-services/wemake-python-styleguide/pull/1471/files#diff-d0914f16c784a2349a4008ccc24c17220012a08741e8c54f290c74dd488efaa1R148).

**Comment by asottile** [comment]
fwiw it's unlikely to be implemented here given `per-file-ignores` can already be leveraged to a similar intent and the complexity for a true baseline doesn't seem worth it

**Comment by Dreamsorcerer** [comment]
I think the baseline provides a lot of advantages over `per-file-ignores` when it comes to adding flake8 to an existing project. You can check the whole project and ensure that no new violations are added while slowly improving the codebase. I was using this on a 30k+ line project with 1000s of violations, and cleaned up ~25% of violations without even trying. `per-file-ignores` would have been entirely useless on this project.

Of course, I'm not the one that has to deal with maintaining this project after merging such a feature.. so, I guess the only option for anyone wanting to take this on is a separate plugin for baseline alone. Again, just send me a message if you're interested and have any questions about the code in that PR.

**Comment by asottile** [comment]
I think the better solution is to just use a code formatter to fix the problems

**Comment by Dreamsorcerer** [comment]
If you have a formatter which can fix all flake8 violations, then you might as well stop using flake8. :P

We used a lot of extra plugins, so I highly doubt a formatter would have fixed the majority of violations (in fact, I recall we were using black, so the flake8 violations were mostly not style violations).
