### ISSUE TITLE
--disable-noqa not working consistently

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#343]
In GitLab by @yumasheta on Feb 4, 2020, 16:19

*Please describe how you installed Flake8*

```
$ pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*
```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.1",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    }
  ],
  "version": "3.7.9"
}
```

*Please describe the problem or feature*

Consider this code snippet:
```python
# test.py
print("this line is definitely to long for flake8 with default settings and should produce an error.")  # noqa: E501

pass

import math  # noqa: E402
print(math.pi)
```

When using the `--disable-noqa` flag, only the first error is shown:
```
$ flake8 --disable-noqa test.py 
test.py:1:80: E501 line too long (119 > 79 characters)
```

May be ralated to issue #590

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 4, 2020, 16:22

could you try against master?  I believe I fixed this (I believe this is pycodestyle interpreting the noqa separate to flake8)

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 4, 2020, 16:24

yep, this works on master:

{noformat}
$ flake8 t.py  --disable-noqa
t.py:2:80: E501 line too long (116 > 79 characters)
t.py:6:1: E402 module level import not at top of file
{noformat}

via !331

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 4, 2020, 16:24

closed

**Comment by asottile** [comment]
In GitLab by @yumasheta on Feb 4, 2020, 16:32

yes, is fixed on master
can confirm

**Comment by Melevir** [comment]
Hey. This one is still valid for me. Sample from TC works fine, but if I will replace E501 error with T001 (from flake8-print), everything gets worse.

So, `test.py`:

```python
import math
print(math.pi)  # noqa: T001
```

```bash
$ flake8 --disable-noqa test.py
```

But if I will remove the error from the comment:

```python
import math
print(math.pi)  # noqa
```

Then error pops out:

```bash
$ flake8 --disable-noqa ~/projects/zipsale/zipsale-web/test.py
test.py:2:1: T001 print found.
```

```bash
$ flake8 --bug-report                                  
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.0a6",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-print",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    }
  ],
  "version": "4.0.1"
}
```


I'll be glad to solve the issue, but I need some directions on where to look for the code, that does the thing.

**Comment by asottile** [comment]
`flake8-print` has their own incompatible implementation of `noqa` which we have no control over and cannot disable

they should remove that
