### ISSUE TITLE
Add `--per-file-selects` option

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#344]
In GitLab by @rossmacarthur on Feb 15, 2020, 02:58

Since `--per-file-ignores` exists I think it makes sense that `--per-file-selects` exists.

**Example: docstrings**

For example I have a project that has a package, scripts, as well as tests, and wanted to use `flake8-docstrings` on just the package part. Being able to specify the following in the config would be useful:

```
[flake8]
ignore = D
per-file-selects =
    <package-name>/*: D
```

**Example: specific lints from plugins**

Additionally, I am unable to select specific lints for the package part, without having to repeat them in the ignores for the rest of the project. Say for example I wanted just 1 lint from three different plugins X001, Y002, Z003 on the package data. It would be nice to use 

```
[flake8]
ignore = X,Y,Z
per-file-selects =
    <package-name>/*: X001,Y002,Z003
```

But instead I have to do something like
```
[flake8]
ignore = X,Y,Z
select = X001,Y002,Z003
per-file-ignores =
    ci/*: X001,Y002,Z003
    examples/*: X001,Y002,Z003
    scripts/*: X001,Y002,Z003
    tests/*: X001,Y002,Z003
```

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 15, 2020, 06:46

Please demonstrate a use case, I don't think this is necessary

**Comment by asottile** [comment]
In GitLab by @rossmacarthur on Feb 15, 2020, 11:37

changed the description

**Comment by asottile** [comment]
In GitLab by @rossmacarthur on Feb 15, 2020, 11:37

changed the description

**Comment by asottile** [comment]
In GitLab by @rossmacarthur on Feb 15, 2020, 11:37

@asottile I have updated the issue description.

**Comment by asottile** [comment]
In GitLab by @rossmacarthur on Feb 15, 2020, 11:44

changed the description

**Comment by asottile** [comment]
In GitLab by @asottile on Feb 15, 2020, 16:51

your use case, couldn't you use `per-file-ignores` instead?

**Comment by sigmavirus24** [comment]
Agree that this isn't necessary. Good call closing this out

**Comment by asottile** [comment]
I don't think you need/want per-file-selects in that case -- you can just ban it in the entire codebase (this already passes minus the one case you've identified)

**Comment by MarcoGorelli** [comment]
> this already passes minus the one case you've identified

Not sure what you mean here, there's several cases outside of `tests` where it doesn't pass (note that the check in the linked PR has `files: ^pandas/tests`)

**Comment by asottile** [comment]
I only see the reference to np.testing in the door that's changed in the pr

**Comment by PeterJCLaw** [comment]
A use-case I'd like to have `--per-file-selects` for is to have stronger lints in some files than others. In our Django codebase we have a lot of Django apps, each of which has an `api.py` that exposes the main API of that app to the rest of the codebase. I'd like to be able to lint those files to require e.g: that all the public members have docstrings.

Currently I'd need to exhaustively name all the possible file names which _aren't_ `api.py` and disable docstring related lints from those files.
