### ISSUE TITLE
How to add a check to verify that all packages have a README.md file

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#602]
In GitLab by @mitar on Jul 24, 2017, 05:54

I was considering implementing a plugin which would require that every sub-package (sub-directory with `__init__.py`) of my larger Python package contains a `README.md` file. It seems this is not really possible to do with current plugin system?

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 25, 2017, 04:24

Hi @Mitar,

I already answered this elsewhere. Please stop asking questions on our *defect* trackers. The code-quality mailing list is the correct place to have these discussions.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 25, 2017, 04:24

closed

**Comment by mitar** [comment]
For posterity, I made it using pylint: https://gitlab.com/aika/aika/-/blob/main/bin/pylint/require_readme.py
