### ISSUE TITLE
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#646]
In GitLab by @mgedmin on Feb 14, 2018, 05:30

*Please describe how you installed Flake8*

I've an always-activated virtualenv ~/.venv into which I've installed flake8

```
$ pip install -U flake8
```

I also sometimes want to run flake8 against Python 3 code (by running `python3 -m flake8`), so I also did

```
$ pip3 install --user -U flake8
```

and, for symmetry (`python -m flake8`),

```
$ pip install --user -U flake8
```

This has worked well for me in the past.

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
{
  "dependencies": [
    {
      "dependency": "setuptools", 
      "version": "38.5.1"
    }
  ], 
  "platform": {
    "python_implementation": "CPython", 
    "python_version": "2.7.14", 
    "system": "Linux"
  }, 
  "plugins": [
    {
      "is_local": false, 
      "plugin": "mccabe", 
      "version": "0.6.1"
    }, 
    {
      "is_local": false, 
      "plugin": "pycodestyle", 
      "version": "2.3.1"
    }, 
    {
      "is_local": false, 
      "plugin": "pyflakes", 
      "version": "1.6.0"
    }
  ], 
  "version": "3.5.0"
}
```

*Please describe the problem or feature*

While `flake8` works fine, `python3 -m flake8` and `python3 -m flake8` fail on startup:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 178, in load_plugin
    self._load(verify_requirements)
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 150, in _load
    self._plugin = resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2326, in resolve
    raise ImportError(str(exc))
ImportError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/home/mg/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.
```

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

**Comment by asottile** [comment]
In GitLab by @mgedmin on Feb 14, 2018, 05:36

Oh.  I figured out what was wrong.

I (or, rather, my Vim plugin) was running `python -m flake8` *while I was inside ~/src/pycodestyle*, which is a git clone of https://github.com/PyCQA/pycodestyle.

Python implicitly adds `.` to sys.path, so `python -m flake8` was importing `./pycodestyle.py`.

The git master of pycodestyle doesn't have a `break_around_binary_operator` function any more.  (For extra confusion, the maintainer of pycodestyle doesn't add `.dev0` to their `__version__` number, so pycodestyle git master claims it's version 2.3.1 despite having different---and incompatible---code.)

I do not know if flake8 can do anything to avoid trouble in this kind of situation.  (Although, heads up: the upcoming pycodestyle release will break flake8 because of the removal of `break_around_binary_operator`.)

**Comment by asottile** [comment]
In GitLab by @sfdye on Apr 10, 2018, 07:41

@mgedmin It's happening for us

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 10, 2018, 08:42

@sfdye do not force pycodestyle to install 2.4.0 then. The released version(s) of Flake8 explicitly cap the version supported at `< 2.4.0`

**Comment by asottile** [comment]
In GitLab by @sfdye on Apr 10, 2018, 08:47

@sigmavirus24 Sure. Someone has raised an issue with pycodestyle already https://github.com/PyCQA/pycodestyle/issues/741

**Comment by asottile** [comment]
In GitLab by @cbrnr on Apr 12, 2018, 24:25

Not installing 2.4.0 works, but this is not a good solution. If you just `pip install pycodestyle` (which is what most people will do by default), you will get 2.4.0. Making flake8 work with the latest version of pycodestyle would be awesome (see also #415).

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Apr 12, 2018, 04:20

@cbmr so you always manually install your own dependencies for projects you use? And everyone else does this? That doesn't sound right to me.

> Making flake8 work with the latest version of pycodestyle would be awesome

It will. Just not an already released version. When our [version constraints](https://gitlab.com/pycqa/flake8/blob/master/setup.py#L25) change, we release a new minor version.

**Comment by asottile** [comment]
In GitLab by @cbrnr on Apr 12, 2018, 04:23

No, I don't manually install dependencies. I routinely do a `pip list --outdated` and then update all outdated packages. Apparently, `pip` is not smart enough to detect these kinds of conflicts, because I never saw a warning or error message. I believe that many people routinely update their packages like that.

Looking forward to the update, thanks for the great work and providing such an essential tool for Python!

**Comment by asottile** [comment]
In GitLab by @cbrnr on Apr 12, 2018, 05:10

Oh yeah, in case you were wondering, `conda` is actually smart about this, because it downgrades `pycodestyle` if you install `flake8` even if you `conda update --all`.

**Comment by asottile** [comment]
In GitLab by @bschaefer on Apr 17, 2018, 07:04

In ArchLinux this prevents me from using the package manager to install `flake8`.

https://bugs.archlinux.org/task/58210?project=5&string=flake8

**Comment by asottile** [comment]
In GitLab by @jiim_e on Apr 17, 2018, 10:19

@bschaefer the fixes have been made, they just haven't been released on pypi yet. I think that'd take a bit of work such as putting together a changelog - I'm sure everyone would appreciate it if you were able to spend the time to help with that process. Maybe @sigmavirus24 can let us know what else needs to be done to make the release happen?

**Comment by asottile** [comment]
In GitLab by @terrisgit on Aug 4, 2018, 09:12

Is there an update? Seems like https://gitlab.com/pycqa/flake8/merge_requests/230 is part of the mix.

**Comment by asottile** [comment]
In GitLab by @terris on Sep 17, 2018, 11:48

#426 is about releasing a version with these fixes.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 20, 2018, 10:07

closed

**Comment by anricoj1** [comment]
For anyone who is still struggling with this in 2022:

- The pycodestyle version is still outdated when you install flake8.
- I had to uninstall pycodestyle then reinstall it manually

**Comment by lalmei** [comment]
> 

@anricoj1  this worked for me thanks!, and I thought I had previously fixed it by fixing the bandit/flak8-bandit versions.
