### ISSUE TITLE
Support using configuration from .editorconfig

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#658]
In GitLab by @KOLANICH on Dec 2, 2018, 05:48

https://editorconfig.org/#file-format-details

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Dec 2, 2018, 07:08

closed

**Comment by KOLANICH** [comment]
As I see, still not fixed. Are you moving back to GitHub? Have you considered SourceHut as an alternative?
