### ISSUE TITLE
Flake8>=3.8.0: 'Namespace' object has no attribute 'output_file' [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#726]
The original issue

	Id: 641
	Title: Flake8>=3.8.0: 'Namespace' object has no attribute 'output_file'

could not be created.
This is a dummy issue, replacing the original one. It contains everything but the original issue description. In case the gitlab repository is still existing, visit the following link to show the original issue:

TODO

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 12, 2020, 04:16

Does this happen with _just_ flake8?

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 04:42

@sigmavirus24, I don't know.   Maybe flake8-rst wrongly uses your plugin API, but right now it seems to me as a flake8 issue.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on May 12, 2020, 05:08

We don't have a public API the way that project uses flake8 so to me it
seems like flake8-rst is using things incorrectly and you're suffering for
it

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 05:30

So, you think I should reopen this issue against flake8-rst repo?

Any glue on _how_ flake8-rst is using things incorrectly?

**Comment by asottile** [comment]
In GitLab by @ericvw on May 12, 2020, 06:25

@skirpichev There was a regression in `flake8==3.8.0` with respect to `--output-file` (see #637).  Can you please confirm if you still observe this issue with `flake8 >= 3.8.1`.  Thanks.

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 07:03

Yes.  The referenced above build logs are for flake8==3.8.1.

**Comment by asottile** [comment]
In GitLab by @ericvw on May 12, 2020, 07:19

Thank you for confirming.  The referenced build logs URI expired, so I was unable to see what version was being used.

**Comment by asottile** [comment]
In GitLab by @ericvw on May 12, 2020, 07:27

`flake8-rst` is using a private API here and is using `flake8` incorrectly.

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 07:29

indeed, was about to comment the same -- thanks for the investigation @ericvw

**Comment by asottile** [comment]
In GitLab by @asottile on May 12, 2020, 07:29

closed

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 07:40

changed the description

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 07:41

Sorry, corrected.

**Comment by asottile** [comment]
In GitLab by @skirpichev on May 12, 2020, 07:43

Ok, thank you for "explanation".

**Comment by asottile** [comment]
In GitLab by @ericvw on Oct 21, 2020, 10:16

mentioned in merge request !458

**Comment by skirpichev** [comment]
@asottile, please STOP this.
